/*
 * DocuSeal API
 * DocuSeal API specs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@docuseal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.docuseal.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.docuseal.models.AddDocumentToTemplateRequestDocumentsInner;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * AddDocumentToTemplateRequest
 */
@JsonPropertyOrder({
  AddDocumentToTemplateRequest.JSON_PROPERTY_DOCUMENTS,
  AddDocumentToTemplateRequest.JSON_PROPERTY_MERGE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class AddDocumentToTemplateRequest {
  public static final String JSON_PROPERTY_DOCUMENTS = "documents";
  @jakarta.annotation.Nullable
  private List<AddDocumentToTemplateRequestDocumentsInner> documents = new ArrayList<>();

  public static final String JSON_PROPERTY_MERGE = "merge";
  @jakarta.annotation.Nullable
  private Boolean merge = false;

  public AddDocumentToTemplateRequest() { 
  }

  public AddDocumentToTemplateRequest documents(@jakarta.annotation.Nullable List<AddDocumentToTemplateRequestDocumentsInner> documents) {
    this.documents = documents;
    return this;
  }

  public AddDocumentToTemplateRequest addDocumentsItem(AddDocumentToTemplateRequestDocumentsInner documentsItem) {
    if (this.documents == null) {
      this.documents = new ArrayList<>();
    }
    this.documents.add(documentsItem);
    return this;
  }

  /**
   * The list of documents to add or replace in the template.
   * @return documents
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DOCUMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<AddDocumentToTemplateRequestDocumentsInner> getDocuments() {
    return documents;
  }


  @JsonProperty(value = JSON_PROPERTY_DOCUMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDocuments(@jakarta.annotation.Nullable List<AddDocumentToTemplateRequestDocumentsInner> documents) {
    this.documents = documents;
  }


  public AddDocumentToTemplateRequest merge(@jakarta.annotation.Nullable Boolean merge) {
    this.merge = merge;
    return this;
  }

  /**
   * Set to &#x60;true&#x60; to merge all existing and new documents into a single PDF document in the template.
   * @return merge
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MERGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getMerge() {
    return merge;
  }


  @JsonProperty(value = JSON_PROPERTY_MERGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMerge(@jakarta.annotation.Nullable Boolean merge) {
    this.merge = merge;
  }


  /**
   * Return true if this AddDocumentToTemplateRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddDocumentToTemplateRequest addDocumentToTemplateRequest = (AddDocumentToTemplateRequest) o;
    return Objects.equals(this.documents, addDocumentToTemplateRequest.documents) &&
        Objects.equals(this.merge, addDocumentToTemplateRequest.merge);
  }

  @Override
  public int hashCode() {
    return Objects.hash(documents, merge);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddDocumentToTemplateRequest {\n");
    sb.append("    documents: ").append(toIndentedString(documents)).append("\n");
    sb.append("    merge: ").append(toIndentedString(merge)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

