/*
 * DocuSeal API
 * DocuSeal API specs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@docuseal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.docuseal.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * Submitter preferences.
 */
@JsonPropertyOrder({
  CreateSubmissionsFromEmailsResponseInnerPreferences.JSON_PROPERTY_SEND_EMAIL,
  CreateSubmissionsFromEmailsResponseInnerPreferences.JSON_PROPERTY_SEND_SMS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class CreateSubmissionsFromEmailsResponseInnerPreferences {
  public static final String JSON_PROPERTY_SEND_EMAIL = "send_email";
  @jakarta.annotation.Nullable
  private Boolean sendEmail;

  public static final String JSON_PROPERTY_SEND_SMS = "send_sms";
  @jakarta.annotation.Nullable
  private Boolean sendSms;

  public CreateSubmissionsFromEmailsResponseInnerPreferences() { 
  }

  public CreateSubmissionsFromEmailsResponseInnerPreferences sendEmail(@jakarta.annotation.Nullable Boolean sendEmail) {
    this.sendEmail = sendEmail;
    return this;
  }

  /**
   * Indicates whether the signature request email should be sent.
   * @return sendEmail
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SEND_EMAIL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getSendEmail() {
    return sendEmail;
  }


  @JsonProperty(value = JSON_PROPERTY_SEND_EMAIL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSendEmail(@jakarta.annotation.Nullable Boolean sendEmail) {
    this.sendEmail = sendEmail;
  }


  public CreateSubmissionsFromEmailsResponseInnerPreferences sendSms(@jakarta.annotation.Nullable Boolean sendSms) {
    this.sendSms = sendSms;
    return this;
  }

  /**
   * Indicates whether the signature request should be sent via SMS.
   * @return sendSms
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SEND_SMS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getSendSms() {
    return sendSms;
  }


  @JsonProperty(value = JSON_PROPERTY_SEND_SMS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSendSms(@jakarta.annotation.Nullable Boolean sendSms) {
    this.sendSms = sendSms;
  }


  /**
   * Return true if this CreateSubmissionsFromEmailsResponse_inner_preferences object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateSubmissionsFromEmailsResponseInnerPreferences createSubmissionsFromEmailsResponseInnerPreferences = (CreateSubmissionsFromEmailsResponseInnerPreferences) o;
    return Objects.equals(this.sendEmail, createSubmissionsFromEmailsResponseInnerPreferences.sendEmail) &&
        Objects.equals(this.sendSms, createSubmissionsFromEmailsResponseInnerPreferences.sendSms);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sendEmail, sendSms);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateSubmissionsFromEmailsResponseInnerPreferences {\n");
    sb.append("    sendEmail: ").append(toIndentedString(sendEmail)).append("\n");
    sb.append("    sendSms: ").append(toIndentedString(sendSms)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

