/*
 * DocuSeal API
 * DocuSeal API specs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@docuseal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.docuseal.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.docuseal.models.CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferencesMask;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * Field display preferences.
 */
@JsonPropertyOrder({
  CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences.JSON_PROPERTY_FONT_SIZE,
  CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences.JSON_PROPERTY_FONT_TYPE,
  CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences.JSON_PROPERTY_FONT,
  CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences.JSON_PROPERTY_COLOR,
  CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences.JSON_PROPERTY_BACKGROUND,
  CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences.JSON_PROPERTY_ALIGN,
  CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences.JSON_PROPERTY_VALIGN,
  CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences.JSON_PROPERTY_FORMAT,
  CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences.JSON_PROPERTY_PRICE,
  CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences.JSON_PROPERTY_CURRENCY,
  CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences.JSON_PROPERTY_MASK,
  CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences.JSON_PROPERTY_REASONS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences {
  public static final String JSON_PROPERTY_FONT_SIZE = "font_size";
  @jakarta.annotation.Nullable
  private Integer fontSize;

  /**
   * Font type of the field value.
   */
  public enum FontTypeEnum {
    BOLD(String.valueOf("bold")),
    
    ITALIC(String.valueOf("italic")),
    
    BOLD_ITALIC(String.valueOf("bold_italic"));

    private String value;

    FontTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static FontTypeEnum fromValue(String value) {
      for (FontTypeEnum b : FontTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_FONT_TYPE = "font_type";
  @jakarta.annotation.Nullable
  private FontTypeEnum fontType;

  /**
   * Font family of the field value.
   */
  public enum FontEnum {
    TIMES(String.valueOf("Times")),
    
    HELVETICA(String.valueOf("Helvetica")),
    
    COURIER(String.valueOf("Courier"));

    private String value;

    FontEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static FontEnum fromValue(String value) {
      for (FontEnum b : FontEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_FONT = "font";
  @jakarta.annotation.Nullable
  private FontEnum font;

  /**
   * Font color of the field value.
   */
  public enum ColorEnum {
    BLACK(String.valueOf("black")),
    
    WHITE(String.valueOf("white")),
    
    BLUE(String.valueOf("blue"));

    private String value;

    ColorEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ColorEnum fromValue(String value) {
      for (ColorEnum b : ColorEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_COLOR = "color";
  @jakarta.annotation.Nullable
  private ColorEnum color = ColorEnum.BLACK;

  /**
   * Field box background color.
   */
  public enum BackgroundEnum {
    BLACK(String.valueOf("black")),
    
    WHITE(String.valueOf("white")),
    
    BLUE(String.valueOf("blue"));

    private String value;

    BackgroundEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static BackgroundEnum fromValue(String value) {
      for (BackgroundEnum b : BackgroundEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_BACKGROUND = "background";
  @jakarta.annotation.Nullable
  private BackgroundEnum background;

  /**
   * Horizontal alignment of the field text value.
   */
  public enum AlignEnum {
    LEFT(String.valueOf("left")),
    
    CENTER(String.valueOf("center")),
    
    RIGHT(String.valueOf("right"));

    private String value;

    AlignEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static AlignEnum fromValue(String value) {
      for (AlignEnum b : AlignEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ALIGN = "align";
  @jakarta.annotation.Nullable
  private AlignEnum align = AlignEnum.LEFT;

  /**
   * Vertical alignment of the field text value.
   */
  public enum ValignEnum {
    TOP(String.valueOf("top")),
    
    CENTER(String.valueOf("center")),
    
    BOTTOM(String.valueOf("bottom"));

    private String value;

    ValignEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ValignEnum fromValue(String value) {
      for (ValignEnum b : ValignEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_VALIGN = "valign";
  @jakarta.annotation.Nullable
  private ValignEnum valign = ValignEnum.CENTER;

  public static final String JSON_PROPERTY_FORMAT = "format";
  @jakarta.annotation.Nullable
  private String format;

  public static final String JSON_PROPERTY_PRICE = "price";
  @jakarta.annotation.Nullable
  private BigDecimal price;

  /**
   * Currency value of the payment field. Only for payment fields.
   */
  public enum CurrencyEnum {
    USD(String.valueOf("USD")),
    
    EUR(String.valueOf("EUR")),
    
    GBP(String.valueOf("GBP")),
    
    CAD(String.valueOf("CAD")),
    
    AUD(String.valueOf("AUD"));

    private String value;

    CurrencyEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static CurrencyEnum fromValue(String value) {
      for (CurrencyEnum b : CurrencyEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @jakarta.annotation.Nullable
  private CurrencyEnum currency = CurrencyEnum.USD;

  public static final String JSON_PROPERTY_MASK = "mask";
  @jakarta.annotation.Nullable
  private CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferencesMask mask;

  public static final String JSON_PROPERTY_REASONS = "reasons";
  @jakarta.annotation.Nullable
  private List<String> reasons = new ArrayList<>();

  public CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences() { 
  }

  public CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences fontSize(@jakarta.annotation.Nullable Integer fontSize) {
    this.fontSize = fontSize;
    return this;
  }

  /**
   * Font size of the field value in pixels.
   * @return fontSize
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FONT_SIZE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getFontSize() {
    return fontSize;
  }


  @JsonProperty(value = JSON_PROPERTY_FONT_SIZE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFontSize(@jakarta.annotation.Nullable Integer fontSize) {
    this.fontSize = fontSize;
  }


  public CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences fontType(@jakarta.annotation.Nullable FontTypeEnum fontType) {
    this.fontType = fontType;
    return this;
  }

  /**
   * Font type of the field value.
   * @return fontType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FONT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public FontTypeEnum getFontType() {
    return fontType;
  }


  @JsonProperty(value = JSON_PROPERTY_FONT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFontType(@jakarta.annotation.Nullable FontTypeEnum fontType) {
    this.fontType = fontType;
  }


  public CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences font(@jakarta.annotation.Nullable FontEnum font) {
    this.font = font;
    return this;
  }

  /**
   * Font family of the field value.
   * @return font
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FONT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public FontEnum getFont() {
    return font;
  }


  @JsonProperty(value = JSON_PROPERTY_FONT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFont(@jakarta.annotation.Nullable FontEnum font) {
    this.font = font;
  }


  public CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences color(@jakarta.annotation.Nullable ColorEnum color) {
    this.color = color;
    return this;
  }

  /**
   * Font color of the field value.
   * @return color
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COLOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ColorEnum getColor() {
    return color;
  }


  @JsonProperty(value = JSON_PROPERTY_COLOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setColor(@jakarta.annotation.Nullable ColorEnum color) {
    this.color = color;
  }


  public CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences background(@jakarta.annotation.Nullable BackgroundEnum background) {
    this.background = background;
    return this;
  }

  /**
   * Field box background color.
   * @return background
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BACKGROUND, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BackgroundEnum getBackground() {
    return background;
  }


  @JsonProperty(value = JSON_PROPERTY_BACKGROUND, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBackground(@jakarta.annotation.Nullable BackgroundEnum background) {
    this.background = background;
  }


  public CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences align(@jakarta.annotation.Nullable AlignEnum align) {
    this.align = align;
    return this;
  }

  /**
   * Horizontal alignment of the field text value.
   * @return align
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ALIGN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public AlignEnum getAlign() {
    return align;
  }


  @JsonProperty(value = JSON_PROPERTY_ALIGN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAlign(@jakarta.annotation.Nullable AlignEnum align) {
    this.align = align;
  }


  public CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences valign(@jakarta.annotation.Nullable ValignEnum valign) {
    this.valign = valign;
    return this;
  }

  /**
   * Vertical alignment of the field text value.
   * @return valign
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VALIGN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ValignEnum getValign() {
    return valign;
  }


  @JsonProperty(value = JSON_PROPERTY_VALIGN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValign(@jakarta.annotation.Nullable ValignEnum valign) {
    this.valign = valign;
  }


  public CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences format(@jakarta.annotation.Nullable String format) {
    this.format = format;
    return this;
  }

  /**
   * The data format for different field types.&lt;br&gt;- Date field: accepts formats such as DD/MM/YYYY (default: MM/DD/YYYY).&lt;br&gt;- Signature field: accepts drawn, typed, drawn_or_typed (default), or upload.&lt;br&gt;- Number field: accepts currency formats such as usd, eur, gbp.
   * @return format
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFormat() {
    return format;
  }


  @JsonProperty(value = JSON_PROPERTY_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFormat(@jakarta.annotation.Nullable String format) {
    this.format = format;
  }


  public CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences price(@jakarta.annotation.Nullable BigDecimal price) {
    this.price = price;
    return this;
  }

  /**
   * Price value of the payment field. Only for payment fields.
   * @return price
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getPrice() {
    return price;
  }


  @JsonProperty(value = JSON_PROPERTY_PRICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrice(@jakarta.annotation.Nullable BigDecimal price) {
    this.price = price;
  }


  public CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences currency(@jakarta.annotation.Nullable CurrencyEnum currency) {
    this.currency = currency;
    return this;
  }

  /**
   * Currency value of the payment field. Only for payment fields.
   * @return currency
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CurrencyEnum getCurrency() {
    return currency;
  }


  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurrency(@jakarta.annotation.Nullable CurrencyEnum currency) {
    this.currency = currency;
  }


  public CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences mask(@jakarta.annotation.Nullable CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferencesMask mask) {
    this.mask = mask;
    return this;
  }

  /**
   * Get mask
   * @return mask
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MASK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferencesMask getMask() {
    return mask;
  }


  @JsonProperty(value = JSON_PROPERTY_MASK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMask(@jakarta.annotation.Nullable CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferencesMask mask) {
    this.mask = mask;
  }


  public CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences reasons(@jakarta.annotation.Nullable List<String> reasons) {
    this.reasons = reasons;
    return this;
  }

  public CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences addReasonsItem(String reasonsItem) {
    if (this.reasons == null) {
      this.reasons = new ArrayList<>();
    }
    this.reasons.add(reasonsItem);
    return this;
  }

  /**
   * An array of signature reasons to choose from.
   * @return reasons
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REASONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getReasons() {
    return reasons;
  }


  @JsonProperty(value = JSON_PROPERTY_REASONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReasons(@jakarta.annotation.Nullable List<String> reasons) {
    this.reasons = reasons;
  }


  /**
   * Return true if this CreateSubmissionFromPdfRequest_submitters_inner_fields_inner_preferences object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences createSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences = (CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences) o;
    return Objects.equals(this.fontSize, createSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences.fontSize) &&
        Objects.equals(this.fontType, createSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences.fontType) &&
        Objects.equals(this.font, createSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences.font) &&
        Objects.equals(this.color, createSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences.color) &&
        Objects.equals(this.background, createSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences.background) &&
        Objects.equals(this.align, createSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences.align) &&
        Objects.equals(this.valign, createSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences.valign) &&
        Objects.equals(this.format, createSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences.format) &&
        Objects.equals(this.price, createSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences.price) &&
        Objects.equals(this.currency, createSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences.currency) &&
        Objects.equals(this.mask, createSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences.mask) &&
        Objects.equals(this.reasons, createSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences.reasons);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fontSize, fontType, font, color, background, align, valign, format, price, currency, mask, reasons);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferences {\n");
    sb.append("    fontSize: ").append(toIndentedString(fontSize)).append("\n");
    sb.append("    fontType: ").append(toIndentedString(fontType)).append("\n");
    sb.append("    font: ").append(toIndentedString(font)).append("\n");
    sb.append("    color: ").append(toIndentedString(color)).append("\n");
    sb.append("    background: ").append(toIndentedString(background)).append("\n");
    sb.append("    align: ").append(toIndentedString(align)).append("\n");
    sb.append("    valign: ").append(toIndentedString(valign)).append("\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    mask: ").append(toIndentedString(mask)).append("\n");
    sb.append("    reasons: ").append(toIndentedString(reasons)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

