/*
 * DocuSeal API
 * DocuSeal API specs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@docuseal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.docuseal.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import com.fasterxml.jackson.core.type.TypeReference;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import com.docuseal.JSON;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
@JsonDeserialize(using = CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferencesMask.CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferencesMaskDeserializer.class)
@JsonSerialize(using = CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferencesMask.CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferencesMaskSerializer.class)
public class CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferencesMask extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferencesMask.class.getName());

    public static class CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferencesMaskSerializer extends StdSerializer<CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferencesMask> {
        public CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferencesMaskSerializer(Class<CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferencesMask> t) {
            super(t);
        }

        public CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferencesMaskSerializer() {
            this(null);
        }

        @Override
        public void serialize(CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferencesMask value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferencesMaskDeserializer extends StdDeserializer<CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferencesMask> {
        public CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferencesMaskDeserializer() {
            this(CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferencesMask.class);
        }

        public CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferencesMaskDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferencesMask deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = ctxt.readTree(jp);
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize Boolean
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (Boolean.class.equals(Integer.class) || Boolean.class.equals(Long.class) || Boolean.class.equals(Float.class) || Boolean.class.equals(Double.class) || Boolean.class.equals(Boolean.class) || Boolean.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((Boolean.class.equals(Integer.class) || Boolean.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((Boolean.class.equals(Float.class) || Boolean.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (Boolean.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (Boolean.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(Boolean.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'Boolean'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'Boolean'", e);
            }

            // deserialize Integer
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (Integer.class.equals(Integer.class) || Integer.class.equals(Long.class) || Integer.class.equals(Float.class) || Integer.class.equals(Double.class) || Integer.class.equals(Boolean.class) || Integer.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((Integer.class.equals(Integer.class) || Integer.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((Integer.class.equals(Float.class) || Integer.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (Integer.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (Integer.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(Integer.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'Integer'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'Integer'", e);
            }

            if (match == 1) {
                CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferencesMask ret = new CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferencesMask();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format(java.util.Locale.ROOT, "Failed deserialization for CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferencesMask: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferencesMask getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferencesMask cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<>();

    public CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferencesMask() {
        super("oneOf", Boolean.FALSE);
    }

    public CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferencesMask(Boolean o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferencesMask(Integer o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("Boolean", Boolean.class);
        schemas.put("Integer", Integer.class);
        JSON.registerDescendants(CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferencesMask.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return CreateSubmissionFromPdfRequestSubmittersInnerFieldsInnerPreferencesMask.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * Boolean, Integer
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(Boolean.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(Integer.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be Boolean, Integer");
    }

    /**
     * Get the actual instance, which can be the following:
     * Boolean, Integer
     *
     * @return The actual instance (Boolean, Integer)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `Boolean`. If the actual instance is not `Boolean`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `Boolean`
     * @throws ClassCastException if the instance is not `Boolean`
     */
    public Boolean getBoolean() throws ClassCastException {
        return (Boolean)super.getActualInstance();
    }

    /**
     * Get the actual instance of `Integer`. If the actual instance is not `Integer`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `Integer`
     * @throws ClassCastException if the instance is not `Integer`
     */
    public Integer getInteger() throws ClassCastException {
        return (Integer)super.getActualInstance();
    }




}

