/*
 * DocuSeal API
 * DocuSeal API specs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@docuseal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.docuseal.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.docuseal.models.GetSubmittersResponseDataInner;
import com.docuseal.models.SubmitterPagination;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * GetSubmittersResponse
 */
@JsonPropertyOrder({
  GetSubmittersResponse.JSON_PROPERTY_DATA,
  GetSubmittersResponse.JSON_PROPERTY_PAGINATION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class GetSubmittersResponse {
  public static final String JSON_PROPERTY_DATA = "data";
  @jakarta.annotation.Nullable
  private List<GetSubmittersResponseDataInner> data = new ArrayList<>();

  public static final String JSON_PROPERTY_PAGINATION = "pagination";
  @jakarta.annotation.Nullable
  private SubmitterPagination pagination;

  public GetSubmittersResponse() { 
  }

  public GetSubmittersResponse data(@jakarta.annotation.Nullable List<GetSubmittersResponseDataInner> data) {
    this.data = data;
    return this;
  }

  public GetSubmittersResponse addDataItem(GetSubmittersResponseDataInner dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<>();
    }
    this.data.add(dataItem);
    return this;
  }

  /**
   * Get data
   * @return data
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<GetSubmittersResponseDataInner> getData() {
    return data;
  }


  @JsonProperty(value = JSON_PROPERTY_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setData(@jakarta.annotation.Nullable List<GetSubmittersResponseDataInner> data) {
    this.data = data;
  }


  public GetSubmittersResponse pagination(@jakarta.annotation.Nullable SubmitterPagination pagination) {
    this.pagination = pagination;
    return this;
  }

  /**
   * Get pagination
   * @return pagination
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PAGINATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public SubmitterPagination getPagination() {
    return pagination;
  }


  @JsonProperty(value = JSON_PROPERTY_PAGINATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPagination(@jakarta.annotation.Nullable SubmitterPagination pagination) {
    this.pagination = pagination;
  }


  /**
   * Return true if this GetSubmittersResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetSubmittersResponse getSubmittersResponse = (GetSubmittersResponse) o;
    return Objects.equals(this.data, getSubmittersResponse.data) &&
        Objects.equals(this.pagination, getSubmittersResponse.pagination);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, pagination);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetSubmittersResponse {\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    pagination: ").append(toIndentedString(pagination)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

