/*
 * DocuSeal API
 * DocuSeal API specs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@docuseal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.docuseal.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.docuseal.models.TemplateAuthor;
import com.docuseal.models.TemplateDocument;
import com.docuseal.models.TemplateField;
import com.docuseal.models.TemplateSchemaDocument;
import com.docuseal.models.TemplateSubmitter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * GetTemplateResponse
 */
@JsonPropertyOrder({
  GetTemplateResponse.JSON_PROPERTY_ID,
  GetTemplateResponse.JSON_PROPERTY_SLUG,
  GetTemplateResponse.JSON_PROPERTY_NAME,
  GetTemplateResponse.JSON_PROPERTY_PREFERENCES,
  GetTemplateResponse.JSON_PROPERTY_SCHEMA,
  GetTemplateResponse.JSON_PROPERTY_FIELDS,
  GetTemplateResponse.JSON_PROPERTY_SUBMITTERS,
  GetTemplateResponse.JSON_PROPERTY_AUTHOR_ID,
  GetTemplateResponse.JSON_PROPERTY_ARCHIVED_AT,
  GetTemplateResponse.JSON_PROPERTY_CREATED_AT,
  GetTemplateResponse.JSON_PROPERTY_UPDATED_AT,
  GetTemplateResponse.JSON_PROPERTY_SOURCE,
  GetTemplateResponse.JSON_PROPERTY_EXTERNAL_ID,
  GetTemplateResponse.JSON_PROPERTY_FOLDER_ID,
  GetTemplateResponse.JSON_PROPERTY_FOLDER_NAME,
  GetTemplateResponse.JSON_PROPERTY_SHARED_LINK,
  GetTemplateResponse.JSON_PROPERTY_AUTHOR,
  GetTemplateResponse.JSON_PROPERTY_DOCUMENTS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class GetTemplateResponse {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private Integer id;

  public static final String JSON_PROPERTY_SLUG = "slug";
  @jakarta.annotation.Nonnull
  private String slug;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_PREFERENCES = "preferences";
  @jakarta.annotation.Nonnull
  private Object preferences;

  public static final String JSON_PROPERTY_SCHEMA = "schema";
  @jakarta.annotation.Nonnull
  private List<TemplateSchemaDocument> schema = new ArrayList<>();

  public static final String JSON_PROPERTY_FIELDS = "fields";
  @jakarta.annotation.Nonnull
  private List<TemplateField> fields = new ArrayList<>();

  public static final String JSON_PROPERTY_SUBMITTERS = "submitters";
  @jakarta.annotation.Nonnull
  private List<TemplateSubmitter> submitters = new ArrayList<>();

  public static final String JSON_PROPERTY_AUTHOR_ID = "author_id";
  @jakarta.annotation.Nonnull
  private Integer authorId;

  public static final String JSON_PROPERTY_ARCHIVED_AT = "archived_at";
  @jakarta.annotation.Nullable
  private String archivedAt;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  @jakarta.annotation.Nonnull
  private String createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updated_at";
  @jakarta.annotation.Nonnull
  private String updatedAt;

  /**
   * Source of the template.
   */
  public enum SourceEnum {
    NATIVE(String.valueOf("native")),
    
    API(String.valueOf("api")),
    
    EMBED(String.valueOf("embed"));

    private String value;

    SourceEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SourceEnum fromValue(String value) {
      for (SourceEnum b : SourceEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SOURCE = "source";
  @jakarta.annotation.Nonnull
  private SourceEnum source;

  public static final String JSON_PROPERTY_EXTERNAL_ID = "external_id";
  @jakarta.annotation.Nullable
  private String externalId;

  public static final String JSON_PROPERTY_FOLDER_ID = "folder_id";
  @jakarta.annotation.Nonnull
  private Integer folderId;

  public static final String JSON_PROPERTY_FOLDER_NAME = "folder_name";
  @jakarta.annotation.Nonnull
  private String folderName;

  public static final String JSON_PROPERTY_SHARED_LINK = "shared_link";
  @jakarta.annotation.Nullable
  private Boolean sharedLink;

  public static final String JSON_PROPERTY_AUTHOR = "author";
  @jakarta.annotation.Nonnull
  private TemplateAuthor author;

  public static final String JSON_PROPERTY_DOCUMENTS = "documents";
  @jakarta.annotation.Nonnull
  private List<TemplateDocument> documents = new ArrayList<>();

  public GetTemplateResponse() { 
  }

  public GetTemplateResponse id(@jakarta.annotation.Nonnull Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Unique identifier of the document template.
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull Integer id) {
    this.id = id;
  }


  public GetTemplateResponse slug(@jakarta.annotation.Nonnull String slug) {
    this.slug = slug;
    return this;
  }

  /**
   * Unique slug of the document template.
   * @return slug
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SLUG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSlug() {
    return slug;
  }


  @JsonProperty(value = JSON_PROPERTY_SLUG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSlug(@jakarta.annotation.Nonnull String slug) {
    this.slug = slug;
  }


  public GetTemplateResponse name(@jakarta.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * The name of the template.
   * @return name
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nonnull String name) {
    this.name = name;
  }


  public GetTemplateResponse preferences(@jakarta.annotation.Nonnull Object preferences) {
    this.preferences = preferences;
    return this;
  }

  /**
   * Template preferences.
   * @return preferences
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PREFERENCES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Object getPreferences() {
    return preferences;
  }


  @JsonProperty(value = JSON_PROPERTY_PREFERENCES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPreferences(@jakarta.annotation.Nonnull Object preferences) {
    this.preferences = preferences;
  }


  public GetTemplateResponse schema(@jakarta.annotation.Nonnull List<TemplateSchemaDocument> schema) {
    this.schema = schema;
    return this;
  }

  public GetTemplateResponse addSchemaItem(TemplateSchemaDocument schemaItem) {
    if (this.schema == null) {
      this.schema = new ArrayList<>();
    }
    this.schema.add(schemaItem);
    return this;
  }

  /**
   * List of documents attached to the template.
   * @return schema
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SCHEMA, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<TemplateSchemaDocument> getSchema() {
    return schema;
  }


  @JsonProperty(value = JSON_PROPERTY_SCHEMA, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSchema(@jakarta.annotation.Nonnull List<TemplateSchemaDocument> schema) {
    this.schema = schema;
  }


  public GetTemplateResponse fields(@jakarta.annotation.Nonnull List<TemplateField> fields) {
    this.fields = fields;
    return this;
  }

  public GetTemplateResponse addFieldsItem(TemplateField fieldsItem) {
    if (this.fields == null) {
      this.fields = new ArrayList<>();
    }
    this.fields.add(fieldsItem);
    return this;
  }

  /**
   * List of fields to be filled in the template.
   * @return fields
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FIELDS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<TemplateField> getFields() {
    return fields;
  }


  @JsonProperty(value = JSON_PROPERTY_FIELDS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFields(@jakarta.annotation.Nonnull List<TemplateField> fields) {
    this.fields = fields;
  }


  public GetTemplateResponse submitters(@jakarta.annotation.Nonnull List<TemplateSubmitter> submitters) {
    this.submitters = submitters;
    return this;
  }

  public GetTemplateResponse addSubmittersItem(TemplateSubmitter submittersItem) {
    if (this.submitters == null) {
      this.submitters = new ArrayList<>();
    }
    this.submitters.add(submittersItem);
    return this;
  }

  /**
   * The list of submitters for the template.
   * @return submitters
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SUBMITTERS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<TemplateSubmitter> getSubmitters() {
    return submitters;
  }


  @JsonProperty(value = JSON_PROPERTY_SUBMITTERS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSubmitters(@jakarta.annotation.Nonnull List<TemplateSubmitter> submitters) {
    this.submitters = submitters;
  }


  public GetTemplateResponse authorId(@jakarta.annotation.Nonnull Integer authorId) {
    this.authorId = authorId;
    return this;
  }

  /**
   * Unique identifier of the author of the template.
   * @return authorId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AUTHOR_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getAuthorId() {
    return authorId;
  }


  @JsonProperty(value = JSON_PROPERTY_AUTHOR_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAuthorId(@jakarta.annotation.Nonnull Integer authorId) {
    this.authorId = authorId;
  }


  public GetTemplateResponse archivedAt(@jakarta.annotation.Nullable String archivedAt) {
    this.archivedAt = archivedAt;
    return this;
  }

  /**
   * Date and time when the template was archived.
   * @return archivedAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ARCHIVED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getArchivedAt() {
    return archivedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_ARCHIVED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setArchivedAt(@jakarta.annotation.Nullable String archivedAt) {
    this.archivedAt = archivedAt;
  }


  public GetTemplateResponse createdAt(@jakarta.annotation.Nonnull String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * The date and time when the template was created.
   * @return createdAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@jakarta.annotation.Nonnull String createdAt) {
    this.createdAt = createdAt;
  }


  public GetTemplateResponse updatedAt(@jakarta.annotation.Nonnull String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * The date and time when the template was last updated.
   * @return updatedAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUpdatedAt(@jakarta.annotation.Nonnull String updatedAt) {
    this.updatedAt = updatedAt;
  }


  public GetTemplateResponse source(@jakarta.annotation.Nonnull SourceEnum source) {
    this.source = source;
    return this;
  }

  /**
   * Source of the template.
   * @return source
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SOURCE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public SourceEnum getSource() {
    return source;
  }


  @JsonProperty(value = JSON_PROPERTY_SOURCE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSource(@jakarta.annotation.Nonnull SourceEnum source) {
    this.source = source;
  }


  public GetTemplateResponse externalId(@jakarta.annotation.Nullable String externalId) {
    this.externalId = externalId;
    return this;
  }

  /**
   * Your application-specific unique string key to identify this template within your app.
   * @return externalId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXTERNAL_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getExternalId() {
    return externalId;
  }


  @JsonProperty(value = JSON_PROPERTY_EXTERNAL_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExternalId(@jakarta.annotation.Nullable String externalId) {
    this.externalId = externalId;
  }


  public GetTemplateResponse folderId(@jakarta.annotation.Nonnull Integer folderId) {
    this.folderId = folderId;
    return this;
  }

  /**
   * Unique identifier of the folder where the template is located.
   * @return folderId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FOLDER_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getFolderId() {
    return folderId;
  }


  @JsonProperty(value = JSON_PROPERTY_FOLDER_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFolderId(@jakarta.annotation.Nonnull Integer folderId) {
    this.folderId = folderId;
  }


  public GetTemplateResponse folderName(@jakarta.annotation.Nonnull String folderName) {
    this.folderName = folderName;
    return this;
  }

  /**
   * Folder name where the template is located.
   * @return folderName
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FOLDER_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getFolderName() {
    return folderName;
  }


  @JsonProperty(value = JSON_PROPERTY_FOLDER_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFolderName(@jakarta.annotation.Nonnull String folderName) {
    this.folderName = folderName;
  }


  public GetTemplateResponse sharedLink(@jakarta.annotation.Nullable Boolean sharedLink) {
    this.sharedLink = sharedLink;
    return this;
  }

  /**
   * Indicates if the template is accessible by link.
   * @return sharedLink
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SHARED_LINK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getSharedLink() {
    return sharedLink;
  }


  @JsonProperty(value = JSON_PROPERTY_SHARED_LINK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSharedLink(@jakarta.annotation.Nullable Boolean sharedLink) {
    this.sharedLink = sharedLink;
  }


  public GetTemplateResponse author(@jakarta.annotation.Nonnull TemplateAuthor author) {
    this.author = author;
    return this;
  }

  /**
   * Get author
   * @return author
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AUTHOR, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public TemplateAuthor getAuthor() {
    return author;
  }


  @JsonProperty(value = JSON_PROPERTY_AUTHOR, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAuthor(@jakarta.annotation.Nonnull TemplateAuthor author) {
    this.author = author;
  }


  public GetTemplateResponse documents(@jakarta.annotation.Nonnull List<TemplateDocument> documents) {
    this.documents = documents;
    return this;
  }

  public GetTemplateResponse addDocumentsItem(TemplateDocument documentsItem) {
    if (this.documents == null) {
      this.documents = new ArrayList<>();
    }
    this.documents.add(documentsItem);
    return this;
  }

  /**
   * List of documents attached to the template.
   * @return documents
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DOCUMENTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<TemplateDocument> getDocuments() {
    return documents;
  }


  @JsonProperty(value = JSON_PROPERTY_DOCUMENTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDocuments(@jakarta.annotation.Nonnull List<TemplateDocument> documents) {
    this.documents = documents;
  }


  /**
   * Return true if this GetTemplateResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetTemplateResponse getTemplateResponse = (GetTemplateResponse) o;
    return Objects.equals(this.id, getTemplateResponse.id) &&
        Objects.equals(this.slug, getTemplateResponse.slug) &&
        Objects.equals(this.name, getTemplateResponse.name) &&
        Objects.equals(this.preferences, getTemplateResponse.preferences) &&
        Objects.equals(this.schema, getTemplateResponse.schema) &&
        Objects.equals(this.fields, getTemplateResponse.fields) &&
        Objects.equals(this.submitters, getTemplateResponse.submitters) &&
        Objects.equals(this.authorId, getTemplateResponse.authorId) &&
        Objects.equals(this.archivedAt, getTemplateResponse.archivedAt) &&
        Objects.equals(this.createdAt, getTemplateResponse.createdAt) &&
        Objects.equals(this.updatedAt, getTemplateResponse.updatedAt) &&
        Objects.equals(this.source, getTemplateResponse.source) &&
        Objects.equals(this.externalId, getTemplateResponse.externalId) &&
        Objects.equals(this.folderId, getTemplateResponse.folderId) &&
        Objects.equals(this.folderName, getTemplateResponse.folderName) &&
        Objects.equals(this.sharedLink, getTemplateResponse.sharedLink) &&
        Objects.equals(this.author, getTemplateResponse.author) &&
        Objects.equals(this.documents, getTemplateResponse.documents);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, slug, name, preferences, schema, fields, submitters, authorId, archivedAt, createdAt, updatedAt, source, externalId, folderId, folderName, sharedLink, author, documents);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetTemplateResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    preferences: ").append(toIndentedString(preferences)).append("\n");
    sb.append("    schema: ").append(toIndentedString(schema)).append("\n");
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("    submitters: ").append(toIndentedString(submitters)).append("\n");
    sb.append("    authorId: ").append(toIndentedString(authorId)).append("\n");
    sb.append("    archivedAt: ").append(toIndentedString(archivedAt)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    folderId: ").append(toIndentedString(folderId)).append("\n");
    sb.append("    folderName: ").append(toIndentedString(folderName)).append("\n");
    sb.append("    sharedLink: ").append(toIndentedString(sharedLink)).append("\n");
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    documents: ").append(toIndentedString(documents)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

