/*
 * DocuSeal API
 * DocuSeal API specs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@docuseal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.docuseal.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * SubmitterPagination
 */
@JsonPropertyOrder({
  SubmitterPagination.JSON_PROPERTY_COUNT,
  SubmitterPagination.JSON_PROPERTY_NEXT,
  SubmitterPagination.JSON_PROPERTY_PREV
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class SubmitterPagination {
  public static final String JSON_PROPERTY_COUNT = "count";
  @jakarta.annotation.Nonnull
  private Integer count;

  public static final String JSON_PROPERTY_NEXT = "next";
  @jakarta.annotation.Nullable
  private Integer next;

  public static final String JSON_PROPERTY_PREV = "prev";
  @jakarta.annotation.Nullable
  private Integer prev;

  public SubmitterPagination() { 
  }

  public SubmitterPagination count(@jakarta.annotation.Nonnull Integer count) {
    this.count = count;
    return this;
  }

  /**
   * Submitters count.
   * @return count
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_COUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getCount() {
    return count;
  }


  @JsonProperty(value = JSON_PROPERTY_COUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCount(@jakarta.annotation.Nonnull Integer count) {
    this.count = count;
  }


  public SubmitterPagination next(@jakarta.annotation.Nullable Integer next) {
    this.next = next;
    return this;
  }

  /**
   * The ID of the submitter after which the next page starts.
   * @return next
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getNext() {
    return next;
  }


  @JsonProperty(value = JSON_PROPERTY_NEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNext(@jakarta.annotation.Nullable Integer next) {
    this.next = next;
  }


  public SubmitterPagination prev(@jakarta.annotation.Nullable Integer prev) {
    this.prev = prev;
    return this;
  }

  /**
   * The ID of the submitter before which the previous page ends.
   * @return prev
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PREV, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getPrev() {
    return prev;
  }


  @JsonProperty(value = JSON_PROPERTY_PREV, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPrev(@jakarta.annotation.Nullable Integer prev) {
    this.prev = prev;
  }


  /**
   * Return true if this SubmitterPagination object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubmitterPagination submitterPagination = (SubmitterPagination) o;
    return Objects.equals(this.count, submitterPagination.count) &&
        Objects.equals(this.next, submitterPagination.next) &&
        Objects.equals(this.prev, submitterPagination.prev);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, next, prev);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubmitterPagination {\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    next: ").append(toIndentedString(next)).append("\n");
    sb.append("    prev: ").append(toIndentedString(prev)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

