/*
 * DocuSeal API
 * DocuSeal API specs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@docuseal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.docuseal.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * Field display preferences.
 */
@JsonPropertyOrder({
  TemplateFieldPreferences.JSON_PROPERTY_FONT_SIZE,
  TemplateFieldPreferences.JSON_PROPERTY_FONT_TYPE,
  TemplateFieldPreferences.JSON_PROPERTY_FONT,
  TemplateFieldPreferences.JSON_PROPERTY_COLOR,
  TemplateFieldPreferences.JSON_PROPERTY_BACKGROUND,
  TemplateFieldPreferences.JSON_PROPERTY_ALIGN,
  TemplateFieldPreferences.JSON_PROPERTY_VALIGN,
  TemplateFieldPreferences.JSON_PROPERTY_FORMAT,
  TemplateFieldPreferences.JSON_PROPERTY_PRICE,
  TemplateFieldPreferences.JSON_PROPERTY_CURRENCY,
  TemplateFieldPreferences.JSON_PROPERTY_MASK,
  TemplateFieldPreferences.JSON_PROPERTY_REASONS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class TemplateFieldPreferences {
  public static final String JSON_PROPERTY_FONT_SIZE = "font_size";
  @jakarta.annotation.Nullable
  private Integer fontSize;

  public static final String JSON_PROPERTY_FONT_TYPE = "font_type";
  @jakarta.annotation.Nullable
  private String fontType;

  public static final String JSON_PROPERTY_FONT = "font";
  @jakarta.annotation.Nullable
  private String font;

  public static final String JSON_PROPERTY_COLOR = "color";
  @jakarta.annotation.Nullable
  private String color;

  public static final String JSON_PROPERTY_BACKGROUND = "background";
  @jakarta.annotation.Nullable
  private String background;

  public static final String JSON_PROPERTY_ALIGN = "align";
  @jakarta.annotation.Nullable
  private String align;

  public static final String JSON_PROPERTY_VALIGN = "valign";
  @jakarta.annotation.Nullable
  private String valign;

  public static final String JSON_PROPERTY_FORMAT = "format";
  @jakarta.annotation.Nullable
  private String format;

  public static final String JSON_PROPERTY_PRICE = "price";
  @jakarta.annotation.Nullable
  private BigDecimal price;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @jakarta.annotation.Nullable
  private String currency;

  public static final String JSON_PROPERTY_MASK = "mask";
  @jakarta.annotation.Nullable
  private Boolean mask;

  public static final String JSON_PROPERTY_REASONS = "reasons";
  @jakarta.annotation.Nullable
  private List<String> reasons = new ArrayList<>();

  public TemplateFieldPreferences() { 
  }

  public TemplateFieldPreferences fontSize(@jakarta.annotation.Nullable Integer fontSize) {
    this.fontSize = fontSize;
    return this;
  }

  /**
   * Font size of the field value in pixels.
   * @return fontSize
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FONT_SIZE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getFontSize() {
    return fontSize;
  }


  @JsonProperty(value = JSON_PROPERTY_FONT_SIZE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFontSize(@jakarta.annotation.Nullable Integer fontSize) {
    this.fontSize = fontSize;
  }


  public TemplateFieldPreferences fontType(@jakarta.annotation.Nullable String fontType) {
    this.fontType = fontType;
    return this;
  }

  /**
   * Font type of the field value.
   * @return fontType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FONT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFontType() {
    return fontType;
  }


  @JsonProperty(value = JSON_PROPERTY_FONT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFontType(@jakarta.annotation.Nullable String fontType) {
    this.fontType = fontType;
  }


  public TemplateFieldPreferences font(@jakarta.annotation.Nullable String font) {
    this.font = font;
    return this;
  }

  /**
   * Font family of the field value.
   * @return font
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FONT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFont() {
    return font;
  }


  @JsonProperty(value = JSON_PROPERTY_FONT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFont(@jakarta.annotation.Nullable String font) {
    this.font = font;
  }


  public TemplateFieldPreferences color(@jakarta.annotation.Nullable String color) {
    this.color = color;
    return this;
  }

  /**
   * Font color of the field value.
   * @return color
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COLOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getColor() {
    return color;
  }


  @JsonProperty(value = JSON_PROPERTY_COLOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setColor(@jakarta.annotation.Nullable String color) {
    this.color = color;
  }


  public TemplateFieldPreferences background(@jakarta.annotation.Nullable String background) {
    this.background = background;
    return this;
  }

  /**
   * Field box background color.
   * @return background
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BACKGROUND, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getBackground() {
    return background;
  }


  @JsonProperty(value = JSON_PROPERTY_BACKGROUND, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBackground(@jakarta.annotation.Nullable String background) {
    this.background = background;
  }


  public TemplateFieldPreferences align(@jakarta.annotation.Nullable String align) {
    this.align = align;
    return this;
  }

  /**
   * Horizontal alignment of the field text value.
   * @return align
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ALIGN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getAlign() {
    return align;
  }


  @JsonProperty(value = JSON_PROPERTY_ALIGN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAlign(@jakarta.annotation.Nullable String align) {
    this.align = align;
  }


  public TemplateFieldPreferences valign(@jakarta.annotation.Nullable String valign) {
    this.valign = valign;
    return this;
  }

  /**
   * Vertical alignment of the field text value.
   * @return valign
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VALIGN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getValign() {
    return valign;
  }


  @JsonProperty(value = JSON_PROPERTY_VALIGN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValign(@jakarta.annotation.Nullable String valign) {
    this.valign = valign;
  }


  public TemplateFieldPreferences format(@jakarta.annotation.Nullable String format) {
    this.format = format;
    return this;
  }

  /**
   * The data format for different field types.
   * @return format
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFormat() {
    return format;
  }


  @JsonProperty(value = JSON_PROPERTY_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFormat(@jakarta.annotation.Nullable String format) {
    this.format = format;
  }


  public TemplateFieldPreferences price(@jakarta.annotation.Nullable BigDecimal price) {
    this.price = price;
    return this;
  }

  /**
   * Price value of the payment field. Only for payment fields.
   * @return price
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getPrice() {
    return price;
  }


  @JsonProperty(value = JSON_PROPERTY_PRICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrice(@jakarta.annotation.Nullable BigDecimal price) {
    this.price = price;
  }


  public TemplateFieldPreferences currency(@jakarta.annotation.Nullable String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * Currency value of the payment field. Only for payment fields.
   * @return currency
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCurrency() {
    return currency;
  }


  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurrency(@jakarta.annotation.Nullable String currency) {
    this.currency = currency;
  }


  public TemplateFieldPreferences mask(@jakarta.annotation.Nullable Boolean mask) {
    this.mask = mask;
    return this;
  }

  /**
   * Indicates if the field is masked on the document.
   * @return mask
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MASK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getMask() {
    return mask;
  }


  @JsonProperty(value = JSON_PROPERTY_MASK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMask(@jakarta.annotation.Nullable Boolean mask) {
    this.mask = mask;
  }


  public TemplateFieldPreferences reasons(@jakarta.annotation.Nullable List<String> reasons) {
    this.reasons = reasons;
    return this;
  }

  public TemplateFieldPreferences addReasonsItem(String reasonsItem) {
    if (this.reasons == null) {
      this.reasons = new ArrayList<>();
    }
    this.reasons.add(reasonsItem);
    return this;
  }

  /**
   * An array of signature reasons to choose from.
   * @return reasons
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REASONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getReasons() {
    return reasons;
  }


  @JsonProperty(value = JSON_PROPERTY_REASONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReasons(@jakarta.annotation.Nullable List<String> reasons) {
    this.reasons = reasons;
  }


  /**
   * Return true if this TemplateFieldPreferences object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TemplateFieldPreferences templateFieldPreferences = (TemplateFieldPreferences) o;
    return Objects.equals(this.fontSize, templateFieldPreferences.fontSize) &&
        Objects.equals(this.fontType, templateFieldPreferences.fontType) &&
        Objects.equals(this.font, templateFieldPreferences.font) &&
        Objects.equals(this.color, templateFieldPreferences.color) &&
        Objects.equals(this.background, templateFieldPreferences.background) &&
        Objects.equals(this.align, templateFieldPreferences.align) &&
        Objects.equals(this.valign, templateFieldPreferences.valign) &&
        Objects.equals(this.format, templateFieldPreferences.format) &&
        Objects.equals(this.price, templateFieldPreferences.price) &&
        Objects.equals(this.currency, templateFieldPreferences.currency) &&
        Objects.equals(this.mask, templateFieldPreferences.mask) &&
        Objects.equals(this.reasons, templateFieldPreferences.reasons);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fontSize, fontType, font, color, background, align, valign, format, price, currency, mask, reasons);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TemplateFieldPreferences {\n");
    sb.append("    fontSize: ").append(toIndentedString(fontSize)).append("\n");
    sb.append("    fontType: ").append(toIndentedString(fontType)).append("\n");
    sb.append("    font: ").append(toIndentedString(font)).append("\n");
    sb.append("    color: ").append(toIndentedString(color)).append("\n");
    sb.append("    background: ").append(toIndentedString(background)).append("\n");
    sb.append("    align: ").append(toIndentedString(align)).append("\n");
    sb.append("    valign: ").append(toIndentedString(valign)).append("\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    mask: ").append(toIndentedString(mask)).append("\n");
    sb.append("    reasons: ").append(toIndentedString(reasons)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

