/*
 * DocuSeal API
 * DocuSeal API specs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@docuseal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.docuseal.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.docuseal.models.TemplateFieldArea;
import com.docuseal.models.TemplateFieldPreferences;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * TemplateField
 */
@JsonPropertyOrder({
  TemplateField.JSON_PROPERTY_UUID,
  TemplateField.JSON_PROPERTY_SUBMITTER_UUID,
  TemplateField.JSON_PROPERTY_NAME,
  TemplateField.JSON_PROPERTY_TYPE,
  TemplateField.JSON_PROPERTY_REQUIRED,
  TemplateField.JSON_PROPERTY_PREFERENCES,
  TemplateField.JSON_PROPERTY_AREAS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class TemplateField {
  public static final String JSON_PROPERTY_UUID = "uuid";
  @jakarta.annotation.Nonnull
  private String uuid;

  public static final String JSON_PROPERTY_SUBMITTER_UUID = "submitter_uuid";
  @jakarta.annotation.Nonnull
  private String submitterUuid;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nonnull
  private String name;

  /**
   * Type of the field (e.g., text, signature, date, initials).
   */
  public enum TypeEnum {
    HEADING(String.valueOf("heading")),
    
    TEXT(String.valueOf("text")),
    
    SIGNATURE(String.valueOf("signature")),
    
    INITIALS(String.valueOf("initials")),
    
    DATE(String.valueOf("date")),
    
    NUMBER(String.valueOf("number")),
    
    IMAGE(String.valueOf("image")),
    
    CHECKBOX(String.valueOf("checkbox")),
    
    MULTIPLE(String.valueOf("multiple")),
    
    FILE(String.valueOf("file")),
    
    RADIO(String.valueOf("radio")),
    
    SELECT(String.valueOf("select")),
    
    CELLS(String.valueOf("cells")),
    
    STAMP(String.valueOf("stamp")),
    
    PAYMENT(String.valueOf("payment")),
    
    PHONE(String.valueOf("phone")),
    
    VERIFICATION(String.valueOf("verification")),
    
    KBA(String.valueOf("kba")),
    
    STRIKETHROUGH(String.valueOf("strikethrough"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private TypeEnum type;

  public static final String JSON_PROPERTY_REQUIRED = "required";
  @jakarta.annotation.Nonnull
  private Boolean required;

  public static final String JSON_PROPERTY_PREFERENCES = "preferences";
  @jakarta.annotation.Nullable
  private TemplateFieldPreferences preferences;

  public static final String JSON_PROPERTY_AREAS = "areas";
  @jakarta.annotation.Nonnull
  private List<TemplateFieldArea> areas = new ArrayList<>();

  public TemplateField() { 
  }

  public TemplateField uuid(@jakarta.annotation.Nonnull String uuid) {
    this.uuid = uuid;
    return this;
  }

  /**
   * Unique identifier of the field.
   * @return uuid
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_UUID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getUuid() {
    return uuid;
  }


  @JsonProperty(value = JSON_PROPERTY_UUID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUuid(@jakarta.annotation.Nonnull String uuid) {
    this.uuid = uuid;
  }


  public TemplateField submitterUuid(@jakarta.annotation.Nonnull String submitterUuid) {
    this.submitterUuid = submitterUuid;
    return this;
  }

  /**
   * Unique identifier of the submitter that filled the field.
   * @return submitterUuid
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SUBMITTER_UUID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSubmitterUuid() {
    return submitterUuid;
  }


  @JsonProperty(value = JSON_PROPERTY_SUBMITTER_UUID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSubmitterUuid(@jakarta.annotation.Nonnull String submitterUuid) {
    this.submitterUuid = submitterUuid;
  }


  public TemplateField name(@jakarta.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Field name.
   * @return name
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nonnull String name) {
    this.name = name;
  }


  public TemplateField type(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * Type of the field (e.g., text, signature, date, initials).
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }


  public TemplateField required(@jakarta.annotation.Nonnull Boolean required) {
    this.required = required;
    return this;
  }

  /**
   * Indicates if the field is required.
   * @return required
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_REQUIRED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getRequired() {
    return required;
  }


  @JsonProperty(value = JSON_PROPERTY_REQUIRED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRequired(@jakarta.annotation.Nonnull Boolean required) {
    this.required = required;
  }


  public TemplateField preferences(@jakarta.annotation.Nullable TemplateFieldPreferences preferences) {
    this.preferences = preferences;
    return this;
  }

  /**
   * Get preferences
   * @return preferences
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PREFERENCES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public TemplateFieldPreferences getPreferences() {
    return preferences;
  }


  @JsonProperty(value = JSON_PROPERTY_PREFERENCES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPreferences(@jakarta.annotation.Nullable TemplateFieldPreferences preferences) {
    this.preferences = preferences;
  }


  public TemplateField areas(@jakarta.annotation.Nonnull List<TemplateFieldArea> areas) {
    this.areas = areas;
    return this;
  }

  public TemplateField addAreasItem(TemplateFieldArea areasItem) {
    if (this.areas == null) {
      this.areas = new ArrayList<>();
    }
    this.areas.add(areasItem);
    return this;
  }

  /**
   * List of areas where the field is located in the document.
   * @return areas
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AREAS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<TemplateFieldArea> getAreas() {
    return areas;
  }


  @JsonProperty(value = JSON_PROPERTY_AREAS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAreas(@jakarta.annotation.Nonnull List<TemplateFieldArea> areas) {
    this.areas = areas;
  }


  /**
   * Return true if this TemplateField object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TemplateField templateField = (TemplateField) o;
    return Objects.equals(this.uuid, templateField.uuid) &&
        Objects.equals(this.submitterUuid, templateField.submitterUuid) &&
        Objects.equals(this.name, templateField.name) &&
        Objects.equals(this.type, templateField.type) &&
        Objects.equals(this.required, templateField.required) &&
        Objects.equals(this.preferences, templateField.preferences) &&
        Objects.equals(this.areas, templateField.areas);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uuid, submitterUuid, name, type, required, preferences, areas);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TemplateField {\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    submitterUuid: ").append(toIndentedString(submitterUuid)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    required: ").append(toIndentedString(required)).append("\n");
    sb.append("    preferences: ").append(toIndentedString(preferences)).append("\n");
    sb.append("    areas: ").append(toIndentedString(areas)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

