/*
 * DocuSeal API
 * DocuSeal API specs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@docuseal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.docuseal.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * TemplateSubmitter
 */
@JsonPropertyOrder({
  TemplateSubmitter.JSON_PROPERTY_NAME,
  TemplateSubmitter.JSON_PROPERTY_UUID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class TemplateSubmitter {
  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_UUID = "uuid";
  @jakarta.annotation.Nonnull
  private String uuid;

  public TemplateSubmitter() { 
  }

  public TemplateSubmitter name(@jakarta.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * The name of the submitter.
   * @return name
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nonnull String name) {
    this.name = name;
  }


  public TemplateSubmitter uuid(@jakarta.annotation.Nonnull String uuid) {
    this.uuid = uuid;
    return this;
  }

  /**
   * Unique identifier of the submitter.
   * @return uuid
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_UUID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getUuid() {
    return uuid;
  }


  @JsonProperty(value = JSON_PROPERTY_UUID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUuid(@jakarta.annotation.Nonnull String uuid) {
    this.uuid = uuid;
  }


  /**
   * Return true if this TemplateSubmitter object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TemplateSubmitter templateSubmitter = (TemplateSubmitter) o;
    return Objects.equals(this.name, templateSubmitter.name) &&
        Objects.equals(this.uuid, templateSubmitter.uuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, uuid);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TemplateSubmitter {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

