/*
 * DocuSeal API
 * DocuSeal API specs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@docuseal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.docuseal.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * UpdateTemplateRequest
 */
@JsonPropertyOrder({
  UpdateTemplateRequest.JSON_PROPERTY_NAME,
  UpdateTemplateRequest.JSON_PROPERTY_FOLDER_NAME,
  UpdateTemplateRequest.JSON_PROPERTY_ROLES,
  UpdateTemplateRequest.JSON_PROPERTY_ARCHIVED
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class UpdateTemplateRequest {
  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_FOLDER_NAME = "folder_name";
  @jakarta.annotation.Nullable
  private String folderName;

  public static final String JSON_PROPERTY_ROLES = "roles";
  @jakarta.annotation.Nullable
  private List<String> roles = new ArrayList<>();

  public static final String JSON_PROPERTY_ARCHIVED = "archived";
  @jakarta.annotation.Nullable
  private Boolean archived;

  public UpdateTemplateRequest() { 
  }

  public UpdateTemplateRequest name(@jakarta.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * The name of the template.
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }


  public UpdateTemplateRequest folderName(@jakarta.annotation.Nullable String folderName) {
    this.folderName = folderName;
    return this;
  }

  /**
   * The folder&#39;s name to which the template should be moved.
   * @return folderName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FOLDER_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFolderName() {
    return folderName;
  }


  @JsonProperty(value = JSON_PROPERTY_FOLDER_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFolderName(@jakarta.annotation.Nullable String folderName) {
    this.folderName = folderName;
  }


  public UpdateTemplateRequest roles(@jakarta.annotation.Nullable List<String> roles) {
    this.roles = roles;
    return this;
  }

  public UpdateTemplateRequest addRolesItem(String rolesItem) {
    if (this.roles == null) {
      this.roles = new ArrayList<>();
    }
    this.roles.add(rolesItem);
    return this;
  }

  /**
   * An array of submitter role names to update the template with.
   * @return roles
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ROLES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getRoles() {
    return roles;
  }


  @JsonProperty(value = JSON_PROPERTY_ROLES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRoles(@jakarta.annotation.Nullable List<String> roles) {
    this.roles = roles;
  }


  public UpdateTemplateRequest archived(@jakarta.annotation.Nullable Boolean archived) {
    this.archived = archived;
    return this;
  }

  /**
   * Set &#x60;false&#x60; to unarchive template.
   * @return archived
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ARCHIVED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getArchived() {
    return archived;
  }


  @JsonProperty(value = JSON_PROPERTY_ARCHIVED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setArchived(@jakarta.annotation.Nullable Boolean archived) {
    this.archived = archived;
  }


  /**
   * Return true if this UpdateTemplateRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateTemplateRequest updateTemplateRequest = (UpdateTemplateRequest) o;
    return Objects.equals(this.name, updateTemplateRequest.name) &&
        Objects.equals(this.folderName, updateTemplateRequest.folderName) &&
        Objects.equals(this.roles, updateTemplateRequest.roles) &&
        Objects.equals(this.archived, updateTemplateRequest.archived);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, folderName, roles, archived);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateTemplateRequest {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    folderName: ").append(toIndentedString(folderName)).append("\n");
    sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
    sb.append("    archived: ").append(toIndentedString(archived)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

