/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.docuseal.types;

import com.docuseal.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateTemplateDocumentFieldPreferencesParams.Builder.class)
public final class CreateTemplateDocumentFieldPreferencesParams {
    private final Optional<Integer> fontSize;

    private final Optional<FieldFontType> fontType;

    private final Optional<FieldFont> font;

    private final Optional<String> color;

    private final Optional<String> background;

    private final Optional<FieldAlign> align;

    private final Optional<FieldValign> valign;

    private final Optional<String> format;

    private final Optional<Double> price;

    private final Optional<Currency> currency;

    private final Optional<CreateTemplateDocumentFieldPreferencesParamsMask> mask;

    private final Optional<List<String>> reasons;

    private final Map<String, Object> additionalProperties;

    private CreateTemplateDocumentFieldPreferencesParams(
            Optional<Integer> fontSize,
            Optional<FieldFontType> fontType,
            Optional<FieldFont> font,
            Optional<String> color,
            Optional<String> background,
            Optional<FieldAlign> align,
            Optional<FieldValign> valign,
            Optional<String> format,
            Optional<Double> price,
            Optional<Currency> currency,
            Optional<CreateTemplateDocumentFieldPreferencesParamsMask> mask,
            Optional<List<String>> reasons,
            Map<String, Object> additionalProperties) {
        this.fontSize = fontSize;
        this.fontType = fontType;
        this.font = font;
        this.color = color;
        this.background = background;
        this.align = align;
        this.valign = valign;
        this.format = format;
        this.price = price;
        this.currency = currency;
        this.mask = mask;
        this.reasons = reasons;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Font size of the field value in pixels.
     */
    @JsonProperty("font_size")
    public Optional<Integer> getFontSize() {
        return fontSize;
    }

    /**
     * @return Font type of the field value.
     */
    @JsonProperty("font_type")
    public Optional<FieldFontType> getFontType() {
        return fontType;
    }

    /**
     * @return Font family of the field value.
     */
    @JsonProperty("font")
    public Optional<FieldFont> getFont() {
        return font;
    }

    /**
     * @return Font color of the field value.
     */
    @JsonProperty("color")
    public Optional<String> getColor() {
        return color;
    }

    /**
     * @return Field box background color.
     */
    @JsonProperty("background")
    public Optional<String> getBackground() {
        return background;
    }

    /**
     * @return Horizontal alignment of the field text value.
     */
    @JsonProperty("align")
    public Optional<FieldAlign> getAlign() {
        return align;
    }

    /**
     * @return Vertical alignment of the field text value.
     */
    @JsonProperty("valign")
    public Optional<FieldValign> getValign() {
        return valign;
    }

    /**
     * @return The data format for different field types.<br>- Date field: accepts formats such as DD/MM/YYYY (default: MM/DD/YYYY).<br>- Signature field: accepts drawn, typed, drawn_or_typed (default), or upload.<br>- Number field: accepts currency formats such as usd, eur, gbp.
     */
    @JsonProperty("format")
    public Optional<String> getFormat() {
        return format;
    }

    /**
     * @return Price value of the payment field. Only for payment fields.
     */
    @JsonProperty("price")
    public Optional<Double> getPrice() {
        return price;
    }

    /**
     * @return Currency value of the payment field. Only for payment fields.
     */
    @JsonProperty("currency")
    public Optional<Currency> getCurrency() {
        return currency;
    }

    /**
     * @return Set <code>true</code> to make sensitive data masked on the document.
     */
    @JsonProperty("mask")
    public Optional<CreateTemplateDocumentFieldPreferencesParamsMask> getMask() {
        return mask;
    }

    /**
     * @return An array of signature reasons to choose from.
     */
    @JsonProperty("reasons")
    public Optional<List<String>> getReasons() {
        return reasons;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateTemplateDocumentFieldPreferencesParams
                && equalTo((CreateTemplateDocumentFieldPreferencesParams) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreateTemplateDocumentFieldPreferencesParams other) {
        return fontSize.equals(other.fontSize)
                && fontType.equals(other.fontType)
                && font.equals(other.font)
                && color.equals(other.color)
                && background.equals(other.background)
                && align.equals(other.align)
                && valign.equals(other.valign)
                && format.equals(other.format)
                && price.equals(other.price)
                && currency.equals(other.currency)
                && mask.equals(other.mask)
                && reasons.equals(other.reasons);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.fontSize,
                this.fontType,
                this.font,
                this.color,
                this.background,
                this.align,
                this.valign,
                this.format,
                this.price,
                this.currency,
                this.mask,
                this.reasons);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Integer> fontSize = Optional.empty();

        private Optional<FieldFontType> fontType = Optional.empty();

        private Optional<FieldFont> font = Optional.empty();

        private Optional<String> color = Optional.empty();

        private Optional<String> background = Optional.empty();

        private Optional<FieldAlign> align = Optional.empty();

        private Optional<FieldValign> valign = Optional.empty();

        private Optional<String> format = Optional.empty();

        private Optional<Double> price = Optional.empty();

        private Optional<Currency> currency = Optional.empty();

        private Optional<CreateTemplateDocumentFieldPreferencesParamsMask> mask = Optional.empty();

        private Optional<List<String>> reasons = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(CreateTemplateDocumentFieldPreferencesParams other) {
            fontSize(other.getFontSize());
            fontType(other.getFontType());
            font(other.getFont());
            color(other.getColor());
            background(other.getBackground());
            align(other.getAlign());
            valign(other.getValign());
            format(other.getFormat());
            price(other.getPrice());
            currency(other.getCurrency());
            mask(other.getMask());
            reasons(other.getReasons());
            return this;
        }

        /**
         * <p>Font size of the field value in pixels.</p>
         */
        @JsonSetter(value = "font_size", nulls = Nulls.SKIP)
        public Builder fontSize(Optional<Integer> fontSize) {
            this.fontSize = fontSize;
            return this;
        }

        public Builder fontSize(Integer fontSize) {
            this.fontSize = Optional.ofNullable(fontSize);
            return this;
        }

        /**
         * <p>Font type of the field value.</p>
         */
        @JsonSetter(value = "font_type", nulls = Nulls.SKIP)
        public Builder fontType(Optional<FieldFontType> fontType) {
            this.fontType = fontType;
            return this;
        }

        public Builder fontType(FieldFontType fontType) {
            this.fontType = Optional.ofNullable(fontType);
            return this;
        }

        /**
         * <p>Font family of the field value.</p>
         */
        @JsonSetter(value = "font", nulls = Nulls.SKIP)
        public Builder font(Optional<FieldFont> font) {
            this.font = font;
            return this;
        }

        public Builder font(FieldFont font) {
            this.font = Optional.ofNullable(font);
            return this;
        }

        /**
         * <p>Font color of the field value.</p>
         */
        @JsonSetter(value = "color", nulls = Nulls.SKIP)
        public Builder color(Optional<String> color) {
            this.color = color;
            return this;
        }

        public Builder color(String color) {
            this.color = Optional.ofNullable(color);
            return this;
        }

        /**
         * <p>Field box background color.</p>
         */
        @JsonSetter(value = "background", nulls = Nulls.SKIP)
        public Builder background(Optional<String> background) {
            this.background = background;
            return this;
        }

        public Builder background(String background) {
            this.background = Optional.ofNullable(background);
            return this;
        }

        /**
         * <p>Horizontal alignment of the field text value.</p>
         */
        @JsonSetter(value = "align", nulls = Nulls.SKIP)
        public Builder align(Optional<FieldAlign> align) {
            this.align = align;
            return this;
        }

        public Builder align(FieldAlign align) {
            this.align = Optional.ofNullable(align);
            return this;
        }

        /**
         * <p>Vertical alignment of the field text value.</p>
         */
        @JsonSetter(value = "valign", nulls = Nulls.SKIP)
        public Builder valign(Optional<FieldValign> valign) {
            this.valign = valign;
            return this;
        }

        public Builder valign(FieldValign valign) {
            this.valign = Optional.ofNullable(valign);
            return this;
        }

        /**
         * <p>The data format for different field types.<br>- Date field: accepts formats such as DD/MM/YYYY (default: MM/DD/YYYY).<br>- Signature field: accepts drawn, typed, drawn_or_typed (default), or upload.<br>- Number field: accepts currency formats such as usd, eur, gbp.</p>
         */
        @JsonSetter(value = "format", nulls = Nulls.SKIP)
        public Builder format(Optional<String> format) {
            this.format = format;
            return this;
        }

        public Builder format(String format) {
            this.format = Optional.ofNullable(format);
            return this;
        }

        /**
         * <p>Price value of the payment field. Only for payment fields.</p>
         */
        @JsonSetter(value = "price", nulls = Nulls.SKIP)
        public Builder price(Optional<Double> price) {
            this.price = price;
            return this;
        }

        public Builder price(Double price) {
            this.price = Optional.ofNullable(price);
            return this;
        }

        /**
         * <p>Currency value of the payment field. Only for payment fields.</p>
         */
        @JsonSetter(value = "currency", nulls = Nulls.SKIP)
        public Builder currency(Optional<Currency> currency) {
            this.currency = currency;
            return this;
        }

        public Builder currency(Currency currency) {
            this.currency = Optional.ofNullable(currency);
            return this;
        }

        /**
         * <p>Set <code>true</code> to make sensitive data masked on the document.</p>
         */
        @JsonSetter(value = "mask", nulls = Nulls.SKIP)
        public Builder mask(Optional<CreateTemplateDocumentFieldPreferencesParamsMask> mask) {
            this.mask = mask;
            return this;
        }

        public Builder mask(CreateTemplateDocumentFieldPreferencesParamsMask mask) {
            this.mask = Optional.ofNullable(mask);
            return this;
        }

        /**
         * <p>An array of signature reasons to choose from.</p>
         */
        @JsonSetter(value = "reasons", nulls = Nulls.SKIP)
        public Builder reasons(Optional<List<String>> reasons) {
            this.reasons = reasons;
            return this;
        }

        public Builder reasons(List<String> reasons) {
            this.reasons = Optional.ofNullable(reasons);
            return this;
        }

        public CreateTemplateDocumentFieldPreferencesParams build() {
            return new CreateTemplateDocumentFieldPreferencesParams(
                    fontSize,
                    fontType,
                    font,
                    color,
                    background,
                    align,
                    valign,
                    format,
                    price,
                    currency,
                    mask,
                    reasons,
                    additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
