/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.docuseal.types;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

public enum CreateSubmissionSubmitterFieldPreferencesParamsBackground {
  BLACK("black"),

  WHITE("white"),

  BLUE("blue");

  private final String value;

  CreateSubmissionSubmitterFieldPreferencesParamsBackground(String value) {
    this.value = value;
  }

  @JsonValue
  @java.lang.Override
  public String toString() {
    return this.value;
  }
}
