/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.docuseal.types;

import com.docuseal.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreateSubmissionRequestSubmitterMessage.Builder.class
)
public final class CreateSubmissionRequestSubmitterMessage {
  private final Optional<String> subject;

  private final Optional<String> body;

  private final Map<String, Object> additionalProperties;

  private CreateSubmissionRequestSubmitterMessage(Optional<String> subject, Optional<String> body,
      Map<String, Object> additionalProperties) {
    this.subject = subject;
    this.body = body;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Custom signature request email subject for the submitter.
   */
  @JsonProperty("subject")
  public Optional<String> getSubject() {
    return subject;
  }

  /**
   * @return Custom signature request email body for the submitter. Can include the following variables: {{template.name}}, {{submitter.link}}, {{account.name}}.
   */
  @JsonProperty("body")
  public Optional<String> getBody() {
    return body;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreateSubmissionRequestSubmitterMessage && equalTo((CreateSubmissionRequestSubmitterMessage) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreateSubmissionRequestSubmitterMessage other) {
    return subject.equals(other.subject) && body.equals(other.body);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.subject, this.body);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> subject = Optional.empty();

    private Optional<String> body = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(CreateSubmissionRequestSubmitterMessage other) {
      subject(other.getSubject());
      body(other.getBody());
      return this;
    }

    /**
     * <p>Custom signature request email subject for the submitter.</p>
     */
    @JsonSetter(
        value = "subject",
        nulls = Nulls.SKIP
    )
    public Builder subject(Optional<String> subject) {
      this.subject = subject;
      return this;
    }

    public Builder subject(String subject) {
      this.subject = Optional.ofNullable(subject);
      return this;
    }

    /**
     * <p>Custom signature request email body for the submitter. Can include the following variables: {{template.name}}, {{submitter.link}}, {{account.name}}.</p>
     */
    @JsonSetter(
        value = "body",
        nulls = Nulls.SKIP
    )
    public Builder body(Optional<String> body) {
      this.body = body;
      return this;
    }

    public Builder body(String body) {
      this.body = Optional.ofNullable(body);
      return this;
    }

    public CreateSubmissionRequestSubmitterMessage build() {
      return new CreateSubmissionRequestSubmitterMessage(subject, body, additionalProperties);
    }
  }
}
