/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.docuseal.types;

import com.docuseal.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Double;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreateTemplateFromDocxRequestDocumentFieldArea.Builder.class
)
public final class CreateTemplateFromDocxRequestDocumentFieldArea {
  private final Optional<Double> x;

  private final Optional<Double> y;

  private final Optional<Double> w;

  private final Optional<Double> h;

  private final Optional<Integer> page;

  private final Optional<String> option;

  private final Map<String, Object> additionalProperties;

  private CreateTemplateFromDocxRequestDocumentFieldArea(Optional<Double> x, Optional<Double> y,
      Optional<Double> w, Optional<Double> h, Optional<Integer> page, Optional<String> option,
      Map<String, Object> additionalProperties) {
    this.x = x;
    this.y = y;
    this.w = w;
    this.h = h;
    this.page = page;
    this.option = option;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return X-coordinate of the field area.
   */
  @JsonProperty("x")
  public Optional<Double> getX() {
    return x;
  }

  /**
   * @return Y-coordinate of the field area.
   */
  @JsonProperty("y")
  public Optional<Double> getY() {
    return y;
  }

  /**
   * @return Width of the field area.
   */
  @JsonProperty("w")
  public Optional<Double> getW() {
    return w;
  }

  /**
   * @return Height of the field area.
   */
  @JsonProperty("h")
  public Optional<Double> getH() {
    return h;
  }

  /**
   * @return Page number of the field area. Starts from 1.
   */
  @JsonProperty("page")
  public Optional<Integer> getPage() {
    return page;
  }

  /**
   * @return Option string value for 'radio' and 'multiple' select field types.
   */
  @JsonProperty("option")
  public Optional<String> getOption() {
    return option;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreateTemplateFromDocxRequestDocumentFieldArea && equalTo((CreateTemplateFromDocxRequestDocumentFieldArea) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreateTemplateFromDocxRequestDocumentFieldArea other) {
    return x.equals(other.x) && y.equals(other.y) && w.equals(other.w) && h.equals(other.h) && page.equals(other.page) && option.equals(other.option);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.x, this.y, this.w, this.h, this.page, this.option);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<Double> x = Optional.empty();

    private Optional<Double> y = Optional.empty();

    private Optional<Double> w = Optional.empty();

    private Optional<Double> h = Optional.empty();

    private Optional<Integer> page = Optional.empty();

    private Optional<String> option = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(CreateTemplateFromDocxRequestDocumentFieldArea other) {
      x(other.getX());
      y(other.getY());
      w(other.getW());
      h(other.getH());
      page(other.getPage());
      option(other.getOption());
      return this;
    }

    /**
     * <p>X-coordinate of the field area.</p>
     */
    @JsonSetter(
        value = "x",
        nulls = Nulls.SKIP
    )
    public Builder x(Optional<Double> x) {
      this.x = x;
      return this;
    }

    public Builder x(Double x) {
      this.x = Optional.ofNullable(x);
      return this;
    }

    /**
     * <p>Y-coordinate of the field area.</p>
     */
    @JsonSetter(
        value = "y",
        nulls = Nulls.SKIP
    )
    public Builder y(Optional<Double> y) {
      this.y = y;
      return this;
    }

    public Builder y(Double y) {
      this.y = Optional.ofNullable(y);
      return this;
    }

    /**
     * <p>Width of the field area.</p>
     */
    @JsonSetter(
        value = "w",
        nulls = Nulls.SKIP
    )
    public Builder w(Optional<Double> w) {
      this.w = w;
      return this;
    }

    public Builder w(Double w) {
      this.w = Optional.ofNullable(w);
      return this;
    }

    /**
     * <p>Height of the field area.</p>
     */
    @JsonSetter(
        value = "h",
        nulls = Nulls.SKIP
    )
    public Builder h(Optional<Double> h) {
      this.h = h;
      return this;
    }

    public Builder h(Double h) {
      this.h = Optional.ofNullable(h);
      return this;
    }

    /**
     * <p>Page number of the field area. Starts from 1.</p>
     */
    @JsonSetter(
        value = "page",
        nulls = Nulls.SKIP
    )
    public Builder page(Optional<Integer> page) {
      this.page = page;
      return this;
    }

    public Builder page(Integer page) {
      this.page = Optional.ofNullable(page);
      return this;
    }

    /**
     * <p>Option string value for 'radio' and 'multiple' select field types.</p>
     */
    @JsonSetter(
        value = "option",
        nulls = Nulls.SKIP
    )
    public Builder option(Optional<String> option) {
      this.option = option;
      return this;
    }

    public Builder option(String option) {
      this.option = Optional.ofNullable(option);
      return this;
    }

    public CreateTemplateFromDocxRequestDocumentFieldArea build() {
      return new CreateTemplateFromDocxRequestDocumentFieldArea(x, y, w, h, page, option, additionalProperties);
    }
  }
}
