/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.docuseal.types;

import com.docuseal.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreateSubmissionFromPdfRequestDocumentField.Builder.class
)
public final class CreateSubmissionFromPdfRequestDocumentField {
  private final Optional<String> name;

  private final Optional<CreateSubmissionFromPdfRequestDocumentFieldType> type;

  private final Optional<String> role;

  private final Optional<Boolean> required;

  private final Optional<String> title;

  private final Optional<String> description;

  private final Optional<List<CreateSubmissionFromPdfRequestDocumentFieldArea>> areas;

  private final Optional<List<String>> options;

  private final Map<String, Object> additionalProperties;

  private CreateSubmissionFromPdfRequestDocumentField(Optional<String> name,
      Optional<CreateSubmissionFromPdfRequestDocumentFieldType> type, Optional<String> role,
      Optional<Boolean> required, Optional<String> title, Optional<String> description,
      Optional<List<CreateSubmissionFromPdfRequestDocumentFieldArea>> areas,
      Optional<List<String>> options, Map<String, Object> additionalProperties) {
    this.name = name;
    this.type = type;
    this.role = role;
    this.required = required;
    this.title = title;
    this.description = description;
    this.areas = areas;
    this.options = options;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Name of the field.
   */
  @JsonProperty("name")
  public Optional<String> getName() {
    return name;
  }

  /**
   * @return Type of the field (e.g., text, signature, date, initials).
   */
  @JsonProperty("type")
  public Optional<CreateSubmissionFromPdfRequestDocumentFieldType> getType() {
    return type;
  }

  /**
   * @return Role name of the signer.
   */
  @JsonProperty("role")
  public Optional<String> getRole() {
    return role;
  }

  /**
   * @return Indicates if the field is required.
   */
  @JsonProperty("required")
  public Optional<Boolean> getRequired() {
    return required;
  }

  /**
   * @return Field title displayed to the user instead of the name, shown on the signing form. Supports Markdown.
   */
  @JsonProperty("title")
  public Optional<String> getTitle() {
    return title;
  }

  /**
   * @return Field description displayed on the signing form. Supports Markdown.
   */
  @JsonProperty("description")
  public Optional<String> getDescription() {
    return description;
  }

  /**
   * @return List of areas where the field is located in the document.
   */
  @JsonProperty("areas")
  public Optional<List<CreateSubmissionFromPdfRequestDocumentFieldArea>> getAreas() {
    return areas;
  }

  /**
   * @return An array of option values for 'select' field type.
   */
  @JsonProperty("options")
  public Optional<List<String>> getOptions() {
    return options;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreateSubmissionFromPdfRequestDocumentField && equalTo((CreateSubmissionFromPdfRequestDocumentField) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreateSubmissionFromPdfRequestDocumentField other) {
    return name.equals(other.name) && type.equals(other.type) && role.equals(other.role) && required.equals(other.required) && title.equals(other.title) && description.equals(other.description) && areas.equals(other.areas) && options.equals(other.options);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.name, this.type, this.role, this.required, this.title, this.description, this.areas, this.options);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> name = Optional.empty();

    private Optional<CreateSubmissionFromPdfRequestDocumentFieldType> type = Optional.empty();

    private Optional<String> role = Optional.empty();

    private Optional<Boolean> required = Optional.empty();

    private Optional<String> title = Optional.empty();

    private Optional<String> description = Optional.empty();

    private Optional<List<CreateSubmissionFromPdfRequestDocumentFieldArea>> areas = Optional.empty();

    private Optional<List<String>> options = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(CreateSubmissionFromPdfRequestDocumentField other) {
      name(other.getName());
      type(other.getType());
      role(other.getRole());
      required(other.getRequired());
      title(other.getTitle());
      description(other.getDescription());
      areas(other.getAreas());
      options(other.getOptions());
      return this;
    }

    /**
     * <p>Name of the field.</p>
     */
    @JsonSetter(
        value = "name",
        nulls = Nulls.SKIP
    )
    public Builder name(Optional<String> name) {
      this.name = name;
      return this;
    }

    public Builder name(String name) {
      this.name = Optional.ofNullable(name);
      return this;
    }

    /**
     * <p>Type of the field (e.g., text, signature, date, initials).</p>
     */
    @JsonSetter(
        value = "type",
        nulls = Nulls.SKIP
    )
    public Builder type(Optional<CreateSubmissionFromPdfRequestDocumentFieldType> type) {
      this.type = type;
      return this;
    }

    public Builder type(CreateSubmissionFromPdfRequestDocumentFieldType type) {
      this.type = Optional.ofNullable(type);
      return this;
    }

    /**
     * <p>Role name of the signer.</p>
     */
    @JsonSetter(
        value = "role",
        nulls = Nulls.SKIP
    )
    public Builder role(Optional<String> role) {
      this.role = role;
      return this;
    }

    public Builder role(String role) {
      this.role = Optional.ofNullable(role);
      return this;
    }

    /**
     * <p>Indicates if the field is required.</p>
     */
    @JsonSetter(
        value = "required",
        nulls = Nulls.SKIP
    )
    public Builder required(Optional<Boolean> required) {
      this.required = required;
      return this;
    }

    public Builder required(Boolean required) {
      this.required = Optional.ofNullable(required);
      return this;
    }

    /**
     * <p>Field title displayed to the user instead of the name, shown on the signing form. Supports Markdown.</p>
     */
    @JsonSetter(
        value = "title",
        nulls = Nulls.SKIP
    )
    public Builder title(Optional<String> title) {
      this.title = title;
      return this;
    }

    public Builder title(String title) {
      this.title = Optional.ofNullable(title);
      return this;
    }

    /**
     * <p>Field description displayed on the signing form. Supports Markdown.</p>
     */
    @JsonSetter(
        value = "description",
        nulls = Nulls.SKIP
    )
    public Builder description(Optional<String> description) {
      this.description = description;
      return this;
    }

    public Builder description(String description) {
      this.description = Optional.ofNullable(description);
      return this;
    }

    /**
     * <p>List of areas where the field is located in the document.</p>
     */
    @JsonSetter(
        value = "areas",
        nulls = Nulls.SKIP
    )
    public Builder areas(Optional<List<CreateSubmissionFromPdfRequestDocumentFieldArea>> areas) {
      this.areas = areas;
      return this;
    }

    public Builder areas(List<CreateSubmissionFromPdfRequestDocumentFieldArea> areas) {
      this.areas = Optional.ofNullable(areas);
      return this;
    }

    /**
     * <p>An array of option values for 'select' field type.</p>
     */
    @JsonSetter(
        value = "options",
        nulls = Nulls.SKIP
    )
    public Builder options(Optional<List<String>> options) {
      this.options = options;
      return this;
    }

    public Builder options(List<String> options) {
      this.options = Optional.ofNullable(options);
      return this;
    }

    public CreateSubmissionFromPdfRequestDocumentField build() {
      return new CreateSubmissionFromPdfRequestDocumentField(name, type, role, required, title, description, areas, options, additionalProperties);
    }
  }
}
