/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.docuseal.types;

import com.docuseal.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreateSubmissionsFromEmailsResponseItemPreferences.Builder.class
)
public final class CreateSubmissionsFromEmailsResponseItemPreferences {
  private final Optional<Boolean> sendEmail;

  private final Optional<Boolean> sendSms;

  private final Map<String, Object> additionalProperties;

  private CreateSubmissionsFromEmailsResponseItemPreferences(Optional<Boolean> sendEmail,
      Optional<Boolean> sendSms, Map<String, Object> additionalProperties) {
    this.sendEmail = sendEmail;
    this.sendSms = sendSms;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Indicates whether the signature request email should be sent.
   */
  @JsonProperty("send_email")
  public Optional<Boolean> getSendEmail() {
    return sendEmail;
  }

  /**
   * @return Indicates whether the signature request should be sent via SMS.
   */
  @JsonProperty("send_sms")
  public Optional<Boolean> getSendSms() {
    return sendSms;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreateSubmissionsFromEmailsResponseItemPreferences && equalTo((CreateSubmissionsFromEmailsResponseItemPreferences) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreateSubmissionsFromEmailsResponseItemPreferences other) {
    return sendEmail.equals(other.sendEmail) && sendSms.equals(other.sendSms);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.sendEmail, this.sendSms);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<Boolean> sendEmail = Optional.empty();

    private Optional<Boolean> sendSms = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(CreateSubmissionsFromEmailsResponseItemPreferences other) {
      sendEmail(other.getSendEmail());
      sendSms(other.getSendSms());
      return this;
    }

    /**
     * <p>Indicates whether the signature request email should be sent.</p>
     */
    @JsonSetter(
        value = "send_email",
        nulls = Nulls.SKIP
    )
    public Builder sendEmail(Optional<Boolean> sendEmail) {
      this.sendEmail = sendEmail;
      return this;
    }

    public Builder sendEmail(Boolean sendEmail) {
      this.sendEmail = Optional.ofNullable(sendEmail);
      return this;
    }

    /**
     * <p>Indicates whether the signature request should be sent via SMS.</p>
     */
    @JsonSetter(
        value = "send_sms",
        nulls = Nulls.SKIP
    )
    public Builder sendSms(Optional<Boolean> sendSms) {
      this.sendSms = sendSms;
      return this;
    }

    public Builder sendSms(Boolean sendSms) {
      this.sendSms = Optional.ofNullable(sendSms);
      return this;
    }

    public CreateSubmissionsFromEmailsResponseItemPreferences build() {
      return new CreateSubmissionsFromEmailsResponseItemPreferences(sendEmail, sendSms, additionalProperties);
    }
  }
}
