/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.docuseal.types;

import com.docuseal.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreateSubmissionFromPdfResponseSchemaDocument.Builder.class
)
public final class CreateSubmissionFromPdfResponseSchemaDocument {
  private final Optional<String> attachmentUuid;

  private final Optional<String> name;

  private final Map<String, Object> additionalProperties;

  private CreateSubmissionFromPdfResponseSchemaDocument(Optional<String> attachmentUuid,
      Optional<String> name, Map<String, Object> additionalProperties) {
    this.attachmentUuid = attachmentUuid;
    this.name = name;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The attachment UUID.
   */
  @JsonProperty("attachment_uuid")
  public Optional<String> getAttachmentUuid() {
    return attachmentUuid;
  }

  /**
   * @return The attachment name.
   */
  @JsonProperty("name")
  public Optional<String> getName() {
    return name;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreateSubmissionFromPdfResponseSchemaDocument && equalTo((CreateSubmissionFromPdfResponseSchemaDocument) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreateSubmissionFromPdfResponseSchemaDocument other) {
    return attachmentUuid.equals(other.attachmentUuid) && name.equals(other.name);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.attachmentUuid, this.name);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> attachmentUuid = Optional.empty();

    private Optional<String> name = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(CreateSubmissionFromPdfResponseSchemaDocument other) {
      attachmentUuid(other.getAttachmentUuid());
      name(other.getName());
      return this;
    }

    /**
     * <p>The attachment UUID.</p>
     */
    @JsonSetter(
        value = "attachment_uuid",
        nulls = Nulls.SKIP
    )
    public Builder attachmentUuid(Optional<String> attachmentUuid) {
      this.attachmentUuid = attachmentUuid;
      return this;
    }

    public Builder attachmentUuid(String attachmentUuid) {
      this.attachmentUuid = Optional.ofNullable(attachmentUuid);
      return this;
    }

    /**
     * <p>The attachment name.</p>
     */
    @JsonSetter(
        value = "name",
        nulls = Nulls.SKIP
    )
    public Builder name(Optional<String> name) {
      this.name = name;
      return this;
    }

    public Builder name(String name) {
      this.name = Optional.ofNullable(name);
      return this;
    }

    public CreateSubmissionFromPdfResponseSchemaDocument build() {
      return new CreateSubmissionFromPdfResponseSchemaDocument(attachmentUuid, name, additionalProperties);
    }
  }
}
