/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.docuseal.types;

import com.docuseal.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Double;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = FieldValidation.Builder.class
)
public final class FieldValidation {
  private final Optional<String> pattern;

  private final Optional<String> message;

  private final Optional<FieldValidationMin> min;

  private final Optional<FieldValidationMax> max;

  private final Optional<Double> step;

  private final Map<String, Object> additionalProperties;

  private FieldValidation(Optional<String> pattern, Optional<String> message,
      Optional<FieldValidationMin> min, Optional<FieldValidationMax> max, Optional<Double> step,
      Map<String, Object> additionalProperties) {
    this.pattern = pattern;
    this.message = message;
    this.min = min;
    this.max = max;
    this.step = step;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return HTML field validation pattern string based on https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/pattern specification.
   */
  @JsonProperty("pattern")
  public Optional<String> getPattern() {
    return pattern;
  }

  /**
   * @return A custom error message to display on validation failure.
   */
  @JsonProperty("message")
  public Optional<String> getMessage() {
    return message;
  }

  /**
   * @return Minimum allowed number value or date depending on field type.
   */
  @JsonProperty("min")
  public Optional<FieldValidationMin> getMin() {
    return min;
  }

  /**
   * @return Maximum allowed number value or date depending on field type.
   */
  @JsonProperty("max")
  public Optional<FieldValidationMax> getMax() {
    return max;
  }

  /**
   * @return Increment step for number field. Pass 1 to accept only integers, or 0.01 to accept decimal currency.
   */
  @JsonProperty("step")
  public Optional<Double> getStep() {
    return step;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof FieldValidation && equalTo((FieldValidation) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(FieldValidation other) {
    return pattern.equals(other.pattern) && message.equals(other.message) && min.equals(other.min) && max.equals(other.max) && step.equals(other.step);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.pattern, this.message, this.min, this.max, this.step);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> pattern = Optional.empty();

    private Optional<String> message = Optional.empty();

    private Optional<FieldValidationMin> min = Optional.empty();

    private Optional<FieldValidationMax> max = Optional.empty();

    private Optional<Double> step = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(FieldValidation other) {
      pattern(other.getPattern());
      message(other.getMessage());
      min(other.getMin());
      max(other.getMax());
      step(other.getStep());
      return this;
    }

    /**
     * <p>HTML field validation pattern string based on https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/pattern specification.</p>
     */
    @JsonSetter(
        value = "pattern",
        nulls = Nulls.SKIP
    )
    public Builder pattern(Optional<String> pattern) {
      this.pattern = pattern;
      return this;
    }

    public Builder pattern(String pattern) {
      this.pattern = Optional.ofNullable(pattern);
      return this;
    }

    /**
     * <p>A custom error message to display on validation failure.</p>
     */
    @JsonSetter(
        value = "message",
        nulls = Nulls.SKIP
    )
    public Builder message(Optional<String> message) {
      this.message = message;
      return this;
    }

    public Builder message(String message) {
      this.message = Optional.ofNullable(message);
      return this;
    }

    /**
     * <p>Minimum allowed number value or date depending on field type.</p>
     */
    @JsonSetter(
        value = "min",
        nulls = Nulls.SKIP
    )
    public Builder min(Optional<FieldValidationMin> min) {
      this.min = min;
      return this;
    }

    public Builder min(FieldValidationMin min) {
      this.min = Optional.ofNullable(min);
      return this;
    }

    /**
     * <p>Maximum allowed number value or date depending on field type.</p>
     */
    @JsonSetter(
        value = "max",
        nulls = Nulls.SKIP
    )
    public Builder max(Optional<FieldValidationMax> max) {
      this.max = max;
      return this;
    }

    public Builder max(FieldValidationMax max) {
      this.max = Optional.ofNullable(max);
      return this;
    }

    /**
     * <p>Increment step for number field. Pass 1 to accept only integers, or 0.01 to accept decimal currency.</p>
     */
    @JsonSetter(
        value = "step",
        nulls = Nulls.SKIP
    )
    public Builder step(Optional<Double> step) {
      this.step = step;
      return this;
    }

    public Builder step(Double step) {
      this.step = Optional.ofNullable(step);
      return this;
    }

    public FieldValidation build() {
      return new FieldValidation(pattern, message, min, max, step, additionalProperties);
    }
  }
}
