/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.docuseal.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class FieldAlign {
    public static final FieldAlign LEFT = new FieldAlign(Value.LEFT, "left");

    public static final FieldAlign RIGHT = new FieldAlign(Value.RIGHT, "right");

    public static final FieldAlign CENTER = new FieldAlign(Value.CENTER, "center");

    private final Value value;

    private final String string;

    FieldAlign(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other) || (other instanceof FieldAlign && this.string.equals(((FieldAlign) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case LEFT:
                return visitor.visitLeft();
            case RIGHT:
                return visitor.visitRight();
            case CENTER:
                return visitor.visitCenter();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static FieldAlign valueOf(String value) {
        switch (value) {
            case "left":
                return LEFT;
            case "right":
                return RIGHT;
            case "center":
                return CENTER;
            default:
                return new FieldAlign(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        LEFT,

        CENTER,

        RIGHT,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitLeft();

        T visitCenter();

        T visitRight();

        T visitUnknown(String unknownType);
    }
}
