/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.docuseal.types;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

public enum FieldPreferencesValign {
  TOP("top"),

  CENTER("center"),

  BOTTOM("bottom");

  private final String value;

  FieldPreferencesValign(String value) {
    this.value = value;
  }

  @JsonValue
  @java.lang.Override
  public String toString() {
    return this.value;
  }
}
