/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.docuseal.types;

import com.docuseal.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = FieldArea.Builder.class
)
public final class FieldArea {
  private final double x;

  private final double y;

  private final double w;

  private final double h;

  private final String attachmentUuid;

  private final int page;

  private final Map<String, Object> additionalProperties;

  private FieldArea(double x, double y, double w, double h, String attachmentUuid, int page,
      Map<String, Object> additionalProperties) {
    this.x = x;
    this.y = y;
    this.w = w;
    this.h = h;
    this.attachmentUuid = attachmentUuid;
    this.page = page;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return X coordinate of the area where the field is located in the document.
   */
  @JsonProperty("x")
  public double getX() {
    return x;
  }

  /**
   * @return Y coordinate of the area where the field is located in the document.
   */
  @JsonProperty("y")
  public double getY() {
    return y;
  }

  /**
   * @return Width of the area where the field is located in the document.
   */
  @JsonProperty("w")
  public double getW() {
    return w;
  }

  /**
   * @return Height of the area where the field is located in the document.
   */
  @JsonProperty("h")
  public double getH() {
    return h;
  }

  /**
   * @return Unique identifier of the attached document where the field is located.
   */
  @JsonProperty("attachment_uuid")
  public String getAttachmentUuid() {
    return attachmentUuid;
  }

  /**
   * @return Page number of the attached document where the field is located.
   */
  @JsonProperty("page")
  public int getPage() {
    return page;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof FieldArea && equalTo((FieldArea) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(FieldArea other) {
    return x == other.x && y == other.y && w == other.w && h == other.h && attachmentUuid.equals(other.attachmentUuid) && page == other.page;
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.x, this.y, this.w, this.h, this.attachmentUuid, this.page);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static XStage builder() {
    return new Builder();
  }

  public interface XStage {
    /**
     * <p>X coordinate of the area where the field is located in the document.</p>
     */
    YStage x(double x);

    Builder from(FieldArea other);
  }

  public interface YStage {
    /**
     * <p>Y coordinate of the area where the field is located in the document.</p>
     */
    WStage y(double y);
  }

  public interface WStage {
    /**
     * <p>Width of the area where the field is located in the document.</p>
     */
    HStage w(double w);
  }

  public interface HStage {
    /**
     * <p>Height of the area where the field is located in the document.</p>
     */
    AttachmentUuidStage h(double h);
  }

  public interface AttachmentUuidStage {
    /**
     * <p>Unique identifier of the attached document where the field is located.</p>
     */
    PageStage attachmentUuid(@NotNull String attachmentUuid);
  }

  public interface PageStage {
    /**
     * <p>Page number of the attached document where the field is located.</p>
     */
    _FinalStage page(int page);
  }

  public interface _FinalStage {
    FieldArea build();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements XStage, YStage, WStage, HStage, AttachmentUuidStage, PageStage, _FinalStage {
    private double x;

    private double y;

    private double w;

    private double h;

    private String attachmentUuid;

    private int page;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(FieldArea other) {
      x(other.getX());
      y(other.getY());
      w(other.getW());
      h(other.getH());
      attachmentUuid(other.getAttachmentUuid());
      page(other.getPage());
      return this;
    }

    /**
     * <p>X coordinate of the area where the field is located in the document.</p>
     * <p>X coordinate of the area where the field is located in the document.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("x")
    public YStage x(double x) {
      this.x = x;
      return this;
    }

    /**
     * <p>Y coordinate of the area where the field is located in the document.</p>
     * <p>Y coordinate of the area where the field is located in the document.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("y")
    public WStage y(double y) {
      this.y = y;
      return this;
    }

    /**
     * <p>Width of the area where the field is located in the document.</p>
     * <p>Width of the area where the field is located in the document.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("w")
    public HStage w(double w) {
      this.w = w;
      return this;
    }

    /**
     * <p>Height of the area where the field is located in the document.</p>
     * <p>Height of the area where the field is located in the document.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("h")
    public AttachmentUuidStage h(double h) {
      this.h = h;
      return this;
    }

    /**
     * <p>Unique identifier of the attached document where the field is located.</p>
     * <p>Unique identifier of the attached document where the field is located.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("attachment_uuid")
    public PageStage attachmentUuid(@NotNull String attachmentUuid) {
      this.attachmentUuid = Objects.requireNonNull(attachmentUuid, "attachmentUuid must not be null");
      return this;
    }

    /**
     * <p>Page number of the attached document where the field is located.</p>
     * <p>Page number of the attached document where the field is located.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("page")
    public _FinalStage page(int page) {
      this.page = page;
      return this;
    }

    @java.lang.Override
    public FieldArea build() {
      return new FieldArea(x, y, w, h, attachmentUuid, page, additionalProperties);
    }
  }
}
