/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.docuseal.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class FieldFont {
    public static final FieldFont HELVETICA = new FieldFont(Value.HELVETICA, "Helvetica");

    public static final FieldFont TIMES = new FieldFont(Value.TIMES, "Times");

    public static final FieldFont COURIER = new FieldFont(Value.COURIER, "Courier");

    private final Value value;

    private final String string;

    FieldFont(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other) || (other instanceof FieldFont && this.string.equals(((FieldFont) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case HELVETICA:
                return visitor.visitHelvetica();
            case TIMES:
                return visitor.visitTimes();
            case COURIER:
                return visitor.visitCourier();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static FieldFont valueOf(String value) {
        switch (value) {
            case "Helvetica":
                return HELVETICA;
            case "Times":
                return TIMES;
            case "Courier":
                return COURIER;
            default:
                return new FieldFont(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        TIMES,

        HELVETICA,

        COURIER,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitTimes();

        T visitHelvetica();

        T visitCourier();

        T visitUnknown(String unknownType);
    }
}
