/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.docuseal.types;

import com.docuseal.core.Nullable;
import com.docuseal.core.NullableNonemptyFilter;
import com.docuseal.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = Submitter.Builder.class)
public final class Submitter {
    private final int id;

    private final int submissionId;

    private final String uuid;

    private final Optional<String> email;

    private final String slug;

    private final Optional<String> sentAt;

    private final Optional<String> openedAt;

    private final Optional<String> completedAt;

    private final Optional<String> declinedAt;

    private final String createdAt;

    private final String updatedAt;

    private final Optional<String> name;

    private final Optional<String> phone;

    private final SubmitterStatus status;

    private final Optional<String> externalId;

    private final Map<String, Object> metadata;

    private final Map<String, Object> preferences;

    private final Optional<SubmitterTemplate> template;

    private final List<SubmissionEvent> submissionEvents;

    private final List<FieldValue> values;

    private final List<Document> documents;

    private final String role;

    private final Map<String, Object> additionalProperties;

    private Submitter(
            int id,
            int submissionId,
            String uuid,
            Optional<String> email,
            String slug,
            Optional<String> sentAt,
            Optional<String> openedAt,
            Optional<String> completedAt,
            Optional<String> declinedAt,
            String createdAt,
            String updatedAt,
            Optional<String> name,
            Optional<String> phone,
            SubmitterStatus status,
            Optional<String> externalId,
            Map<String, Object> metadata,
            Map<String, Object> preferences,
            Optional<SubmitterTemplate> template,
            List<SubmissionEvent> submissionEvents,
            List<FieldValue> values,
            List<Document> documents,
            String role,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.submissionId = submissionId;
        this.uuid = uuid;
        this.email = email;
        this.slug = slug;
        this.sentAt = sentAt;
        this.openedAt = openedAt;
        this.completedAt = completedAt;
        this.declinedAt = declinedAt;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.name = name;
        this.phone = phone;
        this.status = status;
        this.externalId = externalId;
        this.metadata = metadata;
        this.preferences = preferences;
        this.template = template;
        this.submissionEvents = submissionEvents;
        this.values = values;
        this.documents = documents;
        this.role = role;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Submitter unique ID number.
     */
    @JsonProperty("id")
    public int getId() {
        return id;
    }

    /**
     * @return Submission unique ID number.
     */
    @JsonProperty("submission_id")
    public int getSubmissionId() {
        return submissionId;
    }

    /**
     * @return Submitter UUID.
     */
    @JsonProperty("uuid")
    public String getUuid() {
        return uuid;
    }

    /**
     * @return The email address of the submitter.
     */
    @JsonIgnore
    public Optional<String> getEmail() {
        if (email == null) {
            return Optional.empty();
        }
        return email;
    }

    /**
     * @return Unique key to be used in the form signing link and embedded form.
     */
    @JsonProperty("slug")
    public String getSlug() {
        return slug;
    }

    /**
     * @return The date and time when the signing request was sent to the submitter.
     */
    @JsonIgnore
    public Optional<String> getSentAt() {
        if (sentAt == null) {
            return Optional.empty();
        }
        return sentAt;
    }

    /**
     * @return The date and time when the submitter opened the signing form.
     */
    @JsonIgnore
    public Optional<String> getOpenedAt() {
        if (openedAt == null) {
            return Optional.empty();
        }
        return openedAt;
    }

    /**
     * @return The date and time when the submitter completed the signing form.
     */
    @JsonIgnore
    public Optional<String> getCompletedAt() {
        if (completedAt == null) {
            return Optional.empty();
        }
        return completedAt;
    }

    /**
     * @return The date and time when the submitter declined the signing form.
     */
    @JsonIgnore
    public Optional<String> getDeclinedAt() {
        if (declinedAt == null) {
            return Optional.empty();
        }
        return declinedAt;
    }

    /**
     * @return The date and time when the submitter was created.
     */
    @JsonProperty("created_at")
    public String getCreatedAt() {
        return createdAt;
    }

    /**
     * @return The date and time when the submitter was last updated.
     */
    @JsonProperty("updated_at")
    public String getUpdatedAt() {
        return updatedAt;
    }

    /**
     * @return The name of the submitter.
     */
    @JsonIgnore
    public Optional<String> getName() {
        if (name == null) {
            return Optional.empty();
        }
        return name;
    }

    /**
     * @return The phone number of the submitter.
     */
    @JsonIgnore
    public Optional<String> getPhone() {
        if (phone == null) {
            return Optional.empty();
        }
        return phone;
    }

    /**
     * @return The status of signing request for the submitter.
     */
    @JsonProperty("status")
    public SubmitterStatus getStatus() {
        return status;
    }

    /**
     * @return Your application-specific unique string key to identify this submitter within your app.
     */
    @JsonIgnore
    public Optional<String> getExternalId() {
        if (externalId == null) {
            return Optional.empty();
        }
        return externalId;
    }

    /**
     * @return Metadata object with additional submitter information.
     */
    @JsonProperty("metadata")
    public Map<String, Object> getMetadata() {
        return metadata;
    }

    /**
     * @return Submitter preferences.
     */
    @JsonProperty("preferences")
    public Map<String, Object> getPreferences() {
        return preferences;
    }

    @JsonIgnore
    public Optional<SubmitterTemplate> getTemplate() {
        if (template == null) {
            return Optional.empty();
        }
        return template;
    }

    /**
     * @return An array of events related to the submission.
     */
    @JsonProperty("submission_events")
    public List<SubmissionEvent> getSubmissionEvents() {
        return submissionEvents;
    }

    /**
     * @return An array of pre-filled values for the submitter.
     */
    @JsonProperty("values")
    public List<FieldValue> getValues() {
        return values;
    }

    /**
     * @return An array of completed or signed documents by the submitter.
     */
    @JsonProperty("documents")
    public List<Document> getDocuments() {
        return documents;
    }

    /**
     * @return The role of the submitter in the signing process.
     */
    @JsonProperty("role")
    public String getRole() {
        return role;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("email")
    private Optional<String> _getEmail() {
        return email;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("sent_at")
    private Optional<String> _getSentAt() {
        return sentAt;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("opened_at")
    private Optional<String> _getOpenedAt() {
        return openedAt;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("completed_at")
    private Optional<String> _getCompletedAt() {
        return completedAt;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("declined_at")
    private Optional<String> _getDeclinedAt() {
        return declinedAt;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("name")
    private Optional<String> _getName() {
        return name;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("phone")
    private Optional<String> _getPhone() {
        return phone;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("external_id")
    private Optional<String> _getExternalId() {
        return externalId;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("template")
    private Optional<SubmitterTemplate> _getTemplate() {
        return template;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof Submitter && equalTo((Submitter) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(Submitter other) {
        return id == other.id
                && submissionId == other.submissionId
                && uuid.equals(other.uuid)
                && email.equals(other.email)
                && slug.equals(other.slug)
                && sentAt.equals(other.sentAt)
                && openedAt.equals(other.openedAt)
                && completedAt.equals(other.completedAt)
                && declinedAt.equals(other.declinedAt)
                && createdAt.equals(other.createdAt)
                && updatedAt.equals(other.updatedAt)
                && name.equals(other.name)
                && phone.equals(other.phone)
                && status.equals(other.status)
                && externalId.equals(other.externalId)
                && metadata.equals(other.metadata)
                && preferences.equals(other.preferences)
                && template.equals(other.template)
                && submissionEvents.equals(other.submissionEvents)
                && values.equals(other.values)
                && documents.equals(other.documents)
                && role.equals(other.role);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.id,
                this.submissionId,
                this.uuid,
                this.email,
                this.slug,
                this.sentAt,
                this.openedAt,
                this.completedAt,
                this.declinedAt,
                this.createdAt,
                this.updatedAt,
                this.name,
                this.phone,
                this.status,
                this.externalId,
                this.metadata,
                this.preferences,
                this.template,
                this.submissionEvents,
                this.values,
                this.documents,
                this.role);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        /**
         * <p>Submitter unique ID number.</p>
         */
        SubmissionIdStage id(int id);

        Builder from(Submitter other);
    }

    public interface SubmissionIdStage {
        /**
         * <p>Submission unique ID number.</p>
         */
        UuidStage submissionId(int submissionId);
    }

    public interface UuidStage {
        /**
         * <p>Submitter UUID.</p>
         */
        SlugStage uuid(@NotNull String uuid);
    }

    public interface SlugStage {
        /**
         * <p>Unique key to be used in the form signing link and embedded form.</p>
         */
        CreatedAtStage slug(@NotNull String slug);
    }

    public interface CreatedAtStage {
        /**
         * <p>The date and time when the submitter was created.</p>
         */
        UpdatedAtStage createdAt(@NotNull String createdAt);
    }

    public interface UpdatedAtStage {
        /**
         * <p>The date and time when the submitter was last updated.</p>
         */
        StatusStage updatedAt(@NotNull String updatedAt);
    }

    public interface StatusStage {
        /**
         * <p>The status of signing request for the submitter.</p>
         */
        RoleStage status(@NotNull SubmitterStatus status);
    }

    public interface RoleStage {
        /**
         * <p>The role of the submitter in the signing process.</p>
         */
        _FinalStage role(@NotNull String role);
    }

    public interface _FinalStage {
        Submitter build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>The email address of the submitter.</p>
         */
        _FinalStage email(Optional<String> email);

        _FinalStage email(String email);

        _FinalStage email(Nullable<String> email);

        /**
         * <p>The date and time when the signing request was sent to the submitter.</p>
         */
        _FinalStage sentAt(Optional<String> sentAt);

        _FinalStage sentAt(String sentAt);

        _FinalStage sentAt(Nullable<String> sentAt);

        /**
         * <p>The date and time when the submitter opened the signing form.</p>
         */
        _FinalStage openedAt(Optional<String> openedAt);

        _FinalStage openedAt(String openedAt);

        _FinalStage openedAt(Nullable<String> openedAt);

        /**
         * <p>The date and time when the submitter completed the signing form.</p>
         */
        _FinalStage completedAt(Optional<String> completedAt);

        _FinalStage completedAt(String completedAt);

        _FinalStage completedAt(Nullable<String> completedAt);

        /**
         * <p>The date and time when the submitter declined the signing form.</p>
         */
        _FinalStage declinedAt(Optional<String> declinedAt);

        _FinalStage declinedAt(String declinedAt);

        _FinalStage declinedAt(Nullable<String> declinedAt);

        /**
         * <p>The name of the submitter.</p>
         */
        _FinalStage name(Optional<String> name);

        _FinalStage name(String name);

        _FinalStage name(Nullable<String> name);

        /**
         * <p>The phone number of the submitter.</p>
         */
        _FinalStage phone(Optional<String> phone);

        _FinalStage phone(String phone);

        _FinalStage phone(Nullable<String> phone);

        /**
         * <p>Your application-specific unique string key to identify this submitter within your app.</p>
         */
        _FinalStage externalId(Optional<String> externalId);

        _FinalStage externalId(String externalId);

        _FinalStage externalId(Nullable<String> externalId);

        /**
         * <p>Metadata object with additional submitter information.</p>
         */
        _FinalStage metadata(Map<String, Object> metadata);

        _FinalStage putAllMetadata(Map<String, Object> metadata);

        _FinalStage metadata(String key, Object value);

        /**
         * <p>Submitter preferences.</p>
         */
        _FinalStage preferences(Map<String, Object> preferences);

        _FinalStage putAllPreferences(Map<String, Object> preferences);

        _FinalStage preferences(String key, Object value);

        _FinalStage template(Optional<SubmitterTemplate> template);

        _FinalStage template(SubmitterTemplate template);

        _FinalStage template(Nullable<SubmitterTemplate> template);

        /**
         * <p>An array of events related to the submission.</p>
         */
        _FinalStage submissionEvents(List<SubmissionEvent> submissionEvents);

        _FinalStage addSubmissionEvents(SubmissionEvent submissionEvents);

        _FinalStage addAllSubmissionEvents(List<SubmissionEvent> submissionEvents);

        /**
         * <p>An array of pre-filled values for the submitter.</p>
         */
        _FinalStage values(List<FieldValue> values);

        _FinalStage addValues(FieldValue values);

        _FinalStage addAllValues(List<FieldValue> values);

        /**
         * <p>An array of completed or signed documents by the submitter.</p>
         */
        _FinalStage documents(List<Document> documents);

        _FinalStage addDocuments(Document documents);

        _FinalStage addAllDocuments(List<Document> documents);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements IdStage,
                    SubmissionIdStage,
                    UuidStage,
                    SlugStage,
                    CreatedAtStage,
                    UpdatedAtStage,
                    StatusStage,
                    RoleStage,
                    _FinalStage {
        private int id;

        private int submissionId;

        private String uuid;

        private String slug;

        private String createdAt;

        private String updatedAt;

        private SubmitterStatus status;

        private String role;

        private List<Document> documents = new ArrayList<>();

        private List<FieldValue> values = new ArrayList<>();

        private List<SubmissionEvent> submissionEvents = new ArrayList<>();

        private Optional<SubmitterTemplate> template = Optional.empty();

        private Map<String, Object> preferences = new LinkedHashMap<>();

        private Map<String, Object> metadata = new LinkedHashMap<>();

        private Optional<String> externalId = Optional.empty();

        private Optional<String> phone = Optional.empty();

        private Optional<String> name = Optional.empty();

        private Optional<String> declinedAt = Optional.empty();

        private Optional<String> completedAt = Optional.empty();

        private Optional<String> openedAt = Optional.empty();

        private Optional<String> sentAt = Optional.empty();

        private Optional<String> email = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(Submitter other) {
            id(other.getId());
            submissionId(other.getSubmissionId());
            uuid(other.getUuid());
            email(other.getEmail());
            slug(other.getSlug());
            sentAt(other.getSentAt());
            openedAt(other.getOpenedAt());
            completedAt(other.getCompletedAt());
            declinedAt(other.getDeclinedAt());
            createdAt(other.getCreatedAt());
            updatedAt(other.getUpdatedAt());
            name(other.getName());
            phone(other.getPhone());
            status(other.getStatus());
            externalId(other.getExternalId());
            metadata(other.getMetadata());
            preferences(other.getPreferences());
            template(other.getTemplate());
            submissionEvents(other.getSubmissionEvents());
            values(other.getValues());
            documents(other.getDocuments());
            role(other.getRole());
            return this;
        }

        /**
         * <p>Submitter unique ID number.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public SubmissionIdStage id(int id) {
            this.id = id;
            return this;
        }

        /**
         * <p>Submission unique ID number.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("submission_id")
        public UuidStage submissionId(int submissionId) {
            this.submissionId = submissionId;
            return this;
        }

        /**
         * <p>Submitter UUID.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("uuid")
        public SlugStage uuid(@NotNull String uuid) {
            this.uuid = Objects.requireNonNull(uuid, "uuid must not be null");
            return this;
        }

        /**
         * <p>Unique key to be used in the form signing link and embedded form.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("slug")
        public CreatedAtStage slug(@NotNull String slug) {
            this.slug = Objects.requireNonNull(slug, "slug must not be null");
            return this;
        }

        /**
         * <p>The date and time when the submitter was created.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("created_at")
        public UpdatedAtStage createdAt(@NotNull String createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        /**
         * <p>The date and time when the submitter was last updated.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("updated_at")
        public StatusStage updatedAt(@NotNull String updatedAt) {
            this.updatedAt = Objects.requireNonNull(updatedAt, "updatedAt must not be null");
            return this;
        }

        /**
         * <p>The status of signing request for the submitter.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("status")
        public RoleStage status(@NotNull SubmitterStatus status) {
            this.status = Objects.requireNonNull(status, "status must not be null");
            return this;
        }

        /**
         * <p>The role of the submitter in the signing process.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("role")
        public _FinalStage role(@NotNull String role) {
            this.role = Objects.requireNonNull(role, "role must not be null");
            return this;
        }

        /**
         * <p>An array of completed or signed documents by the submitter.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAllDocuments(List<Document> documents) {
            if (documents != null) {
                this.documents.addAll(documents);
            }
            return this;
        }

        /**
         * <p>An array of completed or signed documents by the submitter.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addDocuments(Document documents) {
            this.documents.add(documents);
            return this;
        }

        /**
         * <p>An array of completed or signed documents by the submitter.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "documents", nulls = Nulls.SKIP)
        public _FinalStage documents(List<Document> documents) {
            this.documents.clear();
            if (documents != null) {
                this.documents.addAll(documents);
            }
            return this;
        }

        /**
         * <p>An array of pre-filled values for the submitter.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAllValues(List<FieldValue> values) {
            if (values != null) {
                this.values.addAll(values);
            }
            return this;
        }

        /**
         * <p>An array of pre-filled values for the submitter.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addValues(FieldValue values) {
            this.values.add(values);
            return this;
        }

        /**
         * <p>An array of pre-filled values for the submitter.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "values", nulls = Nulls.SKIP)
        public _FinalStage values(List<FieldValue> values) {
            this.values.clear();
            if (values != null) {
                this.values.addAll(values);
            }
            return this;
        }

        /**
         * <p>An array of events related to the submission.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAllSubmissionEvents(List<SubmissionEvent> submissionEvents) {
            if (submissionEvents != null) {
                this.submissionEvents.addAll(submissionEvents);
            }
            return this;
        }

        /**
         * <p>An array of events related to the submission.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addSubmissionEvents(SubmissionEvent submissionEvents) {
            this.submissionEvents.add(submissionEvents);
            return this;
        }

        /**
         * <p>An array of events related to the submission.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "submission_events", nulls = Nulls.SKIP)
        public _FinalStage submissionEvents(List<SubmissionEvent> submissionEvents) {
            this.submissionEvents.clear();
            if (submissionEvents != null) {
                this.submissionEvents.addAll(submissionEvents);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage template(Nullable<SubmitterTemplate> template) {
            if (template.isNull()) {
                this.template = null;
            } else if (template.isEmpty()) {
                this.template = Optional.empty();
            } else {
                this.template = Optional.of(template.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage template(SubmitterTemplate template) {
            this.template = Optional.ofNullable(template);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "template", nulls = Nulls.SKIP)
        public _FinalStage template(Optional<SubmitterTemplate> template) {
            this.template = template;
            return this;
        }

        /**
         * <p>Submitter preferences.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage preferences(String key, Object value) {
            this.preferences.put(key, value);
            return this;
        }

        /**
         * <p>Submitter preferences.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage putAllPreferences(Map<String, Object> preferences) {
            if (preferences != null) {
                this.preferences.putAll(preferences);
            }
            return this;
        }

        /**
         * <p>Submitter preferences.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "preferences", nulls = Nulls.SKIP)
        public _FinalStage preferences(Map<String, Object> preferences) {
            this.preferences.clear();
            if (preferences != null) {
                this.preferences.putAll(preferences);
            }
            return this;
        }

        /**
         * <p>Metadata object with additional submitter information.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage metadata(String key, Object value) {
            this.metadata.put(key, value);
            return this;
        }

        /**
         * <p>Metadata object with additional submitter information.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage putAllMetadata(Map<String, Object> metadata) {
            if (metadata != null) {
                this.metadata.putAll(metadata);
            }
            return this;
        }

        /**
         * <p>Metadata object with additional submitter information.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "metadata", nulls = Nulls.SKIP)
        public _FinalStage metadata(Map<String, Object> metadata) {
            this.metadata.clear();
            if (metadata != null) {
                this.metadata.putAll(metadata);
            }
            return this;
        }

        /**
         * <p>Your application-specific unique string key to identify this submitter within your app.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage externalId(Nullable<String> externalId) {
            if (externalId.isNull()) {
                this.externalId = null;
            } else if (externalId.isEmpty()) {
                this.externalId = Optional.empty();
            } else {
                this.externalId = Optional.of(externalId.get());
            }
            return this;
        }

        /**
         * <p>Your application-specific unique string key to identify this submitter within your app.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage externalId(String externalId) {
            this.externalId = Optional.ofNullable(externalId);
            return this;
        }

        /**
         * <p>Your application-specific unique string key to identify this submitter within your app.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "external_id", nulls = Nulls.SKIP)
        public _FinalStage externalId(Optional<String> externalId) {
            this.externalId = externalId;
            return this;
        }

        /**
         * <p>The phone number of the submitter.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage phone(Nullable<String> phone) {
            if (phone.isNull()) {
                this.phone = null;
            } else if (phone.isEmpty()) {
                this.phone = Optional.empty();
            } else {
                this.phone = Optional.of(phone.get());
            }
            return this;
        }

        /**
         * <p>The phone number of the submitter.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage phone(String phone) {
            this.phone = Optional.ofNullable(phone);
            return this;
        }

        /**
         * <p>The phone number of the submitter.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "phone", nulls = Nulls.SKIP)
        public _FinalStage phone(Optional<String> phone) {
            this.phone = phone;
            return this;
        }

        /**
         * <p>The name of the submitter.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage name(Nullable<String> name) {
            if (name.isNull()) {
                this.name = null;
            } else if (name.isEmpty()) {
                this.name = Optional.empty();
            } else {
                this.name = Optional.of(name.get());
            }
            return this;
        }

        /**
         * <p>The name of the submitter.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage name(String name) {
            this.name = Optional.ofNullable(name);
            return this;
        }

        /**
         * <p>The name of the submitter.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "name", nulls = Nulls.SKIP)
        public _FinalStage name(Optional<String> name) {
            this.name = name;
            return this;
        }

        /**
         * <p>The date and time when the submitter declined the signing form.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage declinedAt(Nullable<String> declinedAt) {
            if (declinedAt.isNull()) {
                this.declinedAt = null;
            } else if (declinedAt.isEmpty()) {
                this.declinedAt = Optional.empty();
            } else {
                this.declinedAt = Optional.of(declinedAt.get());
            }
            return this;
        }

        /**
         * <p>The date and time when the submitter declined the signing form.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage declinedAt(String declinedAt) {
            this.declinedAt = Optional.ofNullable(declinedAt);
            return this;
        }

        /**
         * <p>The date and time when the submitter declined the signing form.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "declined_at", nulls = Nulls.SKIP)
        public _FinalStage declinedAt(Optional<String> declinedAt) {
            this.declinedAt = declinedAt;
            return this;
        }

        /**
         * <p>The date and time when the submitter completed the signing form.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage completedAt(Nullable<String> completedAt) {
            if (completedAt.isNull()) {
                this.completedAt = null;
            } else if (completedAt.isEmpty()) {
                this.completedAt = Optional.empty();
            } else {
                this.completedAt = Optional.of(completedAt.get());
            }
            return this;
        }

        /**
         * <p>The date and time when the submitter completed the signing form.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage completedAt(String completedAt) {
            this.completedAt = Optional.ofNullable(completedAt);
            return this;
        }

        /**
         * <p>The date and time when the submitter completed the signing form.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "completed_at", nulls = Nulls.SKIP)
        public _FinalStage completedAt(Optional<String> completedAt) {
            this.completedAt = completedAt;
            return this;
        }

        /**
         * <p>The date and time when the submitter opened the signing form.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage openedAt(Nullable<String> openedAt) {
            if (openedAt.isNull()) {
                this.openedAt = null;
            } else if (openedAt.isEmpty()) {
                this.openedAt = Optional.empty();
            } else {
                this.openedAt = Optional.of(openedAt.get());
            }
            return this;
        }

        /**
         * <p>The date and time when the submitter opened the signing form.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage openedAt(String openedAt) {
            this.openedAt = Optional.ofNullable(openedAt);
            return this;
        }

        /**
         * <p>The date and time when the submitter opened the signing form.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "opened_at", nulls = Nulls.SKIP)
        public _FinalStage openedAt(Optional<String> openedAt) {
            this.openedAt = openedAt;
            return this;
        }

        /**
         * <p>The date and time when the signing request was sent to the submitter.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage sentAt(Nullable<String> sentAt) {
            if (sentAt.isNull()) {
                this.sentAt = null;
            } else if (sentAt.isEmpty()) {
                this.sentAt = Optional.empty();
            } else {
                this.sentAt = Optional.of(sentAt.get());
            }
            return this;
        }

        /**
         * <p>The date and time when the signing request was sent to the submitter.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage sentAt(String sentAt) {
            this.sentAt = Optional.ofNullable(sentAt);
            return this;
        }

        /**
         * <p>The date and time when the signing request was sent to the submitter.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "sent_at", nulls = Nulls.SKIP)
        public _FinalStage sentAt(Optional<String> sentAt) {
            this.sentAt = sentAt;
            return this;
        }

        /**
         * <p>The email address of the submitter.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage email(Nullable<String> email) {
            if (email.isNull()) {
                this.email = null;
            } else if (email.isEmpty()) {
                this.email = Optional.empty();
            } else {
                this.email = Optional.of(email.get());
            }
            return this;
        }

        /**
         * <p>The email address of the submitter.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage email(String email) {
            this.email = Optional.ofNullable(email);
            return this;
        }

        /**
         * <p>The email address of the submitter.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "email", nulls = Nulls.SKIP)
        public _FinalStage email(Optional<String> email) {
            this.email = email;
            return this;
        }

        @java.lang.Override
        public Submitter build() {
            return new Submitter(
                    id,
                    submissionId,
                    uuid,
                    email,
                    slug,
                    sentAt,
                    openedAt,
                    completedAt,
                    declinedAt,
                    createdAt,
                    updatedAt,
                    name,
                    phone,
                    status,
                    externalId,
                    metadata,
                    preferences,
                    template,
                    submissionEvents,
                    values,
                    documents,
                    role,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
