/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.docuseal.types;

import com.docuseal.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SubmissionEvent.Builder.class)
public final class SubmissionEvent {
    private final int id;

    private final int submitterId;

    private final SubmissionEventType eventType;

    private final String eventTimestamp;

    private final Optional<Map<String, Object>> data;

    private final Map<String, Object> additionalProperties;

    private SubmissionEvent(
            int id,
            int submitterId,
            SubmissionEventType eventType,
            String eventTimestamp,
            Optional<Map<String, Object>> data,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.submitterId = submitterId;
        this.eventType = eventType;
        this.eventTimestamp = eventTimestamp;
        this.data = data;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Submission event unique ID number.
     */
    @JsonProperty("id")
    public int getId() {
        return id;
    }

    /**
     * @return Unique identifier of the submitter that triggered the event.
     */
    @JsonProperty("submitter_id")
    public int getSubmitterId() {
        return submitterId;
    }

    /**
     * @return Event type.
     */
    @JsonProperty("event_type")
    public SubmissionEventType getEventType() {
        return eventType;
    }

    /**
     * @return Date and time when the event was triggered.
     */
    @JsonProperty("event_timestamp")
    public String getEventTimestamp() {
        return eventTimestamp;
    }

    /**
     * @return Additional event details object.
     */
    @JsonProperty("data")
    public Optional<Map<String, Object>> getData() {
        return data;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof SubmissionEvent && equalTo((SubmissionEvent) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(SubmissionEvent other) {
        return id == other.id
                && submitterId == other.submitterId
                && eventType.equals(other.eventType)
                && eventTimestamp.equals(other.eventTimestamp)
                && data.equals(other.data);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.id, this.submitterId, this.eventType, this.eventTimestamp, this.data);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        /**
         * <p>Submission event unique ID number.</p>
         */
        SubmitterIdStage id(int id);

        Builder from(SubmissionEvent other);
    }

    public interface SubmitterIdStage {
        /**
         * <p>Unique identifier of the submitter that triggered the event.</p>
         */
        EventTypeStage submitterId(int submitterId);
    }

    public interface EventTypeStage {
        /**
         * <p>Event type.</p>
         */
        EventTimestampStage eventType(@NotNull SubmissionEventType eventType);
    }

    public interface EventTimestampStage {
        /**
         * <p>Date and time when the event was triggered.</p>
         */
        _FinalStage eventTimestamp(@NotNull String eventTimestamp);
    }

    public interface _FinalStage {
        SubmissionEvent build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Additional event details object.</p>
         */
        _FinalStage data(Optional<Map<String, Object>> data);

        _FinalStage data(Map<String, Object> data);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements IdStage, SubmitterIdStage, EventTypeStage, EventTimestampStage, _FinalStage {
        private int id;

        private int submitterId;

        private SubmissionEventType eventType;

        private String eventTimestamp;

        private Optional<Map<String, Object>> data = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(SubmissionEvent other) {
            id(other.getId());
            submitterId(other.getSubmitterId());
            eventType(other.getEventType());
            eventTimestamp(other.getEventTimestamp());
            data(other.getData());
            return this;
        }

        /**
         * <p>Submission event unique ID number.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public SubmitterIdStage id(int id) {
            this.id = id;
            return this;
        }

        /**
         * <p>Unique identifier of the submitter that triggered the event.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("submitter_id")
        public EventTypeStage submitterId(int submitterId) {
            this.submitterId = submitterId;
            return this;
        }

        /**
         * <p>Event type.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("event_type")
        public EventTimestampStage eventType(@NotNull SubmissionEventType eventType) {
            this.eventType = Objects.requireNonNull(eventType, "eventType must not be null");
            return this;
        }

        /**
         * <p>Date and time when the event was triggered.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("event_timestamp")
        public _FinalStage eventTimestamp(@NotNull String eventTimestamp) {
            this.eventTimestamp = Objects.requireNonNull(eventTimestamp, "eventTimestamp must not be null");
            return this;
        }

        /**
         * <p>Additional event details object.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage data(Map<String, Object> data) {
            this.data = Optional.ofNullable(data);
            return this;
        }

        /**
         * <p>Additional event details object.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "data", nulls = Nulls.SKIP)
        public _FinalStage data(Optional<Map<String, Object>> data) {
            this.data = data;
            return this;
        }

        @java.lang.Override
        public SubmissionEvent build() {
            return new SubmissionEvent(id, submitterId, eventType, eventTimestamp, data, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
