/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.docuseal.types;

import com.docuseal.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = SubmissionList.Builder.class
)
public final class SubmissionList {
  private final List<SubmissionListItem> data;

  private final Pagination pagination;

  private final Map<String, Object> additionalProperties;

  private SubmissionList(List<SubmissionListItem> data, Pagination pagination,
      Map<String, Object> additionalProperties) {
    this.data = data;
    this.pagination = pagination;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("data")
  public List<SubmissionListItem> getData() {
    return data;
  }

  @JsonProperty("pagination")
  public Pagination getPagination() {
    return pagination;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof SubmissionList && equalTo((SubmissionList) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(SubmissionList other) {
    return data.equals(other.data) && pagination.equals(other.pagination);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.data, this.pagination);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static PaginationStage builder() {
    return new Builder();
  }

  public interface PaginationStage {
    _FinalStage pagination(@NotNull Pagination pagination);

    Builder from(SubmissionList other);
  }

  public interface _FinalStage {
    SubmissionList build();

    _FinalStage data(List<SubmissionListItem> data);

    _FinalStage addData(SubmissionListItem data);

    _FinalStage addAllData(List<SubmissionListItem> data);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements PaginationStage, _FinalStage {
    private Pagination pagination;

    private List<SubmissionListItem> data = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(SubmissionList other) {
      data(other.getData());
      pagination(other.getPagination());
      return this;
    }

    @java.lang.Override
    @JsonSetter("pagination")
    public _FinalStage pagination(@NotNull Pagination pagination) {
      this.pagination = Objects.requireNonNull(pagination, "pagination must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllData(List<SubmissionListItem> data) {
      this.data.addAll(data);
      return this;
    }

    @java.lang.Override
    public _FinalStage addData(SubmissionListItem data) {
      this.data.add(data);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "data",
        nulls = Nulls.SKIP
    )
    public _FinalStage data(List<SubmissionListItem> data) {
      this.data.clear();
      this.data.addAll(data);
      return this;
    }

    @java.lang.Override
    public SubmissionList build() {
      return new SubmissionList(data, pagination, additionalProperties);
    }
  }
}
