/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.docuseal.types;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

public enum UpdateSubmitterFieldPreferencesParamsFontType {
  BOLD("bold"),

  ITALIC("italic"),

  BOLD_ITALIC("bold_italic");

  private final String value;

  UpdateSubmitterFieldPreferencesParamsFontType(String value) {
    this.value = value;
  }

  @JsonValue
  @java.lang.Override
  public String toString() {
    return this.value;
  }
}
