/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.docuseal.resources.submitters;

import com.docuseal.core.ClientOptions;
import com.docuseal.core.RequestOptions;
import com.docuseal.resources.submitters.requests.GetSubmitterRequest;
import com.docuseal.resources.submitters.requests.GetSubmittersRequest;
import com.docuseal.resources.submitters.requests.UpdateSubmitterRequest;
import com.docuseal.types.GetSubmitterResponse;
import com.docuseal.types.GetSubmittersResponse;
import com.docuseal.types.UpdateSubmitterResponse;
import java.util.concurrent.CompletableFuture;

public class AsyncSubmittersClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawSubmittersClient rawClient;

  public AsyncSubmittersClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawSubmittersClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawSubmittersClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * The API endpoint provides functionality to retrieve information about a submitter, along with the submitter documents and field values.
   */
  public CompletableFuture<GetSubmitterResponse> getSubmitter(int id) {
    return this.rawClient.getSubmitter(id).thenApply(response -> response.body());
  }

  /**
   * The API endpoint provides functionality to retrieve information about a submitter, along with the submitter documents and field values.
   */
  public CompletableFuture<GetSubmitterResponse> getSubmitter(int id, GetSubmitterRequest request) {
    return this.rawClient.getSubmitter(id, request).thenApply(response -> response.body());
  }

  /**
   * The API endpoint provides functionality to retrieve information about a submitter, along with the submitter documents and field values.
   */
  public CompletableFuture<GetSubmitterResponse> getSubmitter(int id, GetSubmitterRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.getSubmitter(id, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * The API endpoint allows you to update submitter details, pre-fill or update field values and re-send emails.&lt;br&gt;&lt;b&gt;Related Guides&lt;/b&gt;&lt;br&gt;&lt;a href=&quot;https://www.docuseal.com/guides/pre-fill-pdf-document-form-fields-with-api#automatically_sign_documents_via_api&quot; class=&quot;link&quot;&gt;Automatically sign documents via API&lt;/a&gt;
   */
  public CompletableFuture<UpdateSubmitterResponse> updateSubmitter(int id) {
    return this.rawClient.updateSubmitter(id).thenApply(response -> response.body());
  }

  /**
   * The API endpoint allows you to update submitter details, pre-fill or update field values and re-send emails.&lt;br&gt;&lt;b&gt;Related Guides&lt;/b&gt;&lt;br&gt;&lt;a href=&quot;https://www.docuseal.com/guides/pre-fill-pdf-document-form-fields-with-api#automatically_sign_documents_via_api&quot; class=&quot;link&quot;&gt;Automatically sign documents via API&lt;/a&gt;
   */
  public CompletableFuture<UpdateSubmitterResponse> updateSubmitter(int id,
      UpdateSubmitterRequest request) {
    return this.rawClient.updateSubmitter(id, request).thenApply(response -> response.body());
  }

  /**
   * The API endpoint allows you to update submitter details, pre-fill or update field values and re-send emails.&lt;br&gt;&lt;b&gt;Related Guides&lt;/b&gt;&lt;br&gt;&lt;a href=&quot;https://www.docuseal.com/guides/pre-fill-pdf-document-form-fields-with-api#automatically_sign_documents_via_api&quot; class=&quot;link&quot;&gt;Automatically sign documents via API&lt;/a&gt;
   */
  public CompletableFuture<UpdateSubmitterResponse> updateSubmitter(int id,
      UpdateSubmitterRequest request, RequestOptions requestOptions) {
    return this.rawClient.updateSubmitter(id, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * The API endpoint provides the ability to retrieve a list of submitters.
   */
  public CompletableFuture<GetSubmittersResponse> getSubmitters() {
    return this.rawClient.getSubmitters().thenApply(response -> response.body());
  }

  /**
   * The API endpoint provides the ability to retrieve a list of submitters.
   */
  public CompletableFuture<GetSubmittersResponse> getSubmitters(GetSubmittersRequest request) {
    return this.rawClient.getSubmitters(request).thenApply(response -> response.body());
  }

  /**
   * The API endpoint provides the ability to retrieve a list of submitters.
   */
  public CompletableFuture<GetSubmittersResponse> getSubmitters(GetSubmittersRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.getSubmitters(request, requestOptions).thenApply(response -> response.body());
  }
}
