/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.docuseal.requests;

import com.docuseal.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CloneTemplateParams.Builder.class
)
public final class CloneTemplateParams {
  private final Optional<String> name;

  private final Optional<String> folderName;

  private final Optional<String> externalId;

  private final Map<String, Object> additionalProperties;

  private CloneTemplateParams(Optional<String> name, Optional<String> folderName,
      Optional<String> externalId, Map<String, Object> additionalProperties) {
    this.name = name;
    this.folderName = folderName;
    this.externalId = externalId;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Template name. Existing name with (Clone) suffix will be used if not specified.
   */
  @JsonProperty("name")
  public Optional<String> getName() {
    return name;
  }

  /**
   * @return The folder's name to which the template should be cloned.
   */
  @JsonProperty("folder_name")
  public Optional<String> getFolderName() {
    return folderName;
  }

  /**
   * @return Your application-specific unique string key to identify this template within your app.
   */
  @JsonProperty("external_id")
  public Optional<String> getExternalId() {
    return externalId;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CloneTemplateParams && equalTo((CloneTemplateParams) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CloneTemplateParams other) {
    return name.equals(other.name) && folderName.equals(other.folderName) && externalId.equals(other.externalId);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.name, this.folderName, this.externalId);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> name = Optional.empty();

    private Optional<String> folderName = Optional.empty();

    private Optional<String> externalId = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(CloneTemplateParams other) {
      name(other.getName());
      folderName(other.getFolderName());
      externalId(other.getExternalId());
      return this;
    }

    /**
     * <p>Template name. Existing name with (Clone) suffix will be used if not specified.</p>
     */
    @JsonSetter(
        value = "name",
        nulls = Nulls.SKIP
    )
    public Builder name(Optional<String> name) {
      this.name = name;
      return this;
    }

    public Builder name(String name) {
      this.name = Optional.ofNullable(name);
      return this;
    }

    /**
     * <p>The folder's name to which the template should be cloned.</p>
     */
    @JsonSetter(
        value = "folder_name",
        nulls = Nulls.SKIP
    )
    public Builder folderName(Optional<String> folderName) {
      this.folderName = folderName;
      return this;
    }

    public Builder folderName(String folderName) {
      this.folderName = Optional.ofNullable(folderName);
      return this;
    }

    /**
     * <p>Your application-specific unique string key to identify this template within your app.</p>
     */
    @JsonSetter(
        value = "external_id",
        nulls = Nulls.SKIP
    )
    public Builder externalId(Optional<String> externalId) {
      this.externalId = externalId;
      return this;
    }

    public Builder externalId(String externalId) {
      this.externalId = Optional.ofNullable(externalId);
      return this;
    }

    public CloneTemplateParams build() {
      return new CloneTemplateParams(name, folderName, externalId, additionalProperties);
    }
  }
}
