/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.docuseal.requests;

import com.docuseal.core.ObjectMappers;
import com.docuseal.types.CreateSubmissionMessageParams;
import com.docuseal.types.CreateSubmissionSubmitterParams;
import com.docuseal.types.SubmittersOrder;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateSubmissionParams.Builder.class)
public final class CreateSubmissionParams {
    private final int templateId;

    private final Optional<Boolean> sendEmail;

    private final Optional<Boolean> sendSms;

    private final Optional<SubmittersOrder> order;

    private final Optional<String> completedRedirectUrl;

    private final Optional<String> bccCompleted;

    private final Optional<String> replyTo;

    private final Optional<String> expireAt;

    private final Optional<Map<String, Object>> variables;

    private final Optional<CreateSubmissionMessageParams> message;

    private final List<CreateSubmissionSubmitterParams> submitters;

    private final Map<String, Object> additionalProperties;

    private CreateSubmissionParams(
            int templateId,
            Optional<Boolean> sendEmail,
            Optional<Boolean> sendSms,
            Optional<SubmittersOrder> order,
            Optional<String> completedRedirectUrl,
            Optional<String> bccCompleted,
            Optional<String> replyTo,
            Optional<String> expireAt,
            Optional<Map<String, Object>> variables,
            Optional<CreateSubmissionMessageParams> message,
            List<CreateSubmissionSubmitterParams> submitters,
            Map<String, Object> additionalProperties) {
        this.templateId = templateId;
        this.sendEmail = sendEmail;
        this.sendSms = sendSms;
        this.order = order;
        this.completedRedirectUrl = completedRedirectUrl;
        this.bccCompleted = bccCompleted;
        this.replyTo = replyTo;
        this.expireAt = expireAt;
        this.variables = variables;
        this.message = message;
        this.submitters = submitters;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The unique identifier of the template. Document template forms can be created via the Web UI, <a href="https://www.docuseal.com/guides/use-embedded-text-field-tags-in-the-pdf-to-create-a-fillable-form" class="link">PDF and DOCX API</a>, or <a href="https://www.docuseal.com/guides/create-pdf-document-fillable-form-with-html-api" class="link">HTML API</a>.
     */
    @JsonProperty("template_id")
    public int getTemplateId() {
        return templateId;
    }

    /**
     * @return Set <code>false</code> to disable signature request emails sending.
     */
    @JsonProperty("send_email")
    public Optional<Boolean> getSendEmail() {
        return sendEmail;
    }

    /**
     * @return Set <code>true</code> to send signature request via phone number and SMS.
     */
    @JsonProperty("send_sms")
    public Optional<Boolean> getSendSms() {
        return sendSms;
    }

    /**
     * @return Pass 'random' to send signature request emails to all parties right away. The order is 'preserved' by default so the second party will receive a signature request email only after the document is signed by the first party.
     */
    @JsonProperty("order")
    public Optional<SubmittersOrder> getOrder() {
        return order;
    }

    /**
     * @return Specify URL to redirect to after the submission completion.
     */
    @JsonProperty("completed_redirect_url")
    public Optional<String> getCompletedRedirectUrl() {
        return completedRedirectUrl;
    }

    /**
     * @return Specify BCC address to send signed documents to after the completion.
     */
    @JsonProperty("bcc_completed")
    public Optional<String> getBccCompleted() {
        return bccCompleted;
    }

    /**
     * @return Specify Reply-To address to use in the notification emails.
     */
    @JsonProperty("reply_to")
    public Optional<String> getReplyTo() {
        return replyTo;
    }

    /**
     * @return Specify the expiration date and time after which the submission becomes unavailable for signature.
     */
    @JsonProperty("expire_at")
    public Optional<String> getExpireAt() {
        return expireAt;
    }

    /**
     * @return Dynamic content variables object. Variable values can be strings, numbers, arrays, objects, or HTML content used to generate styled text, paragraphs, and tables in dynamic template documents.
     */
    @JsonProperty("variables")
    public Optional<Map<String, Object>> getVariables() {
        return variables;
    }

    @JsonProperty("message")
    public Optional<CreateSubmissionMessageParams> getMessage() {
        return message;
    }

    /**
     * @return The list of submitters for the submission.
     */
    @JsonProperty("submitters")
    public List<CreateSubmissionSubmitterParams> getSubmitters() {
        return submitters;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateSubmissionParams && equalTo((CreateSubmissionParams) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreateSubmissionParams other) {
        return templateId == other.templateId
                && sendEmail.equals(other.sendEmail)
                && sendSms.equals(other.sendSms)
                && order.equals(other.order)
                && completedRedirectUrl.equals(other.completedRedirectUrl)
                && bccCompleted.equals(other.bccCompleted)
                && replyTo.equals(other.replyTo)
                && expireAt.equals(other.expireAt)
                && variables.equals(other.variables)
                && message.equals(other.message)
                && submitters.equals(other.submitters);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.templateId,
                this.sendEmail,
                this.sendSms,
                this.order,
                this.completedRedirectUrl,
                this.bccCompleted,
                this.replyTo,
                this.expireAt,
                this.variables,
                this.message,
                this.submitters);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static TemplateIdStage builder() {
        return new Builder();
    }

    public interface TemplateIdStage {
        /**
         * <p>The unique identifier of the template. Document template forms can be created via the Web UI, <a href="https://www.docuseal.com/guides/use-embedded-text-field-tags-in-the-pdf-to-create-a-fillable-form" class="link">PDF and DOCX API</a>, or <a href="https://www.docuseal.com/guides/create-pdf-document-fillable-form-with-html-api" class="link">HTML API</a>.</p>
         */
        _FinalStage templateId(int templateId);

        Builder from(CreateSubmissionParams other);
    }

    public interface _FinalStage {
        CreateSubmissionParams build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Set <code>false</code> to disable signature request emails sending.</p>
         */
        _FinalStage sendEmail(Optional<Boolean> sendEmail);

        _FinalStage sendEmail(Boolean sendEmail);

        /**
         * <p>Set <code>true</code> to send signature request via phone number and SMS.</p>
         */
        _FinalStage sendSms(Optional<Boolean> sendSms);

        _FinalStage sendSms(Boolean sendSms);

        /**
         * <p>Pass 'random' to send signature request emails to all parties right away. The order is 'preserved' by default so the second party will receive a signature request email only after the document is signed by the first party.</p>
         */
        _FinalStage order(Optional<SubmittersOrder> order);

        _FinalStage order(SubmittersOrder order);

        /**
         * <p>Specify URL to redirect to after the submission completion.</p>
         */
        _FinalStage completedRedirectUrl(Optional<String> completedRedirectUrl);

        _FinalStage completedRedirectUrl(String completedRedirectUrl);

        /**
         * <p>Specify BCC address to send signed documents to after the completion.</p>
         */
        _FinalStage bccCompleted(Optional<String> bccCompleted);

        _FinalStage bccCompleted(String bccCompleted);

        /**
         * <p>Specify Reply-To address to use in the notification emails.</p>
         */
        _FinalStage replyTo(Optional<String> replyTo);

        _FinalStage replyTo(String replyTo);

        /**
         * <p>Specify the expiration date and time after which the submission becomes unavailable for signature.</p>
         */
        _FinalStage expireAt(Optional<String> expireAt);

        _FinalStage expireAt(String expireAt);

        /**
         * <p>Dynamic content variables object. Variable values can be strings, numbers, arrays, objects, or HTML content used to generate styled text, paragraphs, and tables in dynamic template documents.</p>
         */
        _FinalStage variables(Optional<Map<String, Object>> variables);

        _FinalStage variables(Map<String, Object> variables);

        _FinalStage message(Optional<CreateSubmissionMessageParams> message);

        _FinalStage message(CreateSubmissionMessageParams message);

        /**
         * <p>The list of submitters for the submission.</p>
         */
        _FinalStage submitters(List<CreateSubmissionSubmitterParams> submitters);

        _FinalStage addSubmitters(CreateSubmissionSubmitterParams submitters);

        _FinalStage addAllSubmitters(List<CreateSubmissionSubmitterParams> submitters);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements TemplateIdStage, _FinalStage {
        private int templateId;

        private List<CreateSubmissionSubmitterParams> submitters = new ArrayList<>();

        private Optional<CreateSubmissionMessageParams> message = Optional.empty();

        private Optional<Map<String, Object>> variables = Optional.empty();

        private Optional<String> expireAt = Optional.empty();

        private Optional<String> replyTo = Optional.empty();

        private Optional<String> bccCompleted = Optional.empty();

        private Optional<String> completedRedirectUrl = Optional.empty();

        private Optional<SubmittersOrder> order = Optional.empty();

        private Optional<Boolean> sendSms = Optional.empty();

        private Optional<Boolean> sendEmail = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CreateSubmissionParams other) {
            templateId(other.getTemplateId());
            sendEmail(other.getSendEmail());
            sendSms(other.getSendSms());
            order(other.getOrder());
            completedRedirectUrl(other.getCompletedRedirectUrl());
            bccCompleted(other.getBccCompleted());
            replyTo(other.getReplyTo());
            expireAt(other.getExpireAt());
            variables(other.getVariables());
            message(other.getMessage());
            submitters(other.getSubmitters());
            return this;
        }

        /**
         * <p>The unique identifier of the template. Document template forms can be created via the Web UI, <a href="https://www.docuseal.com/guides/use-embedded-text-field-tags-in-the-pdf-to-create-a-fillable-form" class="link">PDF and DOCX API</a>, or <a href="https://www.docuseal.com/guides/create-pdf-document-fillable-form-with-html-api" class="link">HTML API</a>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("template_id")
        public _FinalStage templateId(int templateId) {
            this.templateId = templateId;
            return this;
        }

        /**
         * <p>The list of submitters for the submission.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAllSubmitters(List<CreateSubmissionSubmitterParams> submitters) {
            if (submitters != null) {
                this.submitters.addAll(submitters);
            }
            return this;
        }

        /**
         * <p>The list of submitters for the submission.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addSubmitters(CreateSubmissionSubmitterParams submitters) {
            this.submitters.add(submitters);
            return this;
        }

        /**
         * <p>The list of submitters for the submission.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "submitters", nulls = Nulls.SKIP)
        public _FinalStage submitters(List<CreateSubmissionSubmitterParams> submitters) {
            this.submitters.clear();
            if (submitters != null) {
                this.submitters.addAll(submitters);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage message(CreateSubmissionMessageParams message) {
            this.message = Optional.ofNullable(message);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "message", nulls = Nulls.SKIP)
        public _FinalStage message(Optional<CreateSubmissionMessageParams> message) {
            this.message = message;
            return this;
        }

        /**
         * <p>Dynamic content variables object. Variable values can be strings, numbers, arrays, objects, or HTML content used to generate styled text, paragraphs, and tables in dynamic template documents.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage variables(Map<String, Object> variables) {
            this.variables = Optional.ofNullable(variables);
            return this;
        }

        /**
         * <p>Dynamic content variables object. Variable values can be strings, numbers, arrays, objects, or HTML content used to generate styled text, paragraphs, and tables in dynamic template documents.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "variables", nulls = Nulls.SKIP)
        public _FinalStage variables(Optional<Map<String, Object>> variables) {
            this.variables = variables;
            return this;
        }

        /**
         * <p>Specify the expiration date and time after which the submission becomes unavailable for signature.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage expireAt(String expireAt) {
            this.expireAt = Optional.ofNullable(expireAt);
            return this;
        }

        /**
         * <p>Specify the expiration date and time after which the submission becomes unavailable for signature.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "expire_at", nulls = Nulls.SKIP)
        public _FinalStage expireAt(Optional<String> expireAt) {
            this.expireAt = expireAt;
            return this;
        }

        /**
         * <p>Specify Reply-To address to use in the notification emails.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage replyTo(String replyTo) {
            this.replyTo = Optional.ofNullable(replyTo);
            return this;
        }

        /**
         * <p>Specify Reply-To address to use in the notification emails.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "reply_to", nulls = Nulls.SKIP)
        public _FinalStage replyTo(Optional<String> replyTo) {
            this.replyTo = replyTo;
            return this;
        }

        /**
         * <p>Specify BCC address to send signed documents to after the completion.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage bccCompleted(String bccCompleted) {
            this.bccCompleted = Optional.ofNullable(bccCompleted);
            return this;
        }

        /**
         * <p>Specify BCC address to send signed documents to after the completion.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "bcc_completed", nulls = Nulls.SKIP)
        public _FinalStage bccCompleted(Optional<String> bccCompleted) {
            this.bccCompleted = bccCompleted;
            return this;
        }

        /**
         * <p>Specify URL to redirect to after the submission completion.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage completedRedirectUrl(String completedRedirectUrl) {
            this.completedRedirectUrl = Optional.ofNullable(completedRedirectUrl);
            return this;
        }

        /**
         * <p>Specify URL to redirect to after the submission completion.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "completed_redirect_url", nulls = Nulls.SKIP)
        public _FinalStage completedRedirectUrl(Optional<String> completedRedirectUrl) {
            this.completedRedirectUrl = completedRedirectUrl;
            return this;
        }

        /**
         * <p>Pass 'random' to send signature request emails to all parties right away. The order is 'preserved' by default so the second party will receive a signature request email only after the document is signed by the first party.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage order(SubmittersOrder order) {
            this.order = Optional.ofNullable(order);
            return this;
        }

        /**
         * <p>Pass 'random' to send signature request emails to all parties right away. The order is 'preserved' by default so the second party will receive a signature request email only after the document is signed by the first party.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "order", nulls = Nulls.SKIP)
        public _FinalStage order(Optional<SubmittersOrder> order) {
            this.order = order;
            return this;
        }

        /**
         * <p>Set <code>true</code> to send signature request via phone number and SMS.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage sendSms(Boolean sendSms) {
            this.sendSms = Optional.ofNullable(sendSms);
            return this;
        }

        /**
         * <p>Set <code>true</code> to send signature request via phone number and SMS.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "send_sms", nulls = Nulls.SKIP)
        public _FinalStage sendSms(Optional<Boolean> sendSms) {
            this.sendSms = sendSms;
            return this;
        }

        /**
         * <p>Set <code>false</code> to disable signature request emails sending.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage sendEmail(Boolean sendEmail) {
            this.sendEmail = Optional.ofNullable(sendEmail);
            return this;
        }

        /**
         * <p>Set <code>false</code> to disable signature request emails sending.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "send_email", nulls = Nulls.SKIP)
        public _FinalStage sendEmail(Optional<Boolean> sendEmail) {
            this.sendEmail = sendEmail;
            return this;
        }

        @java.lang.Override
        public CreateSubmissionParams build() {
            return new CreateSubmissionParams(
                    templateId,
                    sendEmail,
                    sendSms,
                    order,
                    completedRedirectUrl,
                    bccCompleted,
                    replyTo,
                    expireAt,
                    variables,
                    message,
                    submitters,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
