/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.docuseal.requests;

import com.docuseal.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = GetSubmissionDocumentsParams.Builder.class)
public final class GetSubmissionDocumentsParams {
    private final Optional<Boolean> merge;

    private final Map<String, Object> additionalProperties;

    private GetSubmissionDocumentsParams(Optional<Boolean> merge, Map<String, Object> additionalProperties) {
        this.merge = merge;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return When <code>true</code>, merges all documents into a single PDF.
     */
    @JsonProperty("merge")
    public Optional<Boolean> getMerge() {
        return merge;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof GetSubmissionDocumentsParams && equalTo((GetSubmissionDocumentsParams) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(GetSubmissionDocumentsParams other) {
        return merge.equals(other.merge);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.merge);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Boolean> merge = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(GetSubmissionDocumentsParams other) {
            merge(other.getMerge());
            return this;
        }

        /**
         * <p>When <code>true</code>, merges all documents into a single PDF.</p>
         */
        @JsonSetter(value = "merge", nulls = Nulls.SKIP)
        public Builder merge(Optional<Boolean> merge) {
            this.merge = merge;
            return this;
        }

        public Builder merge(Boolean merge) {
            this.merge = Optional.ofNullable(merge);
            return this;
        }

        public GetSubmissionDocumentsParams build() {
            return new GetSubmissionDocumentsParams(merge, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
