/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.docuseal.requests;

import com.docuseal.core.ObjectMappers;
import com.docuseal.types.UpdateSubmitterFieldParams;
import com.docuseal.types.UpdateSubmitterMessageParams;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UpdateSubmitterParams.Builder.class)
public final class UpdateSubmitterParams {
    private final Optional<String> name;

    private final Optional<String> email;

    private final Optional<String> phone;

    private final Optional<Map<String, Object>> values;

    private final Optional<String> externalId;

    private final Optional<Boolean> sendEmail;

    private final Optional<Boolean> sendSms;

    private final Optional<String> replyTo;

    private final Optional<Boolean> completed;

    private final Optional<Map<String, Object>> metadata;

    private final Optional<String> completedRedirectUrl;

    private final Optional<Boolean> requirePhone2Fa;

    private final Optional<Boolean> requireEmail2Fa;

    private final Optional<UpdateSubmitterMessageParams> message;

    private final Optional<List<UpdateSubmitterFieldParams>> fields;

    private final Map<String, Object> additionalProperties;

    private UpdateSubmitterParams(
            Optional<String> name,
            Optional<String> email,
            Optional<String> phone,
            Optional<Map<String, Object>> values,
            Optional<String> externalId,
            Optional<Boolean> sendEmail,
            Optional<Boolean> sendSms,
            Optional<String> replyTo,
            Optional<Boolean> completed,
            Optional<Map<String, Object>> metadata,
            Optional<String> completedRedirectUrl,
            Optional<Boolean> requirePhone2Fa,
            Optional<Boolean> requireEmail2Fa,
            Optional<UpdateSubmitterMessageParams> message,
            Optional<List<UpdateSubmitterFieldParams>> fields,
            Map<String, Object> additionalProperties) {
        this.name = name;
        this.email = email;
        this.phone = phone;
        this.values = values;
        this.externalId = externalId;
        this.sendEmail = sendEmail;
        this.sendSms = sendSms;
        this.replyTo = replyTo;
        this.completed = completed;
        this.metadata = metadata;
        this.completedRedirectUrl = completedRedirectUrl;
        this.requirePhone2Fa = requirePhone2Fa;
        this.requireEmail2Fa = requireEmail2Fa;
        this.message = message;
        this.fields = fields;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The name of the submitter.
     */
    @JsonProperty("name")
    public Optional<String> getName() {
        return name;
    }

    /**
     * @return The email address of the submitter.
     */
    @JsonProperty("email")
    public Optional<String> getEmail() {
        return email;
    }

    /**
     * @return The phone number of the submitter, formatted according to the E.164 standard.
     */
    @JsonProperty("phone")
    public Optional<String> getPhone() {
        return phone;
    }

    /**
     * @return An object with pre-filled values for the submission. Use field names for keys of the object. For more configurations see <code>fields</code> param.
     */
    @JsonProperty("values")
    public Optional<Map<String, Object>> getValues() {
        return values;
    }

    /**
     * @return Your application-specific unique string key to identify this submitter within your app.
     */
    @JsonProperty("external_id")
    public Optional<String> getExternalId() {
        return externalId;
    }

    /**
     * @return Set <code>true</code> to re-send signature request emails.
     */
    @JsonProperty("send_email")
    public Optional<Boolean> getSendEmail() {
        return sendEmail;
    }

    /**
     * @return Set <code>true</code> to re-send signature request via phone number SMS.
     */
    @JsonProperty("send_sms")
    public Optional<Boolean> getSendSms() {
        return sendSms;
    }

    /**
     * @return Specify Reply-To address to use in the notification emails.
     */
    @JsonProperty("reply_to")
    public Optional<String> getReplyTo() {
        return replyTo;
    }

    /**
     * @return Pass <code>true</code> to mark submitter as completed and auto-signed via API.
     */
    @JsonProperty("completed")
    public Optional<Boolean> getCompleted() {
        return completed;
    }

    /**
     * @return Metadata object with additional submitter information.
     */
    @JsonProperty("metadata")
    public Optional<Map<String, Object>> getMetadata() {
        return metadata;
    }

    /**
     * @return Submitter specific URL to redirect to after the submission completion.
     */
    @JsonProperty("completed_redirect_url")
    public Optional<String> getCompletedRedirectUrl() {
        return completedRedirectUrl;
    }

    /**
     * @return Set to <code>true</code> to require phone 2FA verification via a one-time code sent to the phone number in order to access the documents.
     */
    @JsonProperty("require_phone_2fa")
    public Optional<Boolean> getRequirePhone2Fa() {
        return requirePhone2Fa;
    }

    /**
     * @return Set to <code>true</code> to require email 2FA verification via a one-time code sent to the email address in order to access the documents.
     */
    @JsonProperty("require_email_2fa")
    public Optional<Boolean> getRequireEmail2Fa() {
        return requireEmail2Fa;
    }

    @JsonProperty("message")
    public Optional<UpdateSubmitterMessageParams> getMessage() {
        return message;
    }

    /**
     * @return A list of configurations for template document form fields.
     */
    @JsonProperty("fields")
    public Optional<List<UpdateSubmitterFieldParams>> getFields() {
        return fields;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UpdateSubmitterParams && equalTo((UpdateSubmitterParams) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UpdateSubmitterParams other) {
        return name.equals(other.name)
                && email.equals(other.email)
                && phone.equals(other.phone)
                && values.equals(other.values)
                && externalId.equals(other.externalId)
                && sendEmail.equals(other.sendEmail)
                && sendSms.equals(other.sendSms)
                && replyTo.equals(other.replyTo)
                && completed.equals(other.completed)
                && metadata.equals(other.metadata)
                && completedRedirectUrl.equals(other.completedRedirectUrl)
                && requirePhone2Fa.equals(other.requirePhone2Fa)
                && requireEmail2Fa.equals(other.requireEmail2Fa)
                && message.equals(other.message)
                && fields.equals(other.fields);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.name,
                this.email,
                this.phone,
                this.values,
                this.externalId,
                this.sendEmail,
                this.sendSms,
                this.replyTo,
                this.completed,
                this.metadata,
                this.completedRedirectUrl,
                this.requirePhone2Fa,
                this.requireEmail2Fa,
                this.message,
                this.fields);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> name = Optional.empty();

        private Optional<String> email = Optional.empty();

        private Optional<String> phone = Optional.empty();

        private Optional<Map<String, Object>> values = Optional.empty();

        private Optional<String> externalId = Optional.empty();

        private Optional<Boolean> sendEmail = Optional.empty();

        private Optional<Boolean> sendSms = Optional.empty();

        private Optional<String> replyTo = Optional.empty();

        private Optional<Boolean> completed = Optional.empty();

        private Optional<Map<String, Object>> metadata = Optional.empty();

        private Optional<String> completedRedirectUrl = Optional.empty();

        private Optional<Boolean> requirePhone2Fa = Optional.empty();

        private Optional<Boolean> requireEmail2Fa = Optional.empty();

        private Optional<UpdateSubmitterMessageParams> message = Optional.empty();

        private Optional<List<UpdateSubmitterFieldParams>> fields = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(UpdateSubmitterParams other) {
            name(other.getName());
            email(other.getEmail());
            phone(other.getPhone());
            values(other.getValues());
            externalId(other.getExternalId());
            sendEmail(other.getSendEmail());
            sendSms(other.getSendSms());
            replyTo(other.getReplyTo());
            completed(other.getCompleted());
            metadata(other.getMetadata());
            completedRedirectUrl(other.getCompletedRedirectUrl());
            requirePhone2Fa(other.getRequirePhone2Fa());
            requireEmail2Fa(other.getRequireEmail2Fa());
            message(other.getMessage());
            fields(other.getFields());
            return this;
        }

        /**
         * <p>The name of the submitter.</p>
         */
        @JsonSetter(value = "name", nulls = Nulls.SKIP)
        public Builder name(Optional<String> name) {
            this.name = name;
            return this;
        }

        public Builder name(String name) {
            this.name = Optional.ofNullable(name);
            return this;
        }

        /**
         * <p>The email address of the submitter.</p>
         */
        @JsonSetter(value = "email", nulls = Nulls.SKIP)
        public Builder email(Optional<String> email) {
            this.email = email;
            return this;
        }

        public Builder email(String email) {
            this.email = Optional.ofNullable(email);
            return this;
        }

        /**
         * <p>The phone number of the submitter, formatted according to the E.164 standard.</p>
         */
        @JsonSetter(value = "phone", nulls = Nulls.SKIP)
        public Builder phone(Optional<String> phone) {
            this.phone = phone;
            return this;
        }

        public Builder phone(String phone) {
            this.phone = Optional.ofNullable(phone);
            return this;
        }

        /**
         * <p>An object with pre-filled values for the submission. Use field names for keys of the object. For more configurations see <code>fields</code> param.</p>
         */
        @JsonSetter(value = "values", nulls = Nulls.SKIP)
        public Builder values(Optional<Map<String, Object>> values) {
            this.values = values;
            return this;
        }

        public Builder values(Map<String, Object> values) {
            this.values = Optional.ofNullable(values);
            return this;
        }

        /**
         * <p>Your application-specific unique string key to identify this submitter within your app.</p>
         */
        @JsonSetter(value = "external_id", nulls = Nulls.SKIP)
        public Builder externalId(Optional<String> externalId) {
            this.externalId = externalId;
            return this;
        }

        public Builder externalId(String externalId) {
            this.externalId = Optional.ofNullable(externalId);
            return this;
        }

        /**
         * <p>Set <code>true</code> to re-send signature request emails.</p>
         */
        @JsonSetter(value = "send_email", nulls = Nulls.SKIP)
        public Builder sendEmail(Optional<Boolean> sendEmail) {
            this.sendEmail = sendEmail;
            return this;
        }

        public Builder sendEmail(Boolean sendEmail) {
            this.sendEmail = Optional.ofNullable(sendEmail);
            return this;
        }

        /**
         * <p>Set <code>true</code> to re-send signature request via phone number SMS.</p>
         */
        @JsonSetter(value = "send_sms", nulls = Nulls.SKIP)
        public Builder sendSms(Optional<Boolean> sendSms) {
            this.sendSms = sendSms;
            return this;
        }

        public Builder sendSms(Boolean sendSms) {
            this.sendSms = Optional.ofNullable(sendSms);
            return this;
        }

        /**
         * <p>Specify Reply-To address to use in the notification emails.</p>
         */
        @JsonSetter(value = "reply_to", nulls = Nulls.SKIP)
        public Builder replyTo(Optional<String> replyTo) {
            this.replyTo = replyTo;
            return this;
        }

        public Builder replyTo(String replyTo) {
            this.replyTo = Optional.ofNullable(replyTo);
            return this;
        }

        /**
         * <p>Pass <code>true</code> to mark submitter as completed and auto-signed via API.</p>
         */
        @JsonSetter(value = "completed", nulls = Nulls.SKIP)
        public Builder completed(Optional<Boolean> completed) {
            this.completed = completed;
            return this;
        }

        public Builder completed(Boolean completed) {
            this.completed = Optional.ofNullable(completed);
            return this;
        }

        /**
         * <p>Metadata object with additional submitter information.</p>
         */
        @JsonSetter(value = "metadata", nulls = Nulls.SKIP)
        public Builder metadata(Optional<Map<String, Object>> metadata) {
            this.metadata = metadata;
            return this;
        }

        public Builder metadata(Map<String, Object> metadata) {
            this.metadata = Optional.ofNullable(metadata);
            return this;
        }

        /**
         * <p>Submitter specific URL to redirect to after the submission completion.</p>
         */
        @JsonSetter(value = "completed_redirect_url", nulls = Nulls.SKIP)
        public Builder completedRedirectUrl(Optional<String> completedRedirectUrl) {
            this.completedRedirectUrl = completedRedirectUrl;
            return this;
        }

        public Builder completedRedirectUrl(String completedRedirectUrl) {
            this.completedRedirectUrl = Optional.ofNullable(completedRedirectUrl);
            return this;
        }

        /**
         * <p>Set to <code>true</code> to require phone 2FA verification via a one-time code sent to the phone number in order to access the documents.</p>
         */
        @JsonSetter(value = "require_phone_2fa", nulls = Nulls.SKIP)
        public Builder requirePhone2Fa(Optional<Boolean> requirePhone2Fa) {
            this.requirePhone2Fa = requirePhone2Fa;
            return this;
        }

        public Builder requirePhone2Fa(Boolean requirePhone2Fa) {
            this.requirePhone2Fa = Optional.ofNullable(requirePhone2Fa);
            return this;
        }

        /**
         * <p>Set to <code>true</code> to require email 2FA verification via a one-time code sent to the email address in order to access the documents.</p>
         */
        @JsonSetter(value = "require_email_2fa", nulls = Nulls.SKIP)
        public Builder requireEmail2Fa(Optional<Boolean> requireEmail2Fa) {
            this.requireEmail2Fa = requireEmail2Fa;
            return this;
        }

        public Builder requireEmail2Fa(Boolean requireEmail2Fa) {
            this.requireEmail2Fa = Optional.ofNullable(requireEmail2Fa);
            return this;
        }

        @JsonSetter(value = "message", nulls = Nulls.SKIP)
        public Builder message(Optional<UpdateSubmitterMessageParams> message) {
            this.message = message;
            return this;
        }

        public Builder message(UpdateSubmitterMessageParams message) {
            this.message = Optional.ofNullable(message);
            return this;
        }

        /**
         * <p>A list of configurations for template document form fields.</p>
         */
        @JsonSetter(value = "fields", nulls = Nulls.SKIP)
        public Builder fields(Optional<List<UpdateSubmitterFieldParams>> fields) {
            this.fields = fields;
            return this;
        }

        public Builder fields(List<UpdateSubmitterFieldParams> fields) {
            this.fields = Optional.ofNullable(fields);
            return this;
        }

        public UpdateSubmitterParams build() {
            return new UpdateSubmitterParams(
                    name,
                    email,
                    phone,
                    values,
                    externalId,
                    sendEmail,
                    sendSms,
                    replyTo,
                    completed,
                    metadata,
                    completedRedirectUrl,
                    requirePhone2Fa,
                    requireEmail2Fa,
                    message,
                    fields,
                    additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
