/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.docuseal;

import com.docuseal.core.ClientOptions;
import com.docuseal.core.DocusealClientApiException;
import com.docuseal.core.DocusealClientException;
import com.docuseal.core.DocusealClientHttpResponse;
import com.docuseal.core.MediaTypes;
import com.docuseal.core.ObjectMappers;
import com.docuseal.core.QueryStringMapper;
import com.docuseal.core.RequestOptions;
import com.docuseal.requests.AddDocumentToTemplateParams;
import com.docuseal.requests.ArchiveSubmissionParams;
import com.docuseal.requests.ArchiveTemplateParams;
import com.docuseal.requests.CloneTemplateParams;
import com.docuseal.requests.CreateSubmissionFromDocxParams;
import com.docuseal.requests.CreateSubmissionFromHtmlParams;
import com.docuseal.requests.CreateSubmissionFromPdfParams;
import com.docuseal.requests.CreateSubmissionParams;
import com.docuseal.requests.CreateSubmissionsFromEmailsParams;
import com.docuseal.requests.CreateTemplateFromDocxParams;
import com.docuseal.requests.CreateTemplateFromHtmlParams;
import com.docuseal.requests.CreateTemplateFromPdfParams;
import com.docuseal.requests.GetSubmissionDocumentsParams;
import com.docuseal.requests.GetSubmissionParams;
import com.docuseal.requests.GetSubmissionsParams;
import com.docuseal.requests.GetSubmitterParams;
import com.docuseal.requests.GetSubmittersParams;
import com.docuseal.requests.GetTemplateParams;
import com.docuseal.requests.GetTemplatesParams;
import com.docuseal.requests.MergeTemplateParams;
import com.docuseal.requests.UpdateSubmissionParams;
import com.docuseal.requests.UpdateSubmitterParams;
import com.docuseal.requests.UpdateTemplateParams;
import com.docuseal.types.ArchiveSubmissionResponse;
import com.docuseal.types.ArchiveTemplateResponse;
import com.docuseal.types.CreateSubmissionFromPdfResponse;
import com.docuseal.types.CreateSubmissionResponse;
import com.docuseal.types.CreateSubmissionsFromEmailsResponseSubmitter;
import com.docuseal.types.GetSubmissionDocumentsResponse;
import com.docuseal.types.GetSubmissionResponse;
import com.docuseal.types.GetSubmissionsResponse;
import com.docuseal.types.GetSubmitterResponse;
import com.docuseal.types.GetSubmittersResponse;
import com.docuseal.types.GetTemplateResponse;
import com.docuseal.types.GetTemplatesResponse;
import com.docuseal.types.UpdateSubmissionResponse;
import com.docuseal.types.UpdateSubmitterResponse;
import com.docuseal.types.UpdateTemplateResponse;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncRawDocusealClient {
  protected final ClientOptions clientOptions;

  public AsyncRawDocusealClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  /**
   * The API endpoint provides the ability to retrieve a list of available document templates.
   */
  public CompletableFuture<DocusealClientHttpResponse<GetTemplatesResponse>> getTemplates() {
    return getTemplates(GetTemplatesParams.builder().build());
  }

  /**
   * The API endpoint provides the ability to retrieve a list of available document templates.
   */
  public CompletableFuture<DocusealClientHttpResponse<GetTemplatesResponse>> getTemplates(
      GetTemplatesParams request) {
    return getTemplates(request,null);
  }

  /**
   * The API endpoint provides the ability to retrieve a list of available document templates.
   */
  public CompletableFuture<DocusealClientHttpResponse<GetTemplatesResponse>> getTemplates(
      GetTemplatesParams request, RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("templates");if (request.getQ().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "q", request.getQ().get(), false);
      }
      if (request.getSlug().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "slug", request.getSlug().get(), false);
      }
      if (request.getExternalId().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "external_id", request.getExternalId().get(), false);
      }
      if (request.getFolder().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "folder", request.getFolder().get(), false);
      }
      if (request.getArchived().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "archived", request.getArchived().get(), false);
      }
      if (request.getShared().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "shared", request.getShared().get(), false);
      }
      if (request.getLimit().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "limit", request.getLimit().get(), false);
      }
      if (request.getAfter().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "after", request.getAfter().get(), false);
      }
      if (request.getBefore().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "before", request.getBefore().get(), false);
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      CompletableFuture<DocusealClientHttpResponse<GetTemplatesResponse>> future = new CompletableFuture<>();
      client.newCall(okhttpRequest).enqueue(new Callback() {
        @Override
        public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
          try (ResponseBody responseBody = response.body()) {
            if (response.isSuccessful()) {
              future.complete(new DocusealClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), GetTemplatesResponse.class), response));
              return;
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            future.completeExceptionally(new DocusealClientApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
            return;
          }
          catch (IOException e) {
            future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
          }
        }

        @Override
        public void onFailure(@NotNull Call call, @NotNull IOException e) {
          future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
        }
      });
      return future;
    }

    /**
     * The API endpoint provides the functionality to retrieve information about a document template.
     */
    public CompletableFuture<DocusealClientHttpResponse<GetTemplateResponse>> getTemplate(int id) {
      return getTemplate(id,GetTemplateParams.builder().build());
    }

    /**
     * The API endpoint provides the functionality to retrieve information about a document template.
     */
    public CompletableFuture<DocusealClientHttpResponse<GetTemplateResponse>> getTemplate(int id,
        GetTemplateParams request) {
      return getTemplate(id,request,null);
    }

    /**
     * The API endpoint provides the functionality to retrieve information about a document template.
     */
    public CompletableFuture<DocusealClientHttpResponse<GetTemplateResponse>> getTemplate(int id,
        GetTemplateParams request, RequestOptions requestOptions) {
      HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("templates")
        .addPathSegment(Integer.toString(id))
        .build();
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl)
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      CompletableFuture<DocusealClientHttpResponse<GetTemplateResponse>> future = new CompletableFuture<>();
      client.newCall(okhttpRequest).enqueue(new Callback() {
        @Override
        public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
          try (ResponseBody responseBody = response.body()) {
            if (response.isSuccessful()) {
              future.complete(new DocusealClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), GetTemplateResponse.class), response));
              return;
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            future.completeExceptionally(new DocusealClientApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
            return;
          }
          catch (IOException e) {
            future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
          }
        }

        @Override
        public void onFailure(@NotNull Call call, @NotNull IOException e) {
          future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
        }
      });
      return future;
    }

    /**
     * The API endpoint provides the functionality to move a document template to a different folder and update the name of the template.
     */
    public CompletableFuture<DocusealClientHttpResponse<UpdateTemplateResponse>> updateTemplate(
        int id) {
      return updateTemplate(id,UpdateTemplateParams.builder().build());
    }

    /**
     * The API endpoint provides the functionality to move a document template to a different folder and update the name of the template.
     */
    public CompletableFuture<DocusealClientHttpResponse<UpdateTemplateResponse>> updateTemplate(
        int id, UpdateTemplateParams request) {
      return updateTemplate(id,request,null);
    }

    /**
     * The API endpoint provides the functionality to move a document template to a different folder and update the name of the template.
     */
    public CompletableFuture<DocusealClientHttpResponse<UpdateTemplateResponse>> updateTemplate(
        int id, UpdateTemplateParams request, RequestOptions requestOptions) {
      HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("templates")
        .addPathSegment(Integer.toString(id))
        .build();
      RequestBody body;
      try {
        body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
      }
      catch(JsonProcessingException e) {
        throw new DocusealClientException("Failed to serialize request", e);
      }
      Request okhttpRequest = new Request.Builder()
        .url(httpUrl)
        .method("PUT", body)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Content-Type", "application/json")
        .addHeader("Accept", "application/json")
        .build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      CompletableFuture<DocusealClientHttpResponse<UpdateTemplateResponse>> future = new CompletableFuture<>();
      client.newCall(okhttpRequest).enqueue(new Callback() {
        @Override
        public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
          try (ResponseBody responseBody = response.body()) {
            if (response.isSuccessful()) {
              future.complete(new DocusealClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), UpdateTemplateResponse.class), response));
              return;
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            future.completeExceptionally(new DocusealClientApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
            return;
          }
          catch (IOException e) {
            future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
          }
        }

        @Override
        public void onFailure(@NotNull Call call, @NotNull IOException e) {
          future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
        }
      });
      return future;
    }

    /**
     * The API endpoint allows you to archive a document template.
     */
    public CompletableFuture<DocusealClientHttpResponse<ArchiveTemplateResponse>> archiveTemplate(
        int id) {
      return archiveTemplate(id,ArchiveTemplateParams.builder().build());
    }

    /**
     * The API endpoint allows you to archive a document template.
     */
    public CompletableFuture<DocusealClientHttpResponse<ArchiveTemplateResponse>> archiveTemplate(
        int id, ArchiveTemplateParams request) {
      return archiveTemplate(id,request,null);
    }

    /**
     * The API endpoint allows you to archive a document template.
     */
    public CompletableFuture<DocusealClientHttpResponse<ArchiveTemplateResponse>> archiveTemplate(
        int id, ArchiveTemplateParams request, RequestOptions requestOptions) {
      HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("templates")
        .addPathSegment(Integer.toString(id))
        .build();
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl)
        .method("DELETE", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      CompletableFuture<DocusealClientHttpResponse<ArchiveTemplateResponse>> future = new CompletableFuture<>();
      client.newCall(okhttpRequest).enqueue(new Callback() {
        @Override
        public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
          try (ResponseBody responseBody = response.body()) {
            if (response.isSuccessful()) {
              future.complete(new DocusealClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), ArchiveTemplateResponse.class), response));
              return;
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            future.completeExceptionally(new DocusealClientApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
            return;
          }
          catch (IOException e) {
            future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
          }
        }

        @Override
        public void onFailure(@NotNull Call call, @NotNull IOException e) {
          future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
        }
      });
      return future;
    }

    /**
     * The API endpoint provides the ability to retrieve a list of available submissions.
     */
    public CompletableFuture<DocusealClientHttpResponse<GetSubmissionsResponse>> getSubmissions() {
      return getSubmissions(GetSubmissionsParams.builder().build());
    }

    /**
     * The API endpoint provides the ability to retrieve a list of available submissions.
     */
    public CompletableFuture<DocusealClientHttpResponse<GetSubmissionsResponse>> getSubmissions(
        GetSubmissionsParams request) {
      return getSubmissions(request,null);
    }

    /**
     * The API endpoint provides the ability to retrieve a list of available submissions.
     */
    public CompletableFuture<DocusealClientHttpResponse<GetSubmissionsResponse>> getSubmissions(
        GetSubmissionsParams request, RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("submissions");if (request.getTemplateId().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "template_id", request.getTemplateId().get(), false);
        }
        if (request.getStatus().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "status", request.getStatus().get(), false);
        }
        if (request.getQ().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "q", request.getQ().get(), false);
        }
        if (request.getSlug().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "slug", request.getSlug().get(), false);
        }
        if (request.getTemplateFolder().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "template_folder", request.getTemplateFolder().get(), false);
        }
        if (request.getArchived().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "archived", request.getArchived().get(), false);
        }
        if (request.getLimit().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "limit", request.getLimit().get(), false);
        }
        if (request.getAfter().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "after", request.getAfter().get(), false);
        }
        if (request.getBefore().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "before", request.getBefore().get(), false);
        }
        Request.Builder _requestBuilder = new Request.Builder()
          .url(httpUrl.build())
          .method("GET", null)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<DocusealClientHttpResponse<GetSubmissionsResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
          @Override
          public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
            try (ResponseBody responseBody = response.body()) {
              if (response.isSuccessful()) {
                future.complete(new DocusealClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), GetSubmissionsResponse.class), response));
                return;
              }
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              future.completeExceptionally(new DocusealClientApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
              return;
            }
            catch (IOException e) {
              future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
            }
          }

          @Override
          public void onFailure(@NotNull Call call, @NotNull IOException e) {
            future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
          }
        });
        return future;
      }

      /**
       * The API endpoint provides the functionality to retrieve information about a submission.
       */
      public CompletableFuture<DocusealClientHttpResponse<GetSubmissionResponse>> getSubmission(
          int id) {
        return getSubmission(id,GetSubmissionParams.builder().build());
      }

      /**
       * The API endpoint provides the functionality to retrieve information about a submission.
       */
      public CompletableFuture<DocusealClientHttpResponse<GetSubmissionResponse>> getSubmission(
          int id, GetSubmissionParams request) {
        return getSubmission(id,request,null);
      }

      /**
       * The API endpoint provides the functionality to retrieve information about a submission.
       */
      public CompletableFuture<DocusealClientHttpResponse<GetSubmissionResponse>> getSubmission(
          int id, GetSubmissionParams request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

          .addPathSegments("submissions")
          .addPathSegment(Integer.toString(id))
          .build();
        Request.Builder _requestBuilder = new Request.Builder()
          .url(httpUrl)
          .method("GET", null)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<DocusealClientHttpResponse<GetSubmissionResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
          @Override
          public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
            try (ResponseBody responseBody = response.body()) {
              if (response.isSuccessful()) {
                future.complete(new DocusealClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), GetSubmissionResponse.class), response));
                return;
              }
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              future.completeExceptionally(new DocusealClientApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
              return;
            }
            catch (IOException e) {
              future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
            }
          }

          @Override
          public void onFailure(@NotNull Call call, @NotNull IOException e) {
            future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
          }
        });
        return future;
      }

      /**
       * The API endpoint allows you to update a submission: change its name, expiration date, and archive or unarchive it.
       */
      public CompletableFuture<DocusealClientHttpResponse<UpdateSubmissionResponse>> updateSubmission(
          int id) {
        return updateSubmission(id,UpdateSubmissionParams.builder().build());
      }

      /**
       * The API endpoint allows you to update a submission: change its name, expiration date, and archive or unarchive it.
       */
      public CompletableFuture<DocusealClientHttpResponse<UpdateSubmissionResponse>> updateSubmission(
          int id, UpdateSubmissionParams request) {
        return updateSubmission(id,request,null);
      }

      /**
       * The API endpoint allows you to update a submission: change its name, expiration date, and archive or unarchive it.
       */
      public CompletableFuture<DocusealClientHttpResponse<UpdateSubmissionResponse>> updateSubmission(
          int id, UpdateSubmissionParams request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

          .addPathSegments("submissions")
          .addPathSegment(Integer.toString(id))
          .build();
        RequestBody body;
        try {
          body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        }
        catch(JsonProcessingException e) {
          throw new DocusealClientException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
          .url(httpUrl)
          .method("PUT", body)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Content-Type", "application/json")
          .addHeader("Accept", "application/json")
          .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<DocusealClientHttpResponse<UpdateSubmissionResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
          @Override
          public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
            try (ResponseBody responseBody = response.body()) {
              if (response.isSuccessful()) {
                future.complete(new DocusealClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), UpdateSubmissionResponse.class), response));
                return;
              }
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              future.completeExceptionally(new DocusealClientApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
              return;
            }
            catch (IOException e) {
              future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
            }
          }

          @Override
          public void onFailure(@NotNull Call call, @NotNull IOException e) {
            future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
          }
        });
        return future;
      }

      /**
       * The API endpoint allows you to archive a submission.
       */
      public CompletableFuture<DocusealClientHttpResponse<ArchiveSubmissionResponse>> archiveSubmission(
          int id) {
        return archiveSubmission(id,ArchiveSubmissionParams.builder().build());
      }

      /**
       * The API endpoint allows you to archive a submission.
       */
      public CompletableFuture<DocusealClientHttpResponse<ArchiveSubmissionResponse>> archiveSubmission(
          int id, ArchiveSubmissionParams request) {
        return archiveSubmission(id,request,null);
      }

      /**
       * The API endpoint allows you to archive a submission.
       */
      public CompletableFuture<DocusealClientHttpResponse<ArchiveSubmissionResponse>> archiveSubmission(
          int id, ArchiveSubmissionParams request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

          .addPathSegments("submissions")
          .addPathSegment(Integer.toString(id))
          .build();
        Request.Builder _requestBuilder = new Request.Builder()
          .url(httpUrl)
          .method("DELETE", null)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<DocusealClientHttpResponse<ArchiveSubmissionResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
          @Override
          public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
            try (ResponseBody responseBody = response.body()) {
              if (response.isSuccessful()) {
                future.complete(new DocusealClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), ArchiveSubmissionResponse.class), response));
                return;
              }
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              future.completeExceptionally(new DocusealClientApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
              return;
            }
            catch (IOException e) {
              future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
            }
          }

          @Override
          public void onFailure(@NotNull Call call, @NotNull IOException e) {
            future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
          }
        });
        return future;
      }

      /**
       * This endpoint returns a list of partially filled documents for a submission. If the submission has been completed, the final signed documents are returned.
       */
      public CompletableFuture<DocusealClientHttpResponse<GetSubmissionDocumentsResponse>> getSubmissionDocuments(
          int id) {
        return getSubmissionDocuments(id,GetSubmissionDocumentsParams.builder().build());
      }

      /**
       * This endpoint returns a list of partially filled documents for a submission. If the submission has been completed, the final signed documents are returned.
       */
      public CompletableFuture<DocusealClientHttpResponse<GetSubmissionDocumentsResponse>> getSubmissionDocuments(
          int id, GetSubmissionDocumentsParams request) {
        return getSubmissionDocuments(id,request,null);
      }

      /**
       * This endpoint returns a list of partially filled documents for a submission. If the submission has been completed, the final signed documents are returned.
       */
      public CompletableFuture<DocusealClientHttpResponse<GetSubmissionDocumentsResponse>> getSubmissionDocuments(
          int id, GetSubmissionDocumentsParams request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

          .addPathSegments("submissions")
          .addPathSegment(Integer.toString(id))
          .addPathSegments("documents");if (request.getMerge().isPresent()) {
            QueryStringMapper.addQueryParameter(httpUrl, "merge", request.getMerge().get(), false);
          }
          Request.Builder _requestBuilder = new Request.Builder()
            .url(httpUrl.build())
            .method("GET", null)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Accept", "application/json");
          Request okhttpRequest = _requestBuilder.build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          CompletableFuture<DocusealClientHttpResponse<GetSubmissionDocumentsResponse>> future = new CompletableFuture<>();
          client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
              try (ResponseBody responseBody = response.body()) {
                if (response.isSuccessful()) {
                  future.complete(new DocusealClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), GetSubmissionDocumentsResponse.class), response));
                  return;
                }
                String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                future.completeExceptionally(new DocusealClientApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                return;
              }
              catch (IOException e) {
                future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
              }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
              future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
            }
          });
          return future;
        }

        /**
         * This API endpoint allows you to create submissions for a document template and send them to the specified email addresses. This is a simplified version of the POST /submissions API to be used with Zapier or other automation tools.
         */
        public CompletableFuture<DocusealClientHttpResponse<List<CreateSubmissionsFromEmailsResponseSubmitter>>> createSubmissionsFromEmails(
            CreateSubmissionsFromEmailsParams request) {
          return createSubmissionsFromEmails(request,null);
        }

        /**
         * This API endpoint allows you to create submissions for a document template and send them to the specified email addresses. This is a simplified version of the POST /submissions API to be used with Zapier or other automation tools.
         */
        public CompletableFuture<DocusealClientHttpResponse<List<CreateSubmissionsFromEmailsResponseSubmitter>>> createSubmissionsFromEmails(
            CreateSubmissionsFromEmailsParams request, RequestOptions requestOptions) {
          HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

            .addPathSegments("submissions/emails")
            .build();
          RequestBody body;
          try {
            body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
          }
          catch(JsonProcessingException e) {
            throw new DocusealClientException("Failed to serialize request", e);
          }
          Request okhttpRequest = new Request.Builder()
            .url(httpUrl)
            .method("POST", body)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Content-Type", "application/json")
            .addHeader("Accept", "application/json")
            .build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          CompletableFuture<DocusealClientHttpResponse<List<CreateSubmissionsFromEmailsResponseSubmitter>>> future = new CompletableFuture<>();
          client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
              try (ResponseBody responseBody = response.body()) {
                if (response.isSuccessful()) {
                  future.complete(new DocusealClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), new TypeReference<List<CreateSubmissionsFromEmailsResponseSubmitter>>() {}), response));
                  return;
                }
                String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                future.completeExceptionally(new DocusealClientApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                return;
              }
              catch (IOException e) {
                future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
              }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
              future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
            }
          });
          return future;
        }

        /**
         * The API endpoint provides the functionality to create one-off submission request from a PDF. Use &lt;code&gt;{{Field Name;role=Signer1;type=date}}&lt;/code&gt; text tags to define fillable fields in the document. See &lt;a href=&quot;https://www.docuseal.com/examples/fieldtags.pdf&quot; target=&quot;_blank&quot; class=&quot;link font-bold&quot;&gt;https://www.docuseal.com/examples/fieldtags.pdf&lt;/a&gt; for more text tag formats. Or specify the exact pixel coordinates of the document fields using <code>fields</code> param.&lt;br&gt;&lt;b&gt;Related Guides&lt;/b&gt;&lt;br&gt;&lt;a href=&quot;https://www.docuseal.com/guides/use-embedded-text-field-tags-in-the-pdf-to-create-a-fillable-form&quot; class=&quot;link&quot;&gt;Use embedded text field tags to create a fillable form&lt;/a&gt;
         */
        public CompletableFuture<DocusealClientHttpResponse<CreateSubmissionFromPdfResponse>> createSubmissionFromPdf(
            CreateSubmissionFromPdfParams request) {
          return createSubmissionFromPdf(request,null);
        }

        /**
         * The API endpoint provides the functionality to create one-off submission request from a PDF. Use &lt;code&gt;{{Field Name;role=Signer1;type=date}}&lt;/code&gt; text tags to define fillable fields in the document. See &lt;a href=&quot;https://www.docuseal.com/examples/fieldtags.pdf&quot; target=&quot;_blank&quot; class=&quot;link font-bold&quot;&gt;https://www.docuseal.com/examples/fieldtags.pdf&lt;/a&gt; for more text tag formats. Or specify the exact pixel coordinates of the document fields using <code>fields</code> param.&lt;br&gt;&lt;b&gt;Related Guides&lt;/b&gt;&lt;br&gt;&lt;a href=&quot;https://www.docuseal.com/guides/use-embedded-text-field-tags-in-the-pdf-to-create-a-fillable-form&quot; class=&quot;link&quot;&gt;Use embedded text field tags to create a fillable form&lt;/a&gt;
         */
        public CompletableFuture<DocusealClientHttpResponse<CreateSubmissionFromPdfResponse>> createSubmissionFromPdf(
            CreateSubmissionFromPdfParams request, RequestOptions requestOptions) {
          HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

            .addPathSegments("submissions/pdf")
            .build();
          RequestBody body;
          try {
            body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
          }
          catch(JsonProcessingException e) {
            throw new DocusealClientException("Failed to serialize request", e);
          }
          Request okhttpRequest = new Request.Builder()
            .url(httpUrl)
            .method("POST", body)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Content-Type", "application/json")
            .addHeader("Accept", "application/json")
            .build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          CompletableFuture<DocusealClientHttpResponse<CreateSubmissionFromPdfResponse>> future = new CompletableFuture<>();
          client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
              try (ResponseBody responseBody = response.body()) {
                if (response.isSuccessful()) {
                  future.complete(new DocusealClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), CreateSubmissionFromPdfResponse.class), response));
                  return;
                }
                String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                future.completeExceptionally(new DocusealClientApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                return;
              }
              catch (IOException e) {
                future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
              }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
              future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
            }
          });
          return future;
        }

        /**
         * The API endpoint provides functionality to create a one-off submission request from a DOCX file with dynamic content variables. Use &lt;code&gt;[[variable_name]]&lt;/code&gt; text tags to define dynamic content variables in the document. See &lt;a href=&quot;https://www.docuseal.com/examples/demo_template.docx&quot; target=&quot;_blank&quot; class=&quot;link font-bold&quot;&gt;https://www.docuseal.com/examples/demo_template.docx&lt;/a&gt; for the specific text variable syntax, including dynamic content tables and lists. You can also use the &lt;code&gt;{{signature}}&lt;/code&gt; field syntax to define fillable fields, as in a PDF.&lt;br&gt;&lt;b&gt;Related Guides&lt;/b&gt;&lt;br&gt;&lt;a href=&quot;https://www.docuseal.com/guides/use-dynamic-content-variables-in-docx-to-create-personalized-documents&quot; class=&quot;link&quot;&gt;Use dynamic content variables in DOCX to create personalized documents&lt;/a&gt;
         */
        public CompletableFuture<DocusealClientHttpResponse<CreateSubmissionFromPdfResponse>> createSubmissionFromDocx(
            CreateSubmissionFromDocxParams request) {
          return createSubmissionFromDocx(request,null);
        }

        /**
         * The API endpoint provides functionality to create a one-off submission request from a DOCX file with dynamic content variables. Use &lt;code&gt;[[variable_name]]&lt;/code&gt; text tags to define dynamic content variables in the document. See &lt;a href=&quot;https://www.docuseal.com/examples/demo_template.docx&quot; target=&quot;_blank&quot; class=&quot;link font-bold&quot;&gt;https://www.docuseal.com/examples/demo_template.docx&lt;/a&gt; for the specific text variable syntax, including dynamic content tables and lists. You can also use the &lt;code&gt;{{signature}}&lt;/code&gt; field syntax to define fillable fields, as in a PDF.&lt;br&gt;&lt;b&gt;Related Guides&lt;/b&gt;&lt;br&gt;&lt;a href=&quot;https://www.docuseal.com/guides/use-dynamic-content-variables-in-docx-to-create-personalized-documents&quot; class=&quot;link&quot;&gt;Use dynamic content variables in DOCX to create personalized documents&lt;/a&gt;
         */
        public CompletableFuture<DocusealClientHttpResponse<CreateSubmissionFromPdfResponse>> createSubmissionFromDocx(
            CreateSubmissionFromDocxParams request, RequestOptions requestOptions) {
          HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

            .addPathSegments("submissions/docx")
            .build();
          RequestBody body;
          try {
            body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
          }
          catch(JsonProcessingException e) {
            throw new DocusealClientException("Failed to serialize request", e);
          }
          Request okhttpRequest = new Request.Builder()
            .url(httpUrl)
            .method("POST", body)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Content-Type", "application/json")
            .addHeader("Accept", "application/json")
            .build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          CompletableFuture<DocusealClientHttpResponse<CreateSubmissionFromPdfResponse>> future = new CompletableFuture<>();
          client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
              try (ResponseBody responseBody = response.body()) {
                if (response.isSuccessful()) {
                  future.complete(new DocusealClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), CreateSubmissionFromPdfResponse.class), response));
                  return;
                }
                String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                future.completeExceptionally(new DocusealClientApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                return;
              }
              catch (IOException e) {
                future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
              }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
              future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
            }
          });
          return future;
        }

        /**
         * This API endpoint allows you to create a one-off submission request document using the provided HTML content, with special field tags rendered as a fillable and signable form.&lt;br&gt;&lt;b&gt;Related Guides&lt;/b&gt;&lt;br&gt;&lt;a href=&quot;https://www.docuseal.com/guides/create-pdf-document-fillable-form-with-html-api&quot; class=&quot;link&quot;&gt;Create PDF document fillable form with HTML&lt;/a&gt;
         */
        public CompletableFuture<DocusealClientHttpResponse<CreateSubmissionFromPdfResponse>> createSubmissionFromHtml(
            CreateSubmissionFromHtmlParams request) {
          return createSubmissionFromHtml(request,null);
        }

        /**
         * This API endpoint allows you to create a one-off submission request document using the provided HTML content, with special field tags rendered as a fillable and signable form.&lt;br&gt;&lt;b&gt;Related Guides&lt;/b&gt;&lt;br&gt;&lt;a href=&quot;https://www.docuseal.com/guides/create-pdf-document-fillable-form-with-html-api&quot; class=&quot;link&quot;&gt;Create PDF document fillable form with HTML&lt;/a&gt;
         */
        public CompletableFuture<DocusealClientHttpResponse<CreateSubmissionFromPdfResponse>> createSubmissionFromHtml(
            CreateSubmissionFromHtmlParams request, RequestOptions requestOptions) {
          HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

            .addPathSegments("submissions/html")
            .build();
          RequestBody body;
          try {
            body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
          }
          catch(JsonProcessingException e) {
            throw new DocusealClientException("Failed to serialize request", e);
          }
          Request okhttpRequest = new Request.Builder()
            .url(httpUrl)
            .method("POST", body)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Content-Type", "application/json")
            .addHeader("Accept", "application/json")
            .build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          CompletableFuture<DocusealClientHttpResponse<CreateSubmissionFromPdfResponse>> future = new CompletableFuture<>();
          client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
              try (ResponseBody responseBody = response.body()) {
                if (response.isSuccessful()) {
                  future.complete(new DocusealClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), CreateSubmissionFromPdfResponse.class), response));
                  return;
                }
                String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                future.completeExceptionally(new DocusealClientApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                return;
              }
              catch (IOException e) {
                future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
              }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
              future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
            }
          });
          return future;
        }

        /**
         * The API endpoint provides functionality to retrieve information about a submitter, along with the submitter documents and field values.
         */
        public CompletableFuture<DocusealClientHttpResponse<GetSubmitterResponse>> getSubmitter(
            int id) {
          return getSubmitter(id,GetSubmitterParams.builder().build());
        }

        /**
         * The API endpoint provides functionality to retrieve information about a submitter, along with the submitter documents and field values.
         */
        public CompletableFuture<DocusealClientHttpResponse<GetSubmitterResponse>> getSubmitter(
            int id, GetSubmitterParams request) {
          return getSubmitter(id,request,null);
        }

        /**
         * The API endpoint provides functionality to retrieve information about a submitter, along with the submitter documents and field values.
         */
        public CompletableFuture<DocusealClientHttpResponse<GetSubmitterResponse>> getSubmitter(
            int id, GetSubmitterParams request, RequestOptions requestOptions) {
          HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

            .addPathSegments("submitters")
            .addPathSegment(Integer.toString(id))
            .build();
          Request.Builder _requestBuilder = new Request.Builder()
            .url(httpUrl)
            .method("GET", null)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Accept", "application/json");
          Request okhttpRequest = _requestBuilder.build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          CompletableFuture<DocusealClientHttpResponse<GetSubmitterResponse>> future = new CompletableFuture<>();
          client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
              try (ResponseBody responseBody = response.body()) {
                if (response.isSuccessful()) {
                  future.complete(new DocusealClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), GetSubmitterResponse.class), response));
                  return;
                }
                String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                future.completeExceptionally(new DocusealClientApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                return;
              }
              catch (IOException e) {
                future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
              }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
              future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
            }
          });
          return future;
        }

        /**
         * The API endpoint allows you to update submitter details, pre-fill or update field values and re-send emails.&lt;br&gt;&lt;b&gt;Related Guides&lt;/b&gt;&lt;br&gt;&lt;a href=&quot;https://www.docuseal.com/guides/pre-fill-pdf-document-form-fields-with-api#automatically_sign_documents_via_api&quot; class=&quot;link&quot;&gt;Automatically sign documents via API&lt;/a&gt;
         */
        public CompletableFuture<DocusealClientHttpResponse<UpdateSubmitterResponse>> updateSubmitter(
            int id) {
          return updateSubmitter(id,UpdateSubmitterParams.builder().build());
        }

        /**
         * The API endpoint allows you to update submitter details, pre-fill or update field values and re-send emails.&lt;br&gt;&lt;b&gt;Related Guides&lt;/b&gt;&lt;br&gt;&lt;a href=&quot;https://www.docuseal.com/guides/pre-fill-pdf-document-form-fields-with-api#automatically_sign_documents_via_api&quot; class=&quot;link&quot;&gt;Automatically sign documents via API&lt;/a&gt;
         */
        public CompletableFuture<DocusealClientHttpResponse<UpdateSubmitterResponse>> updateSubmitter(
            int id, UpdateSubmitterParams request) {
          return updateSubmitter(id,request,null);
        }

        /**
         * The API endpoint allows you to update submitter details, pre-fill or update field values and re-send emails.&lt;br&gt;&lt;b&gt;Related Guides&lt;/b&gt;&lt;br&gt;&lt;a href=&quot;https://www.docuseal.com/guides/pre-fill-pdf-document-form-fields-with-api#automatically_sign_documents_via_api&quot; class=&quot;link&quot;&gt;Automatically sign documents via API&lt;/a&gt;
         */
        public CompletableFuture<DocusealClientHttpResponse<UpdateSubmitterResponse>> updateSubmitter(
            int id, UpdateSubmitterParams request, RequestOptions requestOptions) {
          HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

            .addPathSegments("submitters")
            .addPathSegment(Integer.toString(id))
            .build();
          RequestBody body;
          try {
            body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
          }
          catch(JsonProcessingException e) {
            throw new DocusealClientException("Failed to serialize request", e);
          }
          Request okhttpRequest = new Request.Builder()
            .url(httpUrl)
            .method("PUT", body)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Content-Type", "application/json")
            .addHeader("Accept", "application/json")
            .build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          CompletableFuture<DocusealClientHttpResponse<UpdateSubmitterResponse>> future = new CompletableFuture<>();
          client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
              try (ResponseBody responseBody = response.body()) {
                if (response.isSuccessful()) {
                  future.complete(new DocusealClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), UpdateSubmitterResponse.class), response));
                  return;
                }
                String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                future.completeExceptionally(new DocusealClientApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                return;
              }
              catch (IOException e) {
                future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
              }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
              future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
            }
          });
          return future;
        }

        /**
         * The API endpoint provides the ability to retrieve a list of submitters.
         */
        public CompletableFuture<DocusealClientHttpResponse<GetSubmittersResponse>> getSubmitters(
            ) {
          return getSubmitters(GetSubmittersParams.builder().build());
        }

        /**
         * The API endpoint provides the ability to retrieve a list of submitters.
         */
        public CompletableFuture<DocusealClientHttpResponse<GetSubmittersResponse>> getSubmitters(
            GetSubmittersParams request) {
          return getSubmitters(request,null);
        }

        /**
         * The API endpoint provides the ability to retrieve a list of submitters.
         */
        public CompletableFuture<DocusealClientHttpResponse<GetSubmittersResponse>> getSubmitters(
            GetSubmittersParams request, RequestOptions requestOptions) {
          HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

            .addPathSegments("submitters");if (request.getSubmissionId().isPresent()) {
              QueryStringMapper.addQueryParameter(httpUrl, "submission_id", request.getSubmissionId().get(), false);
            }
            if (request.getQ().isPresent()) {
              QueryStringMapper.addQueryParameter(httpUrl, "q", request.getQ().get(), false);
            }
            if (request.getSlug().isPresent()) {
              QueryStringMapper.addQueryParameter(httpUrl, "slug", request.getSlug().get(), false);
            }
            if (request.getCompletedAfter().isPresent()) {
              QueryStringMapper.addQueryParameter(httpUrl, "completed_after", request.getCompletedAfter().get(), false);
            }
            if (request.getCompletedBefore().isPresent()) {
              QueryStringMapper.addQueryParameter(httpUrl, "completed_before", request.getCompletedBefore().get(), false);
            }
            if (request.getExternalId().isPresent()) {
              QueryStringMapper.addQueryParameter(httpUrl, "external_id", request.getExternalId().get(), false);
            }
            if (request.getLimit().isPresent()) {
              QueryStringMapper.addQueryParameter(httpUrl, "limit", request.getLimit().get(), false);
            }
            if (request.getAfter().isPresent()) {
              QueryStringMapper.addQueryParameter(httpUrl, "after", request.getAfter().get(), false);
            }
            if (request.getBefore().isPresent()) {
              QueryStringMapper.addQueryParameter(httpUrl, "before", request.getBefore().get(), false);
            }
            Request.Builder _requestBuilder = new Request.Builder()
              .url(httpUrl.build())
              .method("GET", null)
              .headers(Headers.of(clientOptions.headers(requestOptions)))
              .addHeader("Accept", "application/json");
            Request okhttpRequest = _requestBuilder.build();
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
              client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            CompletableFuture<DocusealClientHttpResponse<GetSubmittersResponse>> future = new CompletableFuture<>();
            client.newCall(okhttpRequest).enqueue(new Callback() {
              @Override
              public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                  if (response.isSuccessful()) {
                    future.complete(new DocusealClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), GetSubmittersResponse.class), response));
                    return;
                  }
                  String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                  future.completeExceptionally(new DocusealClientApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                  return;
                }
                catch (IOException e) {
                  future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
                }
              }

              @Override
              public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
              }
            });
            return future;
          }

          /**
           * The API endpoint allows you to add, remove or replace documents in the template with provided PDF/DOCX file or HTML content.
           */
          public CompletableFuture<DocusealClientHttpResponse<GetTemplateResponse>> addDocumentToTemplate(
              int id) {
            return addDocumentToTemplate(id,AddDocumentToTemplateParams.builder().build());
          }

          /**
           * The API endpoint allows you to add, remove or replace documents in the template with provided PDF/DOCX file or HTML content.
           */
          public CompletableFuture<DocusealClientHttpResponse<GetTemplateResponse>> addDocumentToTemplate(
              int id, AddDocumentToTemplateParams request) {
            return addDocumentToTemplate(id,request,null);
          }

          /**
           * The API endpoint allows you to add, remove or replace documents in the template with provided PDF/DOCX file or HTML content.
           */
          public CompletableFuture<DocusealClientHttpResponse<GetTemplateResponse>> addDocumentToTemplate(
              int id, AddDocumentToTemplateParams request, RequestOptions requestOptions) {
            HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

              .addPathSegments("templates")
              .addPathSegment(Integer.toString(id))
              .addPathSegments("documents")
              .build();
            RequestBody body;
            try {
              body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
            }
            catch(JsonProcessingException e) {
              throw new DocusealClientException("Failed to serialize request", e);
            }
            Request okhttpRequest = new Request.Builder()
              .url(httpUrl)
              .method("PUT", body)
              .headers(Headers.of(clientOptions.headers(requestOptions)))
              .addHeader("Content-Type", "application/json")
              .addHeader("Accept", "application/json")
              .build();
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
              client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            CompletableFuture<DocusealClientHttpResponse<GetTemplateResponse>> future = new CompletableFuture<>();
            client.newCall(okhttpRequest).enqueue(new Callback() {
              @Override
              public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                  if (response.isSuccessful()) {
                    future.complete(new DocusealClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), GetTemplateResponse.class), response));
                    return;
                  }
                  String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                  future.completeExceptionally(new DocusealClientApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                  return;
                }
                catch (IOException e) {
                  future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
                }
              }

              @Override
              public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
              }
            });
            return future;
          }

          /**
           * The API endpoint allows you to clone an existing template into a new template.
           */
          public CompletableFuture<DocusealClientHttpResponse<GetTemplateResponse>> cloneTemplate(
              int id) {
            return cloneTemplate(id,CloneTemplateParams.builder().build());
          }

          /**
           * The API endpoint allows you to clone an existing template into a new template.
           */
          public CompletableFuture<DocusealClientHttpResponse<GetTemplateResponse>> cloneTemplate(
              int id, CloneTemplateParams request) {
            return cloneTemplate(id,request,null);
          }

          /**
           * The API endpoint allows you to clone an existing template into a new template.
           */
          public CompletableFuture<DocusealClientHttpResponse<GetTemplateResponse>> cloneTemplate(
              int id, CloneTemplateParams request, RequestOptions requestOptions) {
            HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

              .addPathSegments("templates")
              .addPathSegment(Integer.toString(id))
              .addPathSegments("clone")
              .build();
            RequestBody body;
            try {
              body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
            }
            catch(JsonProcessingException e) {
              throw new DocusealClientException("Failed to serialize request", e);
            }
            Request okhttpRequest = new Request.Builder()
              .url(httpUrl)
              .method("POST", body)
              .headers(Headers.of(clientOptions.headers(requestOptions)))
              .addHeader("Content-Type", "application/json")
              .addHeader("Accept", "application/json")
              .build();
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
              client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            CompletableFuture<DocusealClientHttpResponse<GetTemplateResponse>> future = new CompletableFuture<>();
            client.newCall(okhttpRequest).enqueue(new Callback() {
              @Override
              public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                  if (response.isSuccessful()) {
                    future.complete(new DocusealClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), GetTemplateResponse.class), response));
                    return;
                  }
                  String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                  future.completeExceptionally(new DocusealClientApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                  return;
                }
                catch (IOException e) {
                  future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
                }
              }

              @Override
              public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
              }
            });
            return future;
          }

          /**
           * The API endpoint provides the functionality to seamlessly generate a PDF document template by utilizing the provided HTML content while incorporating pre-defined fields.&lt;br&gt;&lt;b&gt;Related Guides&lt;/b&gt;&lt;br&gt;&lt;a href=&quot;https://www.docuseal.com/guides/create-pdf-document-fillable-form-with-html-api&quot; class=&quot;link&quot;&gt;Create PDF document fillable form with HTML&lt;/a&gt;
           */
          public CompletableFuture<DocusealClientHttpResponse<GetTemplateResponse>> createTemplateFromHtml(
              CreateTemplateFromHtmlParams request) {
            return createTemplateFromHtml(request,null);
          }

          /**
           * The API endpoint provides the functionality to seamlessly generate a PDF document template by utilizing the provided HTML content while incorporating pre-defined fields.&lt;br&gt;&lt;b&gt;Related Guides&lt;/b&gt;&lt;br&gt;&lt;a href=&quot;https://www.docuseal.com/guides/create-pdf-document-fillable-form-with-html-api&quot; class=&quot;link&quot;&gt;Create PDF document fillable form with HTML&lt;/a&gt;
           */
          public CompletableFuture<DocusealClientHttpResponse<GetTemplateResponse>> createTemplateFromHtml(
              CreateTemplateFromHtmlParams request, RequestOptions requestOptions) {
            HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

              .addPathSegments("templates/html")
              .build();
            RequestBody body;
            try {
              body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
            }
            catch(JsonProcessingException e) {
              throw new DocusealClientException("Failed to serialize request", e);
            }
            Request okhttpRequest = new Request.Builder()
              .url(httpUrl)
              .method("POST", body)
              .headers(Headers.of(clientOptions.headers(requestOptions)))
              .addHeader("Content-Type", "application/json")
              .addHeader("Accept", "application/json")
              .build();
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
              client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            CompletableFuture<DocusealClientHttpResponse<GetTemplateResponse>> future = new CompletableFuture<>();
            client.newCall(okhttpRequest).enqueue(new Callback() {
              @Override
              public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                  if (response.isSuccessful()) {
                    future.complete(new DocusealClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), GetTemplateResponse.class), response));
                    return;
                  }
                  String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                  future.completeExceptionally(new DocusealClientApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                  return;
                }
                catch (IOException e) {
                  future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
                }
              }

              @Override
              public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
              }
            });
            return future;
          }

          /**
           * The API endpoint provides the functionality to create a fillable document template for an existing Microsoft Word document. Use &lt;code&gt;{{Field Name;role=Signer1;type=date}}&lt;/code&gt; text tags to define fillable fields in the document. See &lt;a href=&quot;https://www.docuseal.com/examples/fieldtags.docx&quot; target=&quot;_blank&quot; class=&quot;link font-bold&quot; &gt;https://www.docuseal.com/examples/fieldtags.docx&lt;/a&gt; for more text tag formats. Or specify the exact pixel coordinates of the document fields using <code>fields</code> param.&lt;br&gt;&lt;b&gt;Related Guides&lt;/b&gt;&lt;br&gt;&lt;a href=&quot;https://www.docuseal.com/guides/use-embedded-text-field-tags-in-the-pdf-to-create-a-fillable-form&quot; class=&quot;link&quot;&gt;Use embedded text field tags to create a fillable form&lt;/a&gt;
           */
          public CompletableFuture<DocusealClientHttpResponse<GetTemplateResponse>> createTemplateFromDocx(
              CreateTemplateFromDocxParams request) {
            return createTemplateFromDocx(request,null);
          }

          /**
           * The API endpoint provides the functionality to create a fillable document template for an existing Microsoft Word document. Use &lt;code&gt;{{Field Name;role=Signer1;type=date}}&lt;/code&gt; text tags to define fillable fields in the document. See &lt;a href=&quot;https://www.docuseal.com/examples/fieldtags.docx&quot; target=&quot;_blank&quot; class=&quot;link font-bold&quot; &gt;https://www.docuseal.com/examples/fieldtags.docx&lt;/a&gt; for more text tag formats. Or specify the exact pixel coordinates of the document fields using <code>fields</code> param.&lt;br&gt;&lt;b&gt;Related Guides&lt;/b&gt;&lt;br&gt;&lt;a href=&quot;https://www.docuseal.com/guides/use-embedded-text-field-tags-in-the-pdf-to-create-a-fillable-form&quot; class=&quot;link&quot;&gt;Use embedded text field tags to create a fillable form&lt;/a&gt;
           */
          public CompletableFuture<DocusealClientHttpResponse<GetTemplateResponse>> createTemplateFromDocx(
              CreateTemplateFromDocxParams request, RequestOptions requestOptions) {
            HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

              .addPathSegments("templates/docx")
              .build();
            RequestBody body;
            try {
              body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
            }
            catch(JsonProcessingException e) {
              throw new DocusealClientException("Failed to serialize request", e);
            }
            Request okhttpRequest = new Request.Builder()
              .url(httpUrl)
              .method("POST", body)
              .headers(Headers.of(clientOptions.headers(requestOptions)))
              .addHeader("Content-Type", "application/json")
              .addHeader("Accept", "application/json")
              .build();
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
              client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            CompletableFuture<DocusealClientHttpResponse<GetTemplateResponse>> future = new CompletableFuture<>();
            client.newCall(okhttpRequest).enqueue(new Callback() {
              @Override
              public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                  if (response.isSuccessful()) {
                    future.complete(new DocusealClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), GetTemplateResponse.class), response));
                    return;
                  }
                  String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                  future.completeExceptionally(new DocusealClientApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                  return;
                }
                catch (IOException e) {
                  future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
                }
              }

              @Override
              public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
              }
            });
            return future;
          }

          /**
           * The API endpoint provides the functionality to create a fillable document template for a PDF file. Use &lt;code&gt;{{Field Name;role=Signer1;type=date}}&lt;/code&gt; text tags to define fillable fields in the document. See &lt;a href=&quot;https://www.docuseal.com/examples/fieldtags.pdf&quot; target=&quot;_blank&quot; class=&quot;link font-bold&quot;&gt;https://www.docuseal.com/examples/fieldtags.pdf&lt;/a&gt; for more text tag formats. Or specify the exact pixel coordinates of the document fields using <code>fields</code> param.&lt;br&gt;&lt;b&gt;Related Guides&lt;/b&gt;&lt;br&gt;&lt;a href=&quot;https://www.docuseal.com/guides/use-embedded-text-field-tags-in-the-pdf-to-create-a-fillable-form&quot; class=&quot;link&quot;&gt;Use embedded text field tags to create a fillable form&lt;/a&gt;
           */
          public CompletableFuture<DocusealClientHttpResponse<GetTemplateResponse>> createTemplateFromPdf(
              CreateTemplateFromPdfParams request) {
            return createTemplateFromPdf(request,null);
          }

          /**
           * The API endpoint provides the functionality to create a fillable document template for a PDF file. Use &lt;code&gt;{{Field Name;role=Signer1;type=date}}&lt;/code&gt; text tags to define fillable fields in the document. See &lt;a href=&quot;https://www.docuseal.com/examples/fieldtags.pdf&quot; target=&quot;_blank&quot; class=&quot;link font-bold&quot;&gt;https://www.docuseal.com/examples/fieldtags.pdf&lt;/a&gt; for more text tag formats. Or specify the exact pixel coordinates of the document fields using <code>fields</code> param.&lt;br&gt;&lt;b&gt;Related Guides&lt;/b&gt;&lt;br&gt;&lt;a href=&quot;https://www.docuseal.com/guides/use-embedded-text-field-tags-in-the-pdf-to-create-a-fillable-form&quot; class=&quot;link&quot;&gt;Use embedded text field tags to create a fillable form&lt;/a&gt;
           */
          public CompletableFuture<DocusealClientHttpResponse<GetTemplateResponse>> createTemplateFromPdf(
              CreateTemplateFromPdfParams request, RequestOptions requestOptions) {
            HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

              .addPathSegments("templates/pdf")
              .build();
            RequestBody body;
            try {
              body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
            }
            catch(JsonProcessingException e) {
              throw new DocusealClientException("Failed to serialize request", e);
            }
            Request okhttpRequest = new Request.Builder()
              .url(httpUrl)
              .method("POST", body)
              .headers(Headers.of(clientOptions.headers(requestOptions)))
              .addHeader("Content-Type", "application/json")
              .addHeader("Accept", "application/json")
              .build();
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
              client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            CompletableFuture<DocusealClientHttpResponse<GetTemplateResponse>> future = new CompletableFuture<>();
            client.newCall(okhttpRequest).enqueue(new Callback() {
              @Override
              public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                  if (response.isSuccessful()) {
                    future.complete(new DocusealClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), GetTemplateResponse.class), response));
                    return;
                  }
                  String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                  future.completeExceptionally(new DocusealClientApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                  return;
                }
                catch (IOException e) {
                  future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
                }
              }

              @Override
              public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
              }
            });
            return future;
          }

          /**
           * The API endpoint allows you to merge multiple templates with documents and fields into a new combined template.
           */
          public CompletableFuture<DocusealClientHttpResponse<GetTemplateResponse>> mergeTemplate(
              MergeTemplateParams request) {
            return mergeTemplate(request,null);
          }

          /**
           * The API endpoint allows you to merge multiple templates with documents and fields into a new combined template.
           */
          public CompletableFuture<DocusealClientHttpResponse<GetTemplateResponse>> mergeTemplate(
              MergeTemplateParams request, RequestOptions requestOptions) {
            HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

              .addPathSegments("templates/merge")
              .build();
            RequestBody body;
            try {
              body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
            }
            catch(JsonProcessingException e) {
              throw new DocusealClientException("Failed to serialize request", e);
            }
            Request okhttpRequest = new Request.Builder()
              .url(httpUrl)
              .method("POST", body)
              .headers(Headers.of(clientOptions.headers(requestOptions)))
              .addHeader("Content-Type", "application/json")
              .addHeader("Accept", "application/json")
              .build();
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
              client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            CompletableFuture<DocusealClientHttpResponse<GetTemplateResponse>> future = new CompletableFuture<>();
            client.newCall(okhttpRequest).enqueue(new Callback() {
              @Override
              public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                  if (response.isSuccessful()) {
                    future.complete(new DocusealClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), GetTemplateResponse.class), response));
                    return;
                  }
                  String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                  future.completeExceptionally(new DocusealClientApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                  return;
                }
                catch (IOException e) {
                  future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
                }
              }

              @Override
              public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
              }
            });
            return future;
          }

          /**
           * This API endpoint allows you to create signature requests (submissions) for a document template and send them to the specified submitters (signers).&lt;br&gt;&lt;b&gt;Related Guides&lt;/b&gt;&lt;br&gt;&lt;a href=&quot;https://www.docuseal.com/guides/send-documents-for-signature-via-api&quot; class=&quot;link&quot;&gt;Send documents for signature via API&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;https://www.docuseal.com/guides/pre-fill-pdf-document-form-fields-with-api&quot; class=&quot;link&quot;&gt;Pre-fill PDF document form fields with API&lt;/a&gt;
           */
          public CompletableFuture<DocusealClientHttpResponse<CreateSubmissionResponse>> createSubmission(
              CreateSubmissionParams request) {
            return createSubmission(request,null);
          }

          /**
           * This API endpoint allows you to create signature requests (submissions) for a document template and send them to the specified submitters (signers).&lt;br&gt;&lt;b&gt;Related Guides&lt;/b&gt;&lt;br&gt;&lt;a href=&quot;https://www.docuseal.com/guides/send-documents-for-signature-via-api&quot; class=&quot;link&quot;&gt;Send documents for signature via API&lt;/a&gt;&lt;br&gt;&lt;a href=&quot;https://www.docuseal.com/guides/pre-fill-pdf-document-form-fields-with-api&quot; class=&quot;link&quot;&gt;Pre-fill PDF document form fields with API&lt;/a&gt;
           */
          public CompletableFuture<DocusealClientHttpResponse<CreateSubmissionResponse>> createSubmission(
              CreateSubmissionParams request, RequestOptions requestOptions) {
            HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

              .addPathSegments("submissions/init")
              .build();
            RequestBody body;
            try {
              body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
            }
            catch(JsonProcessingException e) {
              throw new DocusealClientException("Failed to serialize request", e);
            }
            Request okhttpRequest = new Request.Builder()
              .url(httpUrl)
              .method("POST", body)
              .headers(Headers.of(clientOptions.headers(requestOptions)))
              .addHeader("Content-Type", "application/json")
              .addHeader("Accept", "application/json")
              .build();
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
              client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            CompletableFuture<DocusealClientHttpResponse<CreateSubmissionResponse>> future = new CompletableFuture<>();
            client.newCall(okhttpRequest).enqueue(new Callback() {
              @Override
              public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                  if (response.isSuccessful()) {
                    future.complete(new DocusealClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), CreateSubmissionResponse.class), response));
                    return;
                  }
                  String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                  future.completeExceptionally(new DocusealClientApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                  return;
                }
                catch (IOException e) {
                  future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
                }
              }

              @Override
              public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new DocusealClientException("Network error executing HTTP request", e));
              }
            });
            return future;
          }
        }
