/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.docuseal.resources.submitters.requests;

import com.docuseal.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = GetSubmitterRequest.Builder.class
)
public final class GetSubmitterRequest {
  private final Map<String, Object> additionalProperties;

  private GetSubmitterRequest(Map<String, Object> additionalProperties) {
    this.additionalProperties = additionalProperties;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof GetSubmitterRequest;
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(GetSubmitterRequest other) {
      return this;
    }

    public GetSubmitterRequest build() {
      return new GetSubmitterRequest(additionalProperties);
    }
  }
}
